//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That mountain is big I tell you. But at least we can use the truck to drive there.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road. Proceed into
the <marker name = 'target1'>mountain 1</marker> and for 
also <marker name = 'target2'>mountain 2</marker> clear all Russians from them.



<br/><br/>Eagle Nest<br/><br/>

GEN SITREP<br/>
Todays operation calls for neutralization of Russian infantry from the 
mountain tops of northern Nogova. We still receive some machine gun fire
from helicopter overlights in that area, it needs to be dealt with.
<br/><br/>

INTEL<br/>
You should only expect infantry in the mountains. Don't be surprised if there
are some spez natz forces in the area also. They seem to like hiding out in the
high mountains. No enemy helicopters are flying.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road. Proceed into the
objective mountains and clear <marker name = 'target1'>mountain 1</marker> and
also <marker name = 'target2'>mountain 2</marker> in the area. Good luck.
<br/><br/>

TACTICAL<br/>
Be careful in the mountains, if there are spez natz guys you can have some violent
fights ou there.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Clear mountain #2"];
objective2 setSimpleTaskDescription ["Clear mountain #2", "Clear mountain #2", "Clear mountain #2"];
objective1 = player createSimpleTask ["Clear mountain #1"];
objective1 setSimpleTaskDescription ["Clear mountain #1", "Clear mountain #1", "Clear mountain #1"];
