//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Path clearance for Abrams tanks, then infantry mop up after the tanks. Yeah, lets go.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, assault
the enemy <marker name = 'target1'>base</marker> north of your position.



<br/>Quick Dancer<br/><br/>

GEN SITREP<br/>
Today we are moving against the enemy base just north of our positions in the ruins.
The gunships are grounded because intel has provided anti air threat in the are north
west from the largest mountain of this island. We will deal that threat soon enough.
When this objective has been captured, we can launch quick land attacks further into
the west.
<br/><br/>

INTEL<br/>
We have reason to believe that enemy has stationed shilkas somewhere north west from
your locations, we do not have the exact posit information at this time. Hopefully
we have tracked them down within 24 hours. The enemy base thats targetted today contains
standard infantry defenses and some T-72 tanks.
<br/><br/>

ORDERS<br/>
Alpha and Bravo <marker name = 'start'>start</marker> from the ruins. Alphas job is to secure
the path for the Abrams tanks (Bravo) neutralizing any anti armor threat that might be
in the path. When its safe to proceed, radio call (0-0-1) will be made by Alpha when
Bravo assaults the base. Alpha will mop up any remaining infantry after the tanks have
done.
<br/><br/>

TACTICAL<br/>
No gunship support today, bummer. Hope the intel will find those shilkas soon. Ok make
sure there are no hiding anti armor russians anywhere near the road where our tanks
will come when you order them. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture enemy base"];
objective1 setSimpleTaskDescription ["Capture enemy base", "Capture enemy base", "Capture enemy base"];
