//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Counter attack from North and West, got it. 

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and Bravo are tasked to <marker name = 'start'>Defend</marker> town of
La Riviere.



<br/>Shining Eye<br/><br/>

GEN SITREP<br/>
Our successful operation to capture La Riviere has stirred up the Russians good, 
another large scale counter attack is on our way. Its is our goal to hold this town
at any cost so we can keep limiting the amount of supplies the Russians are 
transferring through ocean into this island. This port is important.
<br/><br/>

INTEL<br/>
We have estimated that at least two full platoons of T-72's are on their way into
La Riviere along with some infantry. Airbase has shown activity once again and it would
not suprise if there whould be few hinds operating in the area also. The counter attack
is coming from general direction of NORTH and WEST.
<br/><br/>

ORDERS<br/>
Alpha and Bravo teams <marker name = 'start'>Defend</marker> the La Riviere against the 
Russian counter attack.
<br/><br/>

TACTICAL<br/>
There is ammo boxes brough to you where you can find LAW's and AA launchers, use 'em. 
Try to set up good defences against armor and infantry in the north and west sides of the 
town, but don't completely leave out the eastern side also. Some sneaky russians might
flank you. Few Vulcans are defending the airspace against Russian helos, but be alert 
anyways and keep AA launcher handy.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend La Riviere"];
objective1 setSimpleTaskDescription ["Defend La Riviere", "Defend La Riviere", "Defend La Riviere"];
