//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Night time duty, defending the captured base. 






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, defend it
through the night.



<br/>Bright Horizon<br/><br/>

GEN SITREP<br/>
The new base just captured might cause some reaction from the Russian side,
this was the only other base in the southern sector of this island. If they
are going to launch counter attack, it will coming most likely tonight.
<br/><br/>

INTEL<br/>
We don't have much to go on. The enemies are quite near, so basically we can 
say that there is imminent attack or no attack is imminent. They are just sitting
there, we just do not know what their intentions are. Enemy helicopters are 
active in the north west but its uncertain if they show up here.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> outside of the base. Bravo and
Charlie start at the <marker name = 'target1'>base</marker> itself. Bravo is infantry
squad and Charlie is M1A2 Abrams platoon. Your mission tonight is to keep the
base secure. Do not let any enemies inside the perimeter, either infantry from
the north west/west or vehicles along the road.
<br/><br/>

TACTICAL<br/>
I would mine the road, definitely. This would also give the engineers something to 
do tomorrow or whenever we are moving our equipment to the west. Its going to be
night time soon so use those night vision goggles to spot the enemy if any of them
decide to join the party.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend the base"];
objective1 setSimpleTaskDescription ["Defend the base", "Defend the base", "Defend the base"];
