//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh man... these missions are the worst. Downed helicopter in the mercy of blood
thirsty enemy. Damn.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from airstrip. Find 
the <marker name = 'target1'>downed OH-58</marker> helo and rescue the crew. 
Get <marker name = 'extract'>extracted</marker> and back to airstrip.
<br/><br/>
Good luck.



Safe Sparrow

GEN SITREP<br/>
Emergency situation has risen, one of our recon birds the OH-58 helicopter went
down in enemy territory. Rescue squad is send to recover the crew.
<br/><br/>

INTEL<br/>
We have the general area where the bird went down but not precise location. Russians
must be aware of the situation also and its most likely that they will send forces
to search the area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from airstrip in Black Hawk which 
will <marker name = 'insert'>insert</marker> you to the enemy territory. Find 
the <marker name = 'target1'>downed OH-58</marker> Recon helo, rescue and give medical 
aid to the possible alive crew, get to the <marker name = 'extract'>extraction</marker> zone
and use radio call (0-0-1) to get black hawk to extract you. Your support is two
AH-64 Apache gunships. Mission is accomplished when you have returned to the 
airstrip safely. Good luck.
<br/><br/>

TACTICAL<br/>
OK no time to chit chat, find the crew and bring them back!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Return to base"];
_objective1 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
_objective0 = player createSimpleTask ["Find the downed helo"];
_objective0 setSimpleTaskDescription ["Find the downed helo", "Find the downed helo", "Find the downed helo"];
