//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Some remaining russians hmm.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Vigny, proceeds and
clears <marker name = 'target'>coast</marker> line.



Red Harvest

GEN SITREP<br/>
Our succesful operation against La Pessagne has ran some Russians into the
west coast line, they are still threat to our troops so we need to take them
out.
<br/><br/>

INTEL<br/>
No armor are present in the western sector, only infantry. Enemy airbase is 
showing activity again.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Vigny, proceed and sweep
all the <marker name = 'target'>coast</marker> line up to the area marked by dots.
<br/><br/>

TACTICAL<br/>
This should be cakewalk, just infantry mostly hiding in the coastal hillside.
Stay alert anyways. You should not need any AA weapons since our vulcans are 
guarding the airspace around this area. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep out enemies"];
_objective0 setSimpleTaskDescription ["Sweep out enemies", "Sweep out enemies", "Sweep out enemies"];
