//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That was some patrol, wonder why there was so little enemy infantry present in the
Saint Phillippe, I had the idea on my head that we are in for a big fight overthere.
<br/><br/>

Oh well. The guys asked me to join this Recon flight near the airbase. This might be a 
nice change for a while.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Get onboard the UH-60 Blackhawk and recon the area from air.
<marker name = 'start'>here</marker>.



<br/><br/>Flyboys<br/><br/>

There was very low resistance on Saint Phillippe and the Hospital, our patrol
cleared them out nicely.
<br/><br/>

Intel estimates there is no threat for any enemy attack for now. Seems like we really 
took them by surprise here, it could take a while until they get their act together. 
<br/><br/>

We are still building up our forces and you have some free time...

<br/><br/><br/>












"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Recon flight"];
objective1 setSimpleTaskDescription ["Recon flight", "Recon flight", "Recon flight"];
