//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



We are off to the morning patrol. Goddamn I have been up all night and now
the commander ordered me to patrol. Beautiful, welcome to the U.S. Army!
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Good morning soldiers. We'll start this fine day by doing some patrol in the nearby
 areas to make sure there are no Russians lurking around.<br/><br/>

You'll start <marker name = 'start'>here</marker>, the patrol areas defined are the city of
Saint Phillippe <marker name = 'patrol1'>here</marker> and the hospital 
<marker name = 'patrol2'>here</marker>



<br/>Patrols<br/><br/>

We start to move along due south. Now we see what we are up against in this island.
<br/><br/>

No intel to provide you as you are going to be the intel collector in this patrol. We do 
not have detected any air activity from the Russians yet which seems very odd. 
<br/><br/>

The morning patrol contains two locations to be scouted out. You are part of the three
man patrol <marker name = 'start'>here</marker>, the first objective is to patrol city of 
Saint Phillippe <marker name = 'patrol1'>here</marker> and second objective is to check out
 the hospital <marker name = 'patrol2'>here</marker>

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Patrol the Hospital"];
objective2 setSimpleTaskDescription ["Patrol the Hospital", "Patrol the Hospital", "Patrol the Hospital"];
objective1 = player createSimpleTask ["Patrol Saint Phillippe"];
objective1 setSimpleTaskDescription ["Patrol Saint Phillippe", "Patrol Saint Phillippe", "Patrol Saint Phillippe"];
