//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Durras makes me hurrrr maan... That freaking sniper almost got me, the enemy is definitely
pushed off from this island, but they keep a darn good defence until we get them out. 
<br/><br/>

And today we make fast assault to that castle, well I always wanted to be a King heheh!
<br/><br/>
Hooayh!
<br/>
"]];
player createDiaryRecord ["Diary", ["Mission", "Alpha and Bravo squads <marker name = 'start'>start</marker> from the base. Objective
is to assault and clear the <marker name = 'target'>target</marker> castle.
<br/><br/>
Good luck!
<br/>

<br/><br/>
Ghosts
<br/><br/>

Front line forces have captured the city of Durras. We have fortified positions in that
location and there is no enemy counter attack detected. They are kept back by our forces
and dont have the mass to engage counter offensive.
<br/><br/>

Intel estimates that the castle is used as Command and Communications site for the
remaining Russian forces in the southern part of Everon. Our aerial reconnaisance have 
learned that there are lot of infantry and few heavy armored vehicles present in the 
area around in and around the buildings. Enemy has used this as CC site since we captured
the base earlier. We have reason to believe that high ranking officers are gathered in
the castle.
<br/><br/>

Alpha and Bravo squads <marker name = 'start'>start</marker> from the field base, from where
they board two UH-60 Blackhawk helicopters. The helos then carry the squads to 
the <marker name = 'meet'>meet</marker> point where they wait for everybody to get ready. When
all forces are ready the code word KINGDOM is issued, that launches the operation.
Objective is to attack and clear the Command and Communications site in 
the <marker name = 'target'>castle</marker> at the hilltop.
<br/><br/>

Our mission is to attack and capture the <marker name = 'target'>castle</marker> high in the 
mountains. Blackhawks come to pick you guys up at the <marker name = 'start'>base</marker> and
you will board the second helo, Bravo takes first. You will wait the operation commence
code word (finely selected KINGDOM) at the <marker name = 'meet'>meet</marker> point.
After mission commences you are inserted into the yard of the castle, which is very high
risk situation. We dont have any other choice if we want to take these guys at surprise, 
the terrain is extremely hazardous for helos to land elsewhere. Good tip is that when the 
helos get low enough for you to safely jump out, do it. Move fast when on the ground and 
dont get caught in the enemy fire. Watch out the guys in the castle tower and also the 
armored vehicles. The intel dont have enough information about the hillsides, but we have
to assume there are more troops nearby and at least some patrols. Be careful out there.
"]];
// tasks need to be in reversed order
// objective2 moved to objective2.sqf file
objective1 = player createSimpleTask ["Assault the Castle"];
objective1 setSimpleTaskDescription ["Assault the Castle", "Assault the Castle", "Assault the Castle"];
