//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The ruins in the hilltop should be easy, Dolina should not... we'll soon see.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road. Assault
and capture <marker name = 'target1'>hilltop</marker> and then 
proceed to capture <marker name = 'target2'>Dolina</marker> town.



<br/><br/>White Knight<br/><br/>

GEN SITREP<br/>
Today we move forward towards Dolina. We will try to capture it cutting off the
road coming from south. This hopefully gives more trouble for the Russian armored
vehicles in the north.
<br/><br/>

INTEL<br/>
We are looking several vehicles in Dolina along with the infantry. There is no sign
on air defenses, no sign on enemy helicopters. The hilltop contains only infantry
apparently.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road. Move to the west
and assault the <marker name = 'target1'>hilltop</marker> and make sure no Russians
are left there. From that point proceed into <marker name = 'target2'>Dolina</marker> town
and neutralize all enemies in the area. Your backup is AH-64 Apache gunship. Good luck.
<br/><br/>
<br/>
TACTICAL<br/>
The hilltop should be pretty easy, but you must make sure the whole wide area in that 
hill is cleared out. When you have accomplished that I'd suggest you should let the
Apache to kick some butt in Dolina before charging in. Ok take them down!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Dolina"];
objective2 setSimpleTaskDescription ["Capture Dolina", "Capture Dolina", "Capture Dolina"];
objective1 = player createSimpleTask ["Capture Hilltop"];
objective1 setSimpleTaskDescription ["Capture Hilltop", "Capture Hilltop", "Capture Hilltop"];
