//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Dourdan is our objective. And nice objective it is.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Bravo team <marker name = 'start'>start</marker> from Arudy. Objective is to
capture <marker name = 'target1'>Dourdan</marker> from Russians.
<br/><br/>
Good luck.



<br/>Urgent Angel<br/><br/>

GEN SITREP<br/>
Pushing forward towards north, next goal is to seize the town of Dourdan just south
of La Trinite, one of the biggest cities in Malden.
<br/><br/>

INTEL<br/>
Small number of enemy armor, no helicopter activity on the airbase. Mostly infantry
patrolling Dourdan area.
<br/><br/>

ORDERS<br/>
Bravo squad <marker name = 'start'>start</marker> from Arudy, you are to proceed along the
road into <marker name = 'target1'>Dourdan</marker> and capture it. Use radio (0-0-1) to call
up <marker name = 'alpha'>Alpha</marker> squad who will attack from south side of Dourdan.
Your mission is accomplished when we have full control over Dourdan.
<br/><br/>

TACTICAL<br/>
Should be routine attack for you by now. No enemy helos present, no heavy armor, just
the good old ruskie infantry.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Dourdan"];
objective1 setSimpleTaskDescription ["Capture Dourdan", "Capture Dourdan", "Capture Dourdan"];
