//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Kingdom... that freaking kingdom almost got me killed! That was some intense firefight
indeed, seems like the Russians were bit upset of us capturing their Comms site, huh?
<br/><br/>

Okay so we have now to clear out the southern tip of the island.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team will <marker name = 'start'>start</marker> near the castle and proceeds to clear
out any enemy forces in the <marker name = 'sweep'>area</marker> marked with red dots.
<br/><br/>

Go get them Alpha.

<br/>



<br/><br/>Lighthouse<br/><br/>

Russians launched major counter attack when we captured their Comms site in the castle,
they still have some armored units left to use small scale offensives. That move however
was somewhat surprising to us, we expected some reaction but not that heavy. Now we
control the castle and have spotters on the front line to overwatch Saint Pierre collecting
intel of the Russian defensive positions in the city. It should not take long before we 
are ready to launch full scale assault to Saint Pierre.
<br/><br/>

Intel reports that since the castle fell to the NATO forces, the remaining Russians on the
grounds are somewhat scattered around without coordination. We have no indication of any
other type of units except infantry and even there are no AT detected. Lack of AT forces 
is we believe because the terrain is so harsh, no armor is expected to be operating in the
area. We had limited intel on infantry in the area by the helos supporting the castle 
strike, we dont have our own intel birds in the air yet due the Spez Natz attack. We have
new equipment coming very soon to support our operations.
<br/><br/>

Alpha Black's <marker name = 'start'>start</marker> is just near the castle, the squad is put
together only from 4 operatives currently. We believe its enough for a sweep through this
sector. Orders are to search the <marker name = 'sweep'>area</marker> marked by red dots for any
enemy activity.
<br/><br/>

We have some mopping up to do. The castle <marker name = 'bravo'>comms site</marker> raid took 
the enemy by surprise and now the remaining Russians are trying to organize in the south 
of the castle without much of an coordination. Its Alpha squads objective to more disrupt 
that operation. You lead three other lightly armed men (no anti armor weapons needed) into
the <marker name = 'sweep'>area</marker> to conduct search and destroy mission. Do not wander 
outside of the sector marked with red dots. You are free to engage any enemies you find in 
the area. No armor should be present and the opposition should be light, meaning the intel
peeps haven't detected much of activity from the limited aerial reconnaisance.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear sector"];
objective1 setSimpleTaskDescription ["Clear sector", "Clear sector", "Clear sector"];
