//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




These mountain operations are quite demanding on ones physical fitness. But hey
I never turned down a nice jog.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the 
base, <marker name = 'target1'>sweep</marker> the mountain downhill up to 
the friendly positions in <marker name = 'alpha'>beach</marker> road.



<br/>Downhill<br/><br/>

GEN SITREP<br/>
Russians tried to retake the base in the early evening last night, they failed
mostly due the great work of our infantry who were defending the objective. There
is big weather front moving in this region which could bring heavy rain, our weather 
team is monitoring the fronts movements. Next few days we are setting up a plan to 
attack the enemy base just South East from the one we just captured. In order to do 
so there is another mountain sweeping to be done. The target area is east from the 
captured base, all the way downhill into the beach where our front line positions 
are located.
<br/><br/>

INTEL<br/>
As to be expected in this highly rugged terrain, no vechiles of anykind are operating
so you'll be facing only light infantry. Helicopters have been flying in the south, 
its uncertain if they will approach this area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base. Move downhill from there
and <marker name = 'target1'>sweep</marker> the mountain areas. Do not wander of too much
into the south where strong enemy defenses are located. When you reach the NATO positions
in the <marker name = 'alpha'>beach</marker> road, your mission is accomplished.
<br/><br/>

TACTICAL<br/>
Another light mission for you, we have ripped your squad of any heavy weapons as they just
slow you down in the mountainous area. This time however you're in lucky, you are going
downhill so it would be much easier. Do not however lose focus for a second, you know
that if you slip and fall, you are a dead soldier. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Sweep the mountain"];
objective1 setSimpleTaskDescription ["Sweep the mountain", "Sweep the mountain", "Sweep the mountain"];
