//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




We have long way to go into the intersection, which is defended. This is going
to make me sweat...






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road. Sweep the area
towards north east into the <marker name = 'target1'>intersection</marker> which
you will clear from any enemy forces.



Dark Star

GEN SITREP<br/>
Very successful Grey Thunder operation was completeled yesterday, our forces 
struck the Russian infantry and armor in their base neutralizing all of them.
This was one major victory in this war, we have now access for our tanks to
travel through the roads into the central Kolgujev. 
<br/><br/>

INTEL<br/>
We do not have much intel on the terrain ahead, there is not many vehicles as
the terrain is not that suitable for them. Enemy helos are still keeping their 
distance to the front line.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road south west from the
just captured base. Proceed into north west through the harsh terrain clearing
it out from any enemy forces. Go until you arrive into 
the <marker name = 'target1'>intersection</marker> which if occupied by enemy troops.
Clear out all of them. Your mission is accomplished when you have control of that
intersection.
<br/><br/>

TACTICAL<br/>
Okay the Bravo squad is running with M113 just behind you, they will slowly move 
along the road and Charlie M1A1 tanks are following them. They will meet you in
the objective. Be careful in the terrain, watch out for the woods. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Clear intersection"];
_objective0 setSimpleTaskDescription ["Clear intersection", "Clear intersection", "Clear intersection"];
