//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Bring it on dirty you ivan, you ain't scaring me! Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha and Bravo teams <marker name = 'start'>start</marker> from La Trinite, 
defend it all costs.
<br/><br/>
May God be with you.



Dark Jewel

GEN SITREP<br/>
Russians are launching full scale counter attack to reclaim La Trinite, which
we will not give to them. We still havent got Vulcans to the town so no AA cover.
<br/><br/>

INTEL<br/>
Its estimated that they are sending everything they got in hand. Infantry, tanks,
helicopters. 
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> at La Trinite which you are
to defend at all costs. There is heavy Russian 
counter <marker name = 'attack'>attack</marker> coming so dug in and repel the enemies.
<br/><br/>

TACTICAL<br/>
OK relax, we need your cool on this one. There is ammo box in the downtown with 
stinger and LAW launchers, use them how you please as there is no vulcans around.
Stay healthy...
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Repel Russian counter attack"];
_objective0 setSimpleTaskDescription ["Repel Russian counter attack", "Repel Russian counter attack", "Repel Russian counter attack"];
