//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Beach road clearing. fortified enemy defenses. nice.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from base, you'll 
be <marker name = 'insert'>inserted</marker> into a road. Meet up 
with <marker name = 'bravo'>Bravo</marker> squad and seize the
enemy <marker name = 'target1'>positions</marker> in the road.



Rolling Blaze

GEN SITREP<br/>
Today we go against the eastern coastal road, our attempt is to push forward
so that we can set up better area for our attacks into the central island.
<br/><br/>

INTEL<br/>
There are heavy infantry dug in positions ahead, some armored vehicles are
supporting them. Helicopters have been active in this part of the island.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at the base, helicopter 
will <marker name = 'insert'>insert</marker> you to a road, proceed into the
front line positions (aboard the 5t truck that is waiting for you) where you 
meet <marker name = 'bravo'>Bravo</marker> squad. When you're joined up with 
them, <marker name = 'target1'>attack</marker> the enemy positions ahead. Do not 
advance further than out target objective. We do not want to get stretched 
too thin. Mission is accomplished when you're reached the objective and all 
Russians have been neutralized from the area.
<br/><br/>

TACTICAL<br/>
This road is heavily defended, you'll meet infantry who is waiting for you. Be 
very careful, move slowly and keep it low.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Seize road objective"];
_objective0 setSimpleTaskDescription ["Seize road objective", "Seize road objective", "Seize road objective"];
