//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Man that M113 is one slow vehicle to climb hills, my granny could go faster. But of course
the granny is much more vulnerable to assault rifle fire...
<br/><br/>

I must use surprise and precise fire with this mission, the tank crew must be neutralized
before they get inside the tank, I rather deal with three guys running around with AK's 
thank heavy T-72 tank!
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Wipeout enemy <marker name = 'ammodepot'>ammo depot</marker>




<br/><br/>Ammo Depot<br/><br/>

We continue to buildup the Montignac defences, they are looking good already and we can
most likely repel the enemy attacks. We move along in the eastern sector and today the 
enemys ammo depot is next to go.
<br/><br/>

The intel has no indication of any enemy counter attack in the Montignac region, seems like
the Russians have problems gathering up enough firepower to oppose us in that city. Our 
Recom Team has reported that the ammo depot has three trucks and one T72 tank. The T-72 was
not manned at the time of report, they just seem to sit there. Minimal guard activity, but
there are reasonably amount of infantry in the depot.
<br/><br/>

Your team is located east of Entre Deux <marker name = 'start'>here</marker> where you got the
M113 at your disposal. The enemy ammo depot is 
located <marker name = 'ammodepot'>here</marker>. Your orders are to assault and take this depot 
from the Russians. Try to get the enemies by surprise, as it seems that the T-72 is not
manned at the moment, so if you can kill the crew before they get into the tank, you will
have much better tactical situation.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Wipe out enemy ammo depot."];
objective1 setSimpleTaskDescription ["Wipe out enemy ammo depot.", "Wipe out enemy ammo depot.", "Wipe out enemy ammo depot."];
