//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The Russians have REALLY good defenses around here. Its going to take some
real fighting when we assault the western part. Okay the guys performed
well yesterday and I just hope we continue to have good luck today. I just
need to keep my team as stealthly as possible and avoid enemy contacts.
<br/><br/>
When we spot the Scuds, we take them out quickly and escape before Russian
patrols reach the battle point. There is not much time after the first shot
is fired and when new Russians arrive at the scene, especially those BMP's
can get there real quick when they run at full speed. Even BMP's we can handle
if there is no more than one or two, but if we get T-72 or worse, T-80's then
its totally different ballgame.
<br/><br/>
Be stealthy. Avoid enemy contact. Strike quick and escape! I need to repeat that 
to myself over and over again.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from forest, hunt
the <marker name = 'target1'>Scuds</marker> and 
reach <marker name = 'camp'>campign</marker> point.



Scud Hunt 2, Day 2

GEN SITREP<br/>
none
<br/><br/>

INTEL<br/>
none
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from forest, hunt 
the <marker name = 'target1'>Scuds</marker> and when done, reach 
the <marker name = 'camp'>campign</marker> point safely.
<br/><br/>

TACTICAL<br/>
none
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Reach campign point"];
_objective1 setSimpleTaskDescription ["Reach campign point", "Reach campign point", "Reach campign point"];
_objective0 = player createSimpleTask ["Hunt Scuds"];
_objective0 setSimpleTaskDescription ["Hunt Scuds", "Hunt Scuds", "Hunt Scuds"];
