//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh my God...<br/><br/>

I am Prisoner of War... damn... how did this happen?
<br/><br/>

Oh...<br/><br/>

My team... all gone... dead... oh my God...






"]];
player createDiaryRecord ["Diary", ["Mission", "











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Follow their orders, or die."];
objective1 setSimpleTaskDescription ["Follow their orders, or die.", "Follow their orders, or die.", "Follow their orders, or die."];
