//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Damned those enemy snipers, they are the worst... Good thing we had some aircraft overhead
which they could direct to our help. Dunno what might have happened if we would had no
support.
<br/><br/>

Oh well today we take jeeps and drive around, drive around the country side and shoot stuff
up. Hey sounds cool to me!
<br/><br/>

I just need to remember to move, drive fast and stay far away from the enemy. I don't want 
to get stuck anywhere because then the enemy soldiers have too easy target to shoot at. 
So speed and range is essential.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team will take four machine gun jeeps from the <marker name = 'start'>chapel</marker> in 
the hilltop.
<br/><br/>

You must <marker name = '2'>Sweep</marker> the eastern sector for any enemies hiding in there.
<br/><br/>

There is helicopter gunship support too.




Sweep

We continue wiping out the Russian positions on Everon.
<br/><br/>

Not much of an intel to provide you, we have some remaining infantry located in the eastern
part of this sector, they are mostly hiding in forests but they have been observed moving 
a bit too. There seem not to be any larger vehicles in this area and no heavy weapons like
anti armor.
<br/><br/>

Sweep the area <marker name = '2'>here</marker><br/>
Use the speed for your advantage, do not get caught in close up fire fight as you are just
sitting duck in the jeep. Use movement and fire from long ranges to mop up any Russian 
forces hiding or moving about.

<br/><br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep the area"];
_objective0 setSimpleTaskDescription ["Sweep the area", "Sweep the area", "Sweep the area"];
