//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




North from Goisse, time to kick some Russian infantry again.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> at buildings, clear out
the <marker name = 'target1'>hill top</marker> and capture 
the forest <marker name = 'target2'>road</marker> and 
the <marker name = 'target3'>area</marker> just north of Goisse.



<br/>Safe Hat<br/><br/>

GEN SITREP<br/>
We are preparing to assault La Trinite but in the mean time we must also keep
the pressure up in the western side of the island. Today we're sending squad
to clear our the are north of Goisse. It hopefully also could effect as bait
to make the Russians move more troops into north west side of Malden.
<br/><br/>

INTEL<br/>
You'll be expecting some helicopter activity today but we have Vulcan stationed
in Goisse to secure the air space. Infantry is on defensive mode and some armored
vehicles is also present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> near the buildings. You must clear out
the <marker name = 'target1'>hill top</marker> north from your position, from that hill
you descent down to the forest <marker name = 'target2'>road</marker> and capture that
location. The position north of Goisse located <marker name = 'target3'>here</marker> must
be also be wiped out for any Russians. Of course all the surrounding areas where you get
enemy contacts are free engagement zone for you, but do not proceed too much to the 
north of especially along the road down to Larche. We are not attacking them yet.
<br/><br/>

TACTICAL<br/>
Today we got enemy helo threat but luckily Vulcans are stationed in Goisse. Prey that they
chew up the birds in the air before they get to you. Watch out also for the open areas before
you hit the first objective, its good shooting area for helos. Bravo squad is stationed at
Goisse but they are prohibited only to provide defensive force for the town, they will not
join your fight today. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Clear road north of Goisse"];
objective3 setSimpleTaskDescription ["Clear road north of Goisse", "Clear road north of Goisse", "Clear road north of Goisse"];
objective2 = player createSimpleTask ["Capture forest road"];
objective2 setSimpleTaskDescription ["Capture forest road", "Capture forest road", "Capture forest road"];
objective1 = player createSimpleTask ["Clear the hill top"];
objective1 setSimpleTaskDescription ["Clear the hill top", "Clear the hill top", "Clear the hill top"];
