//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh my. Now this is getting interesting, why am I, the professional soldier put
on a babysitting job? Why do I need to be a bodyguard? what do I know about such
things... I just blow russians away... hmm. 






"]];
player createDiaryRecord ["Diary", ["Mission", "


You are bodyguard for our Colonel and <marker name = 'start'>start</marker> from base.
Travel with him to the <marker name = 'insert'>chapoi</marker> where he gives 
public <marker name = 'speech'>speech</marker> to the civilians. Keep him safe.
<br/><br/>
Stay sharp.



<br/><br/>Guardian<br/><br/>

GEN SITREP<br/>
Our Colonel is handeling some Malden public relations and hes making a speech in
the city of Chapoi. We must make sure he stays healthy during this trip.
<br/><br/>

INTEL<br/>
Umm, you need intel for this? well NATO forces all around you. Lots of armor, lots of
infantry, lots of AA sites, lots of helicopters... Oh yeah the Chapoi is now full of civilians
who are to hear the Colonels speech.
<br/><br/>

ORDERS<br/>
You have been selected out of many cancidates to be a bodyguard for our Colonel. We know 
this is not the usual stuff you do, but at the moment you are the soldier in the field 
who has the most combat experience. You mission objectives are simple, keep the Colonel safe.
You'll be flying with him into <marker name = 'insert'>Chapoi</marker> in Blackhawk helicopter, 
where he gives the <marker name = 'speech'>speech</marker> to the civilians. When the speech is 
complete, you both will board the Blackhawk that awaits and fly back to base. Easy task.
<br/><br/>

TACTICAL<br/>
Well damnit, didn't they find anyone better for such bodyguard job than you. We will miss
you in the front lines, oh well we'll bag for Ruskies for ya while you're babysitting. 
See ya later.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Keep Colonel safe."];
objective1 setSimpleTaskDescription ["Keep Colonel safe.", "Keep Colonel safe.", "Keep Colonel safe."];
