//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Oh my what kind of mayhem was the battle for the base, well NATO delivered and now we
control the only real base the Russians had in Everon. It will be great forward base to 
launch attacks into the enemy territory.
<br/><br/>
    So today we are alone with my squad, we are to clear that road block for engineers 
    and then to take the hilltop. I just hope we don't run into any troubles with 
    this op, when it sounds too easy, it usually is not! <br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha squads starting location is <marker name = 'start'>here</marker> in the intersection.
<br/><br/>

Seize the <marker name = 'road'>road block</marker> and hold it until the engineer team will 
arrive.<br/>
Second objective is to take the <marker name = 'hill'>hill</marker>





Road Block

Russians took heavy loss in the battle of the base, they lost two platoons of tanks, two 
squads of men, some guards and few bmps, also their reinforcements where wiped out.
<br/><br/>
  Intel estimates that enemy forces cannot make any kind of offensive maneuver's 
  at this time, we have incapacitated their offensive capability. They are just 
  reinforcing their positions over the front lines, trying to hold us back as 
  much as possible. The road that comes into this base, goes through very narrow 
  bottleneck type woods and the enemy has fortified a road 
  block there. We are launching assault to take that road block down, you'll 
  lead this assault with the normal squad of men. The road block is probably mined, 
  so we send out engineer team to clear it out after you have successfully eliminated 
  all enemy resistance there. When the road block is seized, wait for the engineer 
  team to arrive.<br/>
When freed by PAPA BEAR you are to proceed into the secondary objective which is taking the
<marker name = 'hill'>hill top</marker> where the chapel is located. There must be enemy present
so be careful when approaching it. We suggest you proceed along with the dirt road. 
You are free to engage any enemies you find on that hill.

<br/><br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Take the hill"];
_objective1 setSimpleTaskDescription ["Take the hill", "Take the hill", "Take the hill"];
_objective0 = player createSimpleTask ["Seize road block"];
_objective0 setSimpleTaskDescription ["Seize road block", "Seize road block", "Seize road block"];
