//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That damned T-80 got me scared for a while, now why didn't I bring some AT stuff with me.
Hehe anyways, hes history now so what the heck, new day, new mission. Hooyah!
<br/><br/>

Ambushing enemy convoy in early hours, what can be move fun in the morning.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Enemy convoy is <marker name = 'convoy'>starting</marker> from Saint Pierre and heading
to the <marker name = 'convoydest'>lighthouse</marker> in the beach. Kill the convoy.
<br/><br/>

Have fun.
<br/>



<br/>Good morning Everon<br/><br/>

We have gathered intelligence on the Saint Pierre now and it seems that they have put 
extremely heavy defences there. We are still sorting out all the intel and have clearer
picture shortly. Looks like the Russians are really going to fight for Saint Pierre, the
last foothold they have on Everon.
<br/><br/>

Okay we have hit the jackpot. Intel has learned that there are enemy convoy travelling 
from Saint Pierre to the lighthouse on the beach in the morning. The units in the convoy
contains T72, BMP and two trucks full of infantry, the leading vehicle is UAZ. We believe
that this is attempt to sneak the people to the southside of the castle, possibly to mount
an another counter attack to retake it. Russians are extremely pissed off for losing the 
castle to us, no doubt about that now.
<br/><br/>

Bravo will get positioned <marker name = 'bravo'>here</marker> between the hillsides. Charlie 
will handle cutting off the target, they will <marker name = 'charlie'>wait</marker> until the 
ambush commences, from where they will move into position<br/> 
to <marker name = 'charliecutoff'>cut off</marker> the convoy. Attack commences when the convoy
reaches about this <marker name = 'ambush'>ambush</marker> point.
<br/><br/>

The intel has real sweet info for us, an juicy enemy convoy with knowledge of the exact 
route and time... what else could an nasty ambusher ask? Okay so we run this op in three
teams Alpha, Bravo and Charlie. Bravos will <marker name = 'bravo'>position</marker> themselves 
between the hillsides, Bravo will radio you when they start to shoot, its when the
convoy reached this <marker name = 'ambush'>ambush</marker> point in the road. Charlie 
first <marker name = 'charlie'>waits</marker> until the attack commences and then moves 
into <marker name = 'charliecutoff'>cut off</marker> position to make sure no enemies gets 
away. The convoy is total 5 vehicles, intel has provided with good stuff today, the lead
is UAZ and then comes T-72, BMP with following two Ural trucks. Use the engineer guy to 
plant mines in the road, that will help you to deal with the armor, altough you have strong
anti armor team together in this mission. Be careful, we have good intel but dont get cocky
in there. Do the job with decisive and accurate blow to the convoy. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Kill the convoy"];
objective1 setSimpleTaskDescription ["Kill the convoy", "Kill the convoy", "Kill the convoy"];
