//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Sweep mission, hooyah! I must use caution near the ditch, who knows what might
lie in there.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, approach the
target <marker name = 'target1'>ditch</marker> and neutralize all enemies on the
way there.



Passage

GEN SITREP<br/>
Now we have control over the road system to the central island, there is still one
piece of dirt road into the ruins and from the base into the main road on northern
coast and we can freely move around on both sides. But so far we do fine with just
the southern passage. 
<br/><br/>

INTEL<br/>
We have some armor movement in the base due north of the ruins and your target 
objective. Helicopters are not expected to operate in the front lines. Your 
sweep are should only contain infantry remains.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the friendly dirt road, take
the heading of NW or W and proceed into the 
target <marker name = 'target1'>ditch</marker> which is in the beside the highest 
mountain of Kolgujev. Your operational area is pretty much marked with the blue
arrows. Follow that path and neutralize all enemies encountered. Your mission is
accomplished when you have cleared out the ditch.
<br/><br/>

TACTICAL<br/>
This should be rather easy, our armor has reached the south-west intersection from
your operational area, thats covered. Same thing with north, there is friendly forces.
Just sweep out those enemies that are left in this narrow passage. Be careful in
the mountain edge, Spez Natz forces seem to enjoy the mountain life and they can be
around there. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Clear out the ditch"];
_objective0 setSimpleTaskDescription ["Clear out the ditch", "Clear out the ditch", "Clear out the ditch"];
