//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The bridge, now we must be very careful not to blow that thing up, its a shame
really, it would be nice to bring it down with few squads of infantry and russian
tanks on it! Oh well.
<br/><br/>
by the book, by the book...






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from hill, assault
and capture the <marker name = 'target1'>bridge</marker> from enemy.
<br/><br/>
Good luck.



Blood Tide

GEN SITREP<br/>
Today NATO launches operation against the Nogova bridge held by the Russians. 
Our objective is to capture the bridge undamaged, we want it in one piece as 
its no good for us if its in the bottom of the river.
<br/><br/>

INTEL<br/>
Both sides of the bridge is defended with heavy Russian armor and infantry,
the enemy helos are flying very near and its more than likely that they join
the fight today. The area west of the river, church and so on is most likely
to have another line of heavy defenses.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the hill. Proceed into 
the <marker name = 'target1'>bridge</marker> and capture it undamaged. Your support
forces are <marker name = 'bravo1'>Bravo</marker> squad, M1A1 Abrams platoon 
callsign <marker name = 'ustanks1'>Charlie</marker> and AH-64 Apache gunship callsign 
Echo. Alpha squad issues the radio call (0-0-1) to initiate air support and 
radio call (0-0-2) to commence the ground assault. This mission is accomplished 
when all Russians are run off from the bridge. Good luck everyone.
<br/><br/>

TACTICAL<br/>
Ok this is delicate one, DO NOT DESTROY THE BRIDGE. Actually I'm not worried about
you but those bonehead tanks and gunships, they tend to blow stuff up just for
the fun of it neglecting the factor that there in fact is this thing called 
collateral damage. But at least try to keep this one clean, ok? 
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture bridge"];
_objective0 setSimpleTaskDescription ["Capture bridge", "Capture bridge", "Capture bridge"];
