//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Going to the beach. Time to put end on the water sports for Russians.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Dolina, assault and
capture <marker name = 'target1'>Beach Resort</marker> and 
the <marker name = 'target2'>Joudov</marker> in the hill.



Unforgiving Hawk

GEN SITREP<br/>
The beach resort by the river is used to accomodate Russian infantrymen now,
it was used by tourists before the occupation. We will like to change that 
back to the tourism days. Secondary objective in todays operation is the Joudov.
<br/><br/>

INTEL<br/>
There is mostly relaxed infantry on the beach resort, some armored vehicles
are nearby. The Joudov area is more heavily defended. No helicopters at all.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Dolina, assault and capture
the <marker name = 'target1'>beach resort</marker> and also 
the <marker name = 'target2'>Joudov</marker> in the hill. Good luck.
<br/><br/>

TACTICAL<br/>
When attacking the objective one, watch out for Joudov as they might launch some
reinforcements.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture Joudov"];
_objective1 setSimpleTaskDescription ["Capture Joudov", "Capture Joudov", "Capture Joudov"];
_objective0 = player createSimpleTask ["Capture beach resort"];
_objective0 setSimpleTaskDescription ["Capture beach resort", "Capture beach resort", "Capture beach resort"];
