//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Well another sit back relax mission for me. I'm not sure if I even should bring my beloved
COLT M-16 assault rifle with me... oh well, how could I leave my sweetheart honeybunny 
behind.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Aerial Reconnaisance
<br/><br/>

Bravo (UH60) starts from <marker name = 'start'>Home Base</marker> and flies along the enemy
coastline conducting reconnaisance starting <marker name = 'reconstart'>here</marker> and 
gathering intel for <marker name = 'regina'>Regina</marker> city, finally ending at the other 
 <marker name = 'reconend'>side</marker> of the island.





<br/>Aerial Recon<br/><br/>

Our plans move forward to attack Regina in the next available moment.
<br/><br/>

Intel has very scattered information about enemy movements in the Regina city.
<br/><br/>

You are scheduled to take part on the aerial recon flight along the enemy coast. The
flight starts from <marker name = 'start'>Home Base</marker> and recon commences 
<marker name = 'reconstart'>here</marker> and then continues to <marker name = 'regina'>Regina</marker> 
 city, where it proceeds along the <marker name = 'dot_23'>coastline</marker> all the way to 
the other side of the island <marker name = 'reconend'>here</marker><br/>
You will be with two intelligence officers in this flight.
<br/><br/>

The job at hand is a cakewalk, just enjoy the ride and keep an eye for the enemy forces
in the recon area. What you learn here will help us defeat the enemy in Regina area lateron.

<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Recon Regina"];
objective1 setSimpleTaskDescription ["Recon Regina", "Recon Regina", "Recon Regina"];
