//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



My God was that recon helicopter ride something else!
<br/><br/>

Not in my wildest dreams I could have expected to get killed in a mission like that, it 
was total cakewalk and look what it got me... Oh my, oh my.
<br/><br/>

Speaking of getting killed, this next mission is right in my alley. Straightforward good
ol' infantry combat in the bushes. This is what I like, this is what I do. So bring it on
you bush hiding bastard commies, NATO is coming to kick your ass!







"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and Charlie starts from <marker name = 'start'>here</marker> in the homebase.
<br/><br/>

Sweet through the <marker name = 'area'>area</marker> to clear out any enemy forces.





<br/>Road Block<br/><br/>

Our assault to Regina is just one push away. Forces are getting ready as of now.
<br/><br/>

We have made some overflight passed on the area north of Regina and south/south-west from
our base, there has been no armor or vehicle activity since the large Russian assault. We
do not have good information of enemy infantry, we do know that there is no major forces
in the area, but pockets of resistance could easily be camouflaged in the terrain that our
overlights do not detected. Russians are known to duck for cover when NATO birds are in the
area, if you know what I mean.
<br/><br/>

Our mission is to sweep through the area north of Regina. Alpha team boards 5t truck and
is driven to the <marker name = 'insert'>insertion</marker> point. Where they proceed into the
<marker name = 'area'>southern area</marker> clearing out any enemy 
resistance. <marker name = 'cmove1'>Charlie moves</marker> on foot to the nearest woods 
south-east from our base, their job is to clear 
the <marker name = 'woods'>woods</marker> area. When both teams are done, they 
will <marker name = 'meet'>meet</marker> on the selected point. Nobody is authorized to move 
more further south than the meeting point.
<br/><br/>

Use caution on this one, the intel does not obtain information of any large scale enemy 
forces in this area but its most certain that there are pockets of enemy infantry hiding in
the terrain. The area is secure all the way up to the insertion point, but from that point
to the south we have not clear picture. When you get into the meeting point, you must stop 
there. You are not allowed to proceed any further south (towards Regina) as it would draw 
too much attention to our presence in the area. We want to keep the Russians calm in the
city before we launch the assault. So stop at the meeting point.
<br/><br/>














"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Sweet the area"];
objective1 setSimpleTaskDescription ["Sweet the area", "Sweet the area", "Sweet the area"];
