//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Merry Xmas, yeah... its nice to be fighting a war when we should be sitting in 
home near a fireplace getting presents. Oh well, I might as well give few nice
presents for Ivan this year.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Dolina. Assault
and clear the <marker name = 'target1'>intersection</marker> and wait for
backup. When they arrive capture <marker name = 'target2'>Mokropsy</marker> town.
<br/><br/>
Merry X-Mas and good luck!



<br/>Santas Bag<br/><br/>

GEN SITREP<br/>
Soldiers, airmen and navy personnel, we have come long way in the war against Russians. 
Today we celebrate christmas in war conditions, many of you wish you would be with 
your loved ones back home but we have a job to do. The sooner we neutralize the 
Russian occupation in Nogova, the sooner we can get home to those friends and family. 
Todays operation is against intersection east of our main target which is town of 
Mokropsy. And... Merry Christmas for all forces in the region.
<br/><br/>

INTEL<br/>
The intersection is heavily defended with anti armor forces, the Russian armor is
located in Mokropsy with additional infantry defenses and they are dug deep. No 
enemy helos active today in the area. Merry Xmas from intel.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Dolina. Proceed and clear out
all defenses around the <marker name = 'target1'>intersection</marker> so our tanks can 
pass through it. When it is neutralized, assault with the tanks 
into <marker name = 'target2'>Mokropsy</marker> town and capture it. Merry X-mas and
good luck!
<br/><br/>

TACTICAL<br/>
Ho Ho Ho! Santas Bags are full of grenades and 5.56mm NATO rifle cartridges, those
russian commies have been very very naughty. Santa will kick their butts back to 
Moscow, HO HO HO! Your mistletov is now match for my TOW missile!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Mokropsy"];
objective2 setSimpleTaskDescription ["Capture Mokropsy", "Capture Mokropsy", "Capture Mokropsy"];
objective1 = player createSimpleTask ["Clear intersection"];
objective1 setSimpleTaskDescription ["Clear intersection", "Clear intersection", "Clear intersection"];
