//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time for Beach!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Dourdan and proceeds 
to <marker name = 'target1'>sweep</marker> the beach.



Beach Sweep

GEN SITREP<br/>
La Trinite has extremely heavy defenses supported by anti aircraft weapons, we are not
ready to assault it yet. Until we move additional forces into the front line and try
to gather more intelligence its time to secure the sector.
<br/><br/>

INTEL<br/>
Only infantry is expected to be in the South East area of Dourdan all the way up to the
beach as there is no vehicle contacts at all. Enemy helos are operating in the area again.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Dourdan and your orders are to proceed
into the <marker name = 'target1'>beach</marker> and wipe out all enemy forces in the area. 
Good luck.
<br/><br/>

TACTICAL<br/>
Watch out for the enemy helos, it might be good idea to pickup some AA weapons from the ammo
boxes to cover your squad. Vulcans are not yet arrived into Dourdan area.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep the beach"];
_objective0 setSimpleTaskDescription ["Sweep the beach", "Sweep the beach", "Sweep the beach"];
