//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Holy smokes
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha starts at Durras and <marker name = 'target'>target</marker> is Vernon




Vernon Vampires

We are moving forward with this war, time to attack and capture village of Vernon. The 
Russians have been kept low profile in defensive positions so far and we like to keep it 
that way. We are now starting to push them into the ocean. These final battles are fought
on heavily populated area of the island and we do not want to have any civilian casualties
and that way get the sentiment against our war efforts here.
<br/><br/>

Intel has collected info for Vernon quite some time now, we pretty much can sum it up for
strong defenses. We are looking at three squads of infantry, three main battle tanks and
one BMP. They are dug in and also the worst part is that the road and area North from 
Vernon is mined.
<br/><br/>

Alpha starts from <marker name = 'start'>Durras</marker> and proceeds into Vernon which is our
 <marker name = 'target'>target</marker> for today. Teams supporting Alpha are 
 <marker name = 'bravo'>Bravo</marker> coming from East, <marker name = 'delta'>Delta</marker> 
 (anti armor) goes to the rear and <marker name = 'charlie'>Charlie</marker> Snipers are giving
supressive fire. Mission is accomplished when Vernon is freed from Russian occupancy. In 
this op you do not have air support as we do not want to obliterate Vernon, people do live
in there you know.
<br/><br/>

Finally we are pushing forward, Vernon is next to go. You're the lead element of this
assault, you're Alpha Black. Three other teams are supporting you which are Bravo who is
full squad and comes from the East in the mountains, Charlie is two man Sniper team who
are located NE from the target. Lastly we got anti armor team Delta Black which will go
from the west and try to sneak into the enemys rear to get some damage for the tanks. When
the mission commences all teams move into assault positions and report to you, when Bravo,
Charlie and Delta has reported in they will wait for your radio command (0-0-1) to start
the assault. The reason we dont have any armor support on this one is because the road and
landscape due north from Vernon is heavily mined and it would be suicide to send armor
through that. There is no other way to send armor in this valley. We do not want to send 
the gunships as people do live in Vernon.
<br/><br/>

<br/>











"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture Vernon"];
_objective0 setSimpleTaskDescription ["Capture Vernon", "Capture Vernon", "Capture Vernon"];
