//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




It was a long trip to Malden, usually I take a nap on the Black Hawk, but not today...
I am anxious, so much so that I cannot even nap.
<br/><br/>

Wonder what kind of guys are there waiting for me, they are newbies fresh out of boot camp.
So again its my resposibility to shepherd them and keep them alive... hmm alive... could I 
have something different back in the ammo boxes... could my team still be alive and this
would have never happened?
<br/><br/>
Damn, I must stop thinking these things, there is much time for that when the War is over.






"]];
player createDiaryRecord ["Diary", ["Mission", "
Meet your new team in the training ground.











"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Board black hawk to Kolgujev"];
objective2 setSimpleTaskDescription ["Board black hawk to Kolgujev", "Board black hawk to Kolgujev", "Board black hawk to Kolgujev"];
objective1 = player createSimpleTask ["Meet your team"];
objective1 setSimpleTaskDescription ["Meet your team", "Meet your team", "Meet your team"];
