//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to make a NATO stop sign on this intersection!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from La Riviere with objective 
to capture the <marker name = 'target'>intersection</marker> just North of the town.



<br/>Shepherd<br/><br/>

GEN SITREP<br/>
The enemy movement is heavy on the road just north of La Riviere, they are moving
vehicles and people in and out from the southern peak of Malden. We would like to 
stop this activity or at least make it more difficult as they need to move using
rural areas. The statrategic location is the intersection.
<br/><br/>

INTEL<br/>
There seem to be lower level of enemy air activity currently, no helicopter operations
expected in next hour. The target location has enemy road block secured by one BMP and
lot of infantry. No tanks currently present.
<br/><br/>

ORDERS<br/>
Alpha Squad <marker name = 'start'>start</marker> from La Riviere and proceeds on foot alone
into the north, clearing out any enemy opposition along the road into the target 
objective. At this time we don't want to send in tanks as the are is suspected to be mined. 
We must seize the <marker name = 'target'>intersection</marker> so we can control the 
roads. Your mission is to neutralize all enemies in the nearby area.
<br/><br/>

TACTICAL<br/>
So no enemy helos this time, one BMP and lot of infantry. Move slowly, check that you 
don't let the enemy flank you. Watch out the fast bmp - keep your LAW guy ready. Don't
get your squad killed over there!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Seize road intersection"];
objective1 setSimpleTaskDescription ["Seize road intersection", "Seize road intersection", "Seize road intersection"];
