//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Fried Spez Natz anyone? Todays choices are medium or extra chrispy... Haha!
<br/><br/>

So now we are making another attempt to take the castle, hopefully the situation wont 
require us to abort the mission this time.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Assault <marker name = 'castle'>Castle</marker> and capture it. Your backup is 
<marker name = 'echoins'>Echo</marker> who will <marker name = 'ambush'>ambush</marker> and cut any
reinforcements.
<br/><br/>

When castle is secured, radio the <marker name = 'convoy'>Convoy</marker> to start moving.
<br/><br/>

Good luck!

<br/>



<br/><br/>King of my Castle<br/><br/>

Our next objective is to capture enemys Commnd and Control site at the hilltop castle. 
If we manage to take this, it will be severe blow to the Russian communications and 
leadership.
<br/><br/>

Intel estimates that the castle is used as Command and Communications site for the
remaining Russian forces in the southern part of Everon. Our aerial reconnaisance have 
learned that there are lot of infantry and few heavy armored vehicles present in the 
area around in and around the buildings. Enemy has used this as CC site since we captured
the base earlier. We have reason to believe that high ranking officers are gathered in
the castle.
<br/><br/>

Alpha and Bravo <marker name = 'start'>start</marker> in the base, they board two Blackhawks
which fly to the <marker name = 'meet'>meet</marker> point where they wait for everybody to get
ready. When all forces are ready the code word KINGDOM is issued, that launches the 
operation. Blackhawks will drop Alpha and Bravo to 
the <marker name = 'castle'>Castle</marker> with parachute insertion. Echo squad will cover the 
road leading to the castle, they will <marker name = 'ambush'>ambush</marker> and cut any enemy 
reinforcements that might run up the road. After the castle is secured, Alpha radioes 
the <marker name = 'convoy'>Convoy</marker> to join them in the castle. Nobody is allowed to 
enter into the <marker name = 'noentry'>area</marker> surrounding Saint Pierre.
<br/><br/>


Our another try with this mission is to attack and capture 
the <marker name = 'castle'>castle</marker> high in the mountains. You will command the Alpha 
squad and are onboard the Blackhawk alongside with Bravo squad. Blackhawks fly to 
the <marker name = 'meet'>meet</marker> point where you wait for everybody to get into position.
Your backup team one is <marker name = 'echoins'>Echo</marker> who will first move into position
to <marker name = 'ambush'>ambush</marker> and cut off any possible enemy reinforcements coming 
from <marker name = 'noentry'>area</marker> of Saint Pierre. The operation commence code word is
(KINGDOM). After mission commences you are inserted with parachutes into the 
yard of the castle, which is very high risk situation. The terrain wont allow us to safely
insert the teams anywhere else, the terrain is extremely hazardous. Move fast when on the 
ground and dont get caught in the enemy fire. Watch out the guys in the castle tower and 
also the armored vehicles. The intel dont have enough information about the hillsides, but 
we have to assume there are more troops nearby and at least some patrols. When the castle
is secured and all enemies neutralized, you are to radio 
the <marker name = 'convoy'>Convoy</marker> (Foxtrot Black) to start moving. They will be your 
backup number two. Be careful out there, this is going to be another dangerous one.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture castle"];
objective1 setSimpleTaskDescription ["Capture castle", "Capture castle", "Capture castle"];
