//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Those spetz natz guys gives me the creeps.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase, sweep 
the <marker name = 'target1'>mountains #1</marker> 
and <marker name = 'target2'>mountain #2</marker> for any hiding russians.



<br/><br/>Mountain Relief<br/><br/>

GEN SITREP<br/>
Victory, finally Malden is freed from Russian forces. NATO command will congratulate
all the men and women of armed forces for this excellent performance. Very well done.
<br/><br/>

INTEL<br/>
Some scattered spez natz soldiers are expected to hide in the mountains, its uncertain if
they already escaped further to the woods or not. 
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from 
airbase, <marker name = 'insert'>insertion</marker> point is north of the mountain range
which you must clear out. sweep the <marker name = 'target1'>mountains #1</marker> and
also <marker name = 'target2'>mountain #2</marker> for any escaped Russians. When done
searching, radio call (0-0-1) for the <marker name = 'extract'>extract</marker> helo and
return to base. Good hunting.
<br/><br/>

TACTICAL<br/>
Some of the damned spetz natz soldiers and other possibly snipers has escaped from out
desert battlefield into the mountains and wood areas just south of the desert. Be careful
as these guys have nothing to lose here, they most likely are hiding and just waiting
to spray bullets in your direction when detected. Stay sharp!
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Return to base"];
objective3 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective2 = player createSimpleTask ["Clear mountain #2"];
objective2 setSimpleTaskDescription ["Clear mountain #2", "Clear mountain #2", "Clear mountain #2"];
objective1 = player createSimpleTask ["Clear mountains #1"];
objective1 setSimpleTaskDescription ["Clear mountains #1", "Clear mountains #1", "Clear mountains #1"];
