//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Action in marie






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Chapoi, proceeds into
village of <marker name = 'target'>Sainte Marie</marker> and captures it.



<br/>Sharp Star<br/><br/>

GEN SITREP<br/>
After we successfully took Chapoi we are immediately sending squad to assault
Sainte Marie.
<br/><br/>

INTEL<br/>
Sainte Marie contains only infantry and some BMP's. 
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>starts</marker> from Chapoi and proceeds to
the <marker name = 'target'>Sainte Marie</marker> clearing out the road all the way
up to the village. When the Sainte Marie is under our control, mission is accomplished.
<br/><br/>

TACTICAL<br/>
Nothing special in this one, don't proceed beyond the village itself as the woods can
contain some nasty stuff. Be careful when near the village as the engagement range
drops to almost knife fight ranges. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Sainte Marie"];
objective1 setSimpleTaskDescription ["Capture Sainte Marie", "Capture Sainte Marie", "Capture Sainte Marie"];
