//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




My and Bravo squad are descenting down this piece mountain, should be ok job.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road, clear out
all enemies from the <marker name = 'target1'>terrain 1</marker> and 
 <marker name = 'target2'>terrain 2</marker> south of you until you 
meet <marker name = 'charlie'>Charlie</marker> squad in ruins.



<br/>Clear Sabre<br/><br/>

GEN SITREP<br/>
Good news, today the weather starts to clear up. It will take some days before we are
in dry conditions again, but now we have seen the end of the thunderstorms in Kolgujev.
<br/><br/>

INTEL<br/>
Only infantry expected in that area.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from the road, there you are
to proceed into the <marker name = 'target1'>terrain 1</marker> and clear out any remaining
enemy forces <marker name = 'target2'>south</marker> of your starting position. Do this 
until you reach Charlies position in the ruins.
<br/><br/>

TACTICAL<br/>
You are now seeing the end of this goddamned rain, finally! This is what we have been
waiting for some time, excellent news. OK this mission is light one, descenting down
from the mountain with only infantry against you.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear area and reach Charlie"];
objective1 setSimpleTaskDescription ["Clear area and reach Charlie", "Clear area and reach Charlie", "Clear area and reach Charlie"];
