//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Hot damn that was fierce firefight we had in the Regina, some close calls indeed.
<br/><br/>

Anyways it seems that there is another mission cut out for me, sweep through the
hillside east from the city. Well there are some wooden areas and open grounds, dont
seem to be too difficult to handle, yet I gotta be careful, as always.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha starts from <marker name = 'start'>here</marker> and conducts a sweep operation
around the nearby area marked by dots. Do not across over the dotted area.





Sweet Sweep

When Regina was fallen into NATO hands, some Russians went hiding in the nearby 
area.
<br/><br/>

Intel reports that unknown number of enemy soldiers escaped from the NATO assault on
Regina, they are now hiding and trying to regroup in the nearby area east from the city.
There is no armor or vehicle movement detected.
<br/><br/>

Alpha squad is tasked to clear out any remaining enemy forces in east of Regina city. 
Alphas starting position <marker name = 'start'>here</marker> just SE of the city. Area assigned
for sweep is marked with dots, you are not autohorized to across this dotted area.
<br/><br/>

You are tasked to sweep the area, you are moving by foot this time as there are no vehicles 
detected by the intel people so you should be able to handle everything that you meet out 
there. The area of sweep is marked by dots, do not across the line.
<br/><br/>














"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep the area"];
_objective0 setSimpleTaskDescription ["Sweep the area", "Sweep the area", "Sweep the area"];
