//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




All right, lets give the Russians a warm NATO welcome.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Davle. Protect the
area and the bridge at all costs.



Party Night

GEN SITREP<br/>
Russians have launched counter attack to the bridge. Our forces will defend it at all
costs, we cannot lose this important piece of realestate in strategic location in Nogova.
<br/><br/>

INTEL<br/>
Now the Nogova airbase is red hot. They are launching more or less everything
they got over there, hinds... SU-25's. The ground forces are closing in 
directly from the west along the road.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Devle just west end of the
bridge. Russian counter <marker name = 'attack'>attack</marker> is coming from west 
along the road. Hold them off, do not let any Russians to get into the bridge. When you
have repelled the enemy assault and feel that area can be declared safe, use radio call
(0-0-1) to end the mission. Good luck.
<br/><br/>

TACTICAL<br/>
Okay so now they are pissed again. Take good defensive positions so your team is
covered, there is some ammo boxes brought here so use them as you please. Also
try to bring down as many enemy helos as possible.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Defend bridge"];
_objective0 setSimpleTaskDescription ["Defend bridge", "Defend bridge", "Defend bridge"];
