//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Those two house objectives should be easy task, but neveklov will be a one major.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Davle. Assault
the two farmouses <marker name = 'target1'>houses #1</marker> and 
the <marker name = 'target2'>houses #2</marker> to clear them from any Russians. 
Finally capture <marker name = 'target3'>Neveklov</marker> city.



Distant Glow

GEN SITREP<br/>
Russians lost massive amount of hardware and personnel in the last nights attack,
it was really a good victory for NATO. Today we advance further into enemy
territory, we must neutralize two remote farm houses on our way to Neveklov city.
<br/><br/>

INTEL<br/>
Only thing we know about the farmhouses is that there is no vehicles present, 
city of Neveklov does however have strong defenses, both infantry and armor. Seems 
like last night Russians lost most of their helicopters and aren't capable of 
launching sorties anytime soon.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Davle. Assault the two farmhouses
located <marker name = 'target1'>houses #1</marker> and <marker name = 'target2'>houses #2</marker>.
When done, assault and capture the <marker name = 'target3'>Neveklov</marker> city along
the road. Mission is accomplished when NATO reinforcements have arrived. Good luck.
<br/><br/>

TACTICAL<br/>
Ok the farmhouses are no biggie, the Neveklov is. Try to pick out the enemies from far,
keep your men alive and don't take stupid risks. Remember to keep the city secure until
the NATO reinforcements arrive.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective3 = player createSimpleTask ["Wait for reinforcements"];
_objective3 setSimpleTaskDescription ["Wait for reinforcements", "Wait for reinforcements", "Wait for reinforcements"];
_objective2 = player createSimpleTask ["Capture Neveklov"];
_objective2 setSimpleTaskDescription ["Capture Neveklov", "Capture Neveklov", "Capture Neveklov"];
_objective1 = player createSimpleTask ["Capture farmhouse #2"];
_objective1 setSimpleTaskDescription ["Capture farmhouse #2", "Capture farmhouse #2", "Capture farmhouse #2"];
_objective0 = player createSimpleTask ["Capture farmhouse #1"];
_objective0 setSimpleTaskDescription ["Capture farmhouse #1", "Capture farmhouse #1", "Capture farmhouse #1"];
