//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Another ammo blow up. Yeah I got to play with satches again, cool.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> front of the captured base.
Proceed into east and search for enemy <marker name = 'target1'>ammo cache</marker> 
 and destroy it.



Ammo Denial

GEN SITREP<br/>
Now we are in control of the northern most areas of the island, including the 
two bases in the mountain ridge. This is extremely good situation to start
push deeper and deeper into enemy territory.
<br/><br/>

INTEL<br/>
Enemy had ammo cache just south east from the base, apparently they had expected
our assault. There are several ammo boxes. Only infantry, no vehicles can drive
in that area. Helicopters seem to be inactive, only minor movement detected 
further in west Kolgujev.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> in front of the captured base. Move
into the eastern forest edge and find the <marker name = 'target1'>ammo cache</marker> 
 enemy has left there. When you find it, destroy it with any means you see fit. 
Return to base after accomplishing your mission.
<br/><br/>

TACTICAL<br/>
This is another easy one. Find the ammo boxes and destroy them. Stay alert for any
remaining enemies in the forests.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Find and destroy ammo cache"];
_objective0 setSimpleTaskDescription ["Find and destroy ammo cache", "Find and destroy ammo cache", "Find and destroy ammo cache"];
