//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Its getting dark fast and Russian attack is under way, oh geesh.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from St. Sedlo, defend it
against Russian counter <marker name = 'attack'>attack</marker> coming from north.



<br/>Bear Trap<br/><br/>

GEN SITREP<br/>
NATO has now basic defensive positions on the south east tip of Nogova, more troops
are ferried in as we speak. The enemy activity is believed to be counter attack, so
our forces must go into defensive positions and repel any such attacks. By tomorrow
we are hopefully strong enough to advance towards north.
<br/><br/>

INTEL<br/>
There has been hectic Russian radio traffic going on in the eastern part of the island,
we believe its going to be counter attack against the beach and St. Sedlo. Helicopters
are reported being active in the airfield, its unknown whether those are coming east.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from St. Sedlo, you are to defend it at
any cost against the enemy counter <marker name = 'attack'>attack</marker> coming from north. 
Bravo squad is holding your eastern flank in the <marker name = 'bravo'>beach</marker> where 
more troops are landing throughout the night. Your mission is accomplished when the 
objective is secure and no Russians are attacking agains it. There are abrams tanks 
defending the St. Sedlo with you.
<br/><br/>

TACTICAL<br/>
Lot of commie activity, this can mean nasy counter attack in the darkness. You have your
night vision goggles so use them if it gets too dark. Ammo boxes are brough in the town
so you should not run out of ammo either. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend St. Sedlo"];
objective1 setSimpleTaskDescription ["Defend St. Sedlo", "Defend St. Sedlo", "Defend St. Sedlo"];
