/*
Okay so this is oddball mission briefing... origninal mission goes that apparently player only sees
objective 1 at mission start and only once he talks to colonel he activates objective 2.
*/


//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Long flight back to the Kolgujev... back to the War...<br/><br/>Here I come Ivan... hope you bastard are ready for me... God have mercy, because I sure hell don't!"]];

player createDiaryRecord ["Diary", ["Mission", "Alpha team <marker name = 'start'>start</marker> get inserted to the docks. Proceed into the <marker name = 'hq'>NATO HQ</marker> to get new orders.<br/><br/>Welcome back."]];

// tasks need to be in reversed order
// objective2 moved into orders.sqs file
objective1 = player createSimpleTask ["Get new orders from Colonel"];
objective1 setSimpleTaskDescription ["Get new orders from Colonel", "Get new orders from Colonel", "Get new orders from Colonel"];
