//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Long flight back to the Kolgujev... back to the War...
<br/><br/>
Here I come Ivan... hope you bastard are ready for me... God have mercy, 
because I sure hell don't!






"]];
player createDiaryRecord ["Diary", ["Mission", "

Alpha team <marker name = 'start'>start</marker> get inserted to the docks.
Proceed into the <marker name = 'hq'>NATO HQ</marker> to get new orders.
<br/><br/>
Welcome back.



<br/>Fire Flash<br/><br/>

GEN SITREP<br/>
We like to welcome back ALPHA BLACK ONE. He was one of the prisoners of war who
got rescued by the Special Operations Forces working on coordination with air force.
Our war effort have progressed more deeper into enemy territory in these few past days,
the enemy area and front line is marked on the map with RED color.
<br/><br/>

INTEL<br/>
Today we do not expect any enemy activity in the air, no helos are detected since we
shot few of them down yesterday. Enemy armor is at halt and infantry is dug in. There
can be some minor movement but nothing larger is on the scope.
<br/><br/>

ORDERS<br/>
You are here now at the <marker name = 'hq'>NATO HQ</marker> in the ruins. Take 
your new Alpha Black squad to the <marker name = 'start'>Black Hawk</marker> which will 
transport you to a <marker name = 'insert'>insertion</marker> point at the mountain ridge.
From there proceed west and <marker name = 'target1'>meet Bravo</marker> squad. When you met
them, relieve Bravo from defensive positions and take over the front line defenses.
Do not I repeat DO NOT across over into enemy territoy. 
<br/><br/>

TACTICAL<br/>
Goddamnit guy! I'm so happy to see you again you old dog! You got us worried for a while
back there after the Operation Ammo Denial. It was some time before we got track of you,
if you want I can tell the Rescue Story of what we did.
<br/><br/>







<! RESCUE OPERATION TEXT! >

<a name="MyRescueStory">Rescue Operation

What happened<br/>
yeah what happened was when you disappeared after the Ammo Denial operation, there was 
just bodies of rest of your team but you were gone. We immediately got the word out to our 
Special Forces that one of our soldiers is missing, now you do not need to be told twice of our
policy: Leave No Man Behind. The spec ops guys were on this like a eagle on poor rabbit...
<br/><br/>

It was the second day when our deep recon team spotted you guys on the high security 
camp in the north west corner of Kolgujev. Immediately we started to put together a 
plan to get you out.
<br/><br/>

The plan was simple; first NAVY F/A-18 planes dropped 2000lbs laser guided bombs to the
T-80 tanks that were guarding the facility, the house which the Russians used for 
interrogating you guys (your statements) was bombed also. This had considerable risk,
we had the special operations forces operatives in direct contact with the NAVY planes 
to make absolutely sure that the POW's arent being in the target building at the time
of the strike started. I personally was listening to the radio comms they guys had, it
was serious business but it was pretty funny as believe me or not the NAVY fighter pilots
asked confirmation for the LGB drop for THREE CONSECUTIVE times from the people in the 
ground. That much caution they had that they will not drop ordnance to our own people. 
Somehow that was so professional that it was... freaking cool, you know.
<br/><br/>

Now that the bombs were dropped, the single ship A-10 fly fast low level along the coast 
line and struck the remaining T-80's that survived the LGB strike. The A-10 came from 
only few seconds later than the last bombs was released. 
<br/><br/>

When the first A-10 pass was complete, two army AH-64 Apache gunships came in with 
additional firepower to slap on those tanks. They also used rockets and cannons for 
any remaining Russian infantry or soft vehicles present.

<br/><br/>
About 30-45 seconds after the gunships arrived, the UH-60 Black Hawk utility choppers
came in low which both had the Special Operations Forces who are trained to rescue 
personnel in high risk situations. 
<br/><br/>

We are very happy that we got you out unharmed.
<br/><br/>

Back to War Situation










"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Read new orders "];
objective2 setSimpleTaskDescription ["Read new orders ", "Read new orders ", "Read new orders "];
objective1 = player createSimpleTask ["Get new orders from Colonel"];
objective1 setSimpleTaskDescription ["Get new orders from Colonel", "Get new orders from Colonel", "Get new orders from Colonel"];
