//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



My first battle as commander... that was fun, it was fun because I am still
breathing. I might actually make it as squad leader, who knows.
<br/><br/>

So now what... we are staying overnight in Tyrone, soon we will see
if the Ivan sends he's troops to pay us a visit. Well let me tell you something, we have
lot of NATO 5.56's to waiting for them! 

<br/>





"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Guard the city of <marker name = 'tyrone'>tyrone</marker>.



Night watch

The success we had with Tyrone was as expected from our highly trained troops. We are in 
the planning stage to advance deeper into enemy territory, assaults start in the daylight
tomorrow.
<br/><br/>

We have some indication of infantry movement near the front lines (Tyrone/Meaux), all 
forces should stay sharp tonight and be prepared for small attack(s) from the enemy. There
is no armored vehicles detected.
<br/><br/>

You have been tasked to hold the <marker name = 'tyrone'>tyrone</marker> overnight. Some 
additional equipment has been delivered to you in the truck. There are friendly forces 
due north-west in city of Meaux. If you get into trouble in the night, remember where 
the friendlies are so you don't kill our own guys. And Sargent, please make sure Tyrone 
is still under NATO command in the morning.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Guard the Tyrone"];
_objective0 setSimpleTaskDescription ["Guard the Tyrone", "Guard the Tyrone", "Guard the Tyrone"];
