//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Holy smokes, it was one fight with the Russians again. I'm getting good at this!
<br/><br/>
We are sitting in this freaking Gas Station waiting reinforcements coming to take this 
over. Dunno what they want us to do after that. At least there are tanks coming to refuel.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Your team is securing the Gas Station <marker name = 'start'>here</marker>,
wait for reinforcements. They will give new orders to your team. 



Refueling tanks

We are in the preparations for assault on city of Meaux. We still need to get last 
remaining forces together.
<br/><br/>

Intel is at work.
<br/><br/>

You are to hold the <marker name = 'start'>Gas Station</marker> until reinforcements arrive to
relieve you. They will give you further orders, be prepared to follow them out.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Assault and Capture Meaux Intel"];
_objective1 setSimpleTaskDescription ["Assault and Capture Meaux Intel", "Assault and Capture Meaux Intel", "Assault and Capture Meaux Intel"];
_objective0 = player createSimpleTask ["Follow orders"];
_objective0 setSimpleTaskDescription ["Follow orders", "Follow orders", "Follow orders"];
