//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Holy smokes, it was one fight with the Russians again. I'm getting good at this!
<br/><br/>
We are sitting in this freaking Gas Station waiting reinforcements coming to take this 
over. Dunno what they want us to do after that. At least there are tanks coming to refuel.
<br/>
"]];

player createDiaryRecord ["Diary", ["Mission", "Your team is securing the Gas Station <marker name = 'start'>here</marker>,
wait for reinforcements. They will give new orders to your team. 
<br/><br/>
Refueling tanks
<br/><br/>
We are in the preparations for assault on city of Meaux. We still need to get last 
remaining forces together.
<br/><br/>

Intel is at work.
<br/><br/>

You are to hold the <marker name = 'start'>Gas Station</marker> until reinforcements arrive to
relieve you. They will give you further orders, be prepared to follow them out."]];

// tasks need to be in reversed order
// objective2 moved into objective2.sqf file
objective1 = player createSimpleTask ["Follow orders"];
objective1 setSimpleTaskDescription ["Follow orders", "Follow orders", "Follow orders"];
