//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Ghost bat in this south west corner of Malden...






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from La Riviere, proceeds
into the <marker name = 'target2'>south west</marker> area of Malden 
clearing out all Russians.
<br/><br/>
Good luck!




<br/><br/>Ghost Bat<br/><br/>

GEN SITREP<br/>
The south west corner of this map is coming under our attack today. If we capture 
this area, we can bring in some helicopters to operate safely from the southern parts
of Malden.
<br/><br/>

INTEL<br/>
There is lot of infantry and some armored vehicles in the SW corner. 
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at La Riviere, proceed into south west
of malden and clear out any Russians present. There are three sectors you must make
sure is cleared, they are:<br/>
<marker name = 'target1'>Sector #1</marker><br/>
<marker name = 'target2'>Sector #2</marker><br/>
<marker name = 'target3'>Sector #3</marker><br/>
After the whole SW area is cleared, your mission is accomplished.
<br/><br/>

TACTICAL<br/>
Be careful, you have lot of ground to cover. Take the truck and use it as your field
base sort of. There is extra LAW and AA launchers for you to use, plus the normal ammo.
Be careful when you enter deep into enemy territory, keep your men alive!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear out SW of Malden"];
objective1 setSimpleTaskDescription ["Clear out SW of Malden", "Clear out SW of Malden", "Clear out SW of Malden"];
