//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Road capturing is boring I tell ya. I feel like traffic cop here.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from woods, proceeds into 
the <marker name = 'hill'>Hill</marker> and then to
the <marker name = 'target'>Road</marker> capturing it.



<br/><br/>Proud Forge<br/><br/>

GEN SITREP<br/>
Our final preparation before the attack to Chapoi. Were off to capture the
hill North West of Cancon and road located due north of the hill. This way
we can control the in and out traffic of the target city.
<br/><br/>

INTEL<br/>
Infantry and some vehicles are detected, also activity in the enemy airbase. 
Stay alert for enemy air support on next few hours.
<br/><br/>

ORDERS<br/>
Bravo <marker name = 'start'>starts</marker> from the woods, proceeds and takes 
the <marker name = 'hill'>Hill</marker> in NW. From the hill proceed 
and capture the piece of <marker name = 'target'>Road</marker> west from Chapoi.
<br/><br/>

TACTICAL<br/>
We have another enemy helo support on this one, so stay low and let the Vulcans 
handle them. When you proceed to the hill, make sure you clear it out completely
as there might be single soldiers lurking around. When the hill is secure, radio
in and call the reinforcements. Wait for the reinf squad and then proceed to 
capture the <marker name = 'target'>Road</marker> north of the hill.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture road"];
objective2 setSimpleTaskDescription ["Capture road", "Capture road", "Capture road"];
objective1 = player createSimpleTask ["Clear the hill"];
objective1 setSimpleTaskDescription ["Clear the hill", "Clear the hill", "Clear the hill"];
