//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




James... that was his name, James...
<br/><br/>

What could I have done to stop the russians to kill him, what? There I was standing 
right next to him when they shot him in cold blood. I will not ever forget that
as long as I live, thats much is certain. Sure I've seen lot of deaths in my time,
I've done my own share of killing... but this, this was something else.
<br/><br/>

James is gone. Was it my fault? Could I have done something? Was I selfish not to
jump in and take the bullet to save the kid? What if I've told the commies about
NATO plans? Will God ever forgive me the death of James?
<br/><br/>

Will today be my turn, I feel that the next interrogation that comes, its going to be
my turn to bite the dust. Is this the end of my military career, to die in this barren
Kolgujev Russian prison camp... will my family even know what happened to me. What about
my NATO friends, do they know where I am... have they already sended letter to my family
explaining me being KIA? Oh Lord...






"]];
player createDiaryRecord ["Diary", ["Mission", "











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Follow orders or die"];
objective1 setSimpleTaskDescription ["Follow orders or die", "Follow orders or die", "Follow orders or die"];
