//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




We are taking this island from the Russians!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from the beach and proceeds to
clear <marker name = 'target1'>Base</marker> and <marker name = 'target2'>camp</marker>



Cosmopolitan Warrior

GEN SITREP<br/>
Now its time to take this small island with good base grounds. Once we have set up this 
place, we can rest assure that no russian attack will threaten our precious equipment, 
which is a threat when they are located on the same land mass.
<br/><br/>

INTEL<br/>
The enemy island contains Anti Aircraft cover, so we cannot use helicopters. There are
some armored vehicles patrolling and heavy defenses set up for the base and the camp.
No enemy air activity detected in the Malden airbase.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the beach, as covertly inserted
by a boat. From that point you must proceed and capture the large 
enemy <marker name = 'target1'>base</marker> and after that HQ sends another squad to cover
the captured base. Then you are to proceed 
into <marker name = 'target2'>camp</marker> in the north east corner of this small island
and seize that enemy encampment also.
<br/><br/>

TACTICAL<br/>
The enemies should have no alert of your presence when you hit the beach. So you have
the advantage. There should be no enemy helos in the area so you're safe from aerial
attacks, however be alert for enemy armor as they can gun you down fast. After you have
captured the base, wait until your backup team arrives. Then you are free to proceed into
the second objective.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture camp"];
_objective1 setSimpleTaskDescription ["Capture camp", "Capture camp", "Capture camp"];
_objective0 = player createSimpleTask ["Capture base"];
_objective0 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
