//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



We have no intel on the enemy airbase. The assault for this island starts
by capturing the airbase, so we need to go in and check it out.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Welcome to the Everon soldier!<br/><br/>

This is Recon mission for Everon airbase.<br/>
Insertion point <marker name = 'insertion'>here</marker><br/>
Recon #1 <marker name = 'recon'>here</marker><br/>
Recon #2 <marker name = 'recon2'>here</marker><br/>
Extraction <marker name = 'extraction'>here</marker>



<br/>Recon<br/><br/>

Welcome to the war.<br/><br/>

Our mission is to remove all elements of Russian forces from Everon. We start this
operation by capturing the airbase located in the north of the island so we can conduct
air operations more easily than from our far offshore bases.<br/><br/>

There is no intel for the airbase at the moment, NATO HQ is re-tasking our satellites as
we speak, but it takes too long to get them to correct orbit. We are sending one man to
conduct Recon on the airbase, we hope it to be totally covert so the Russians have zero
warning of our upcoming invasion.<br/><br/>

You start on the water with scuba gear <marker name = 'insertion'>here</marker>, make your way 
UNDETECTED into near the airbases northern part <marker name = 'recon'>here</marker>.
After you have collected intel, you are to be proceed into southern part 
located <marker name = 'recon2'>here</marker>.<br/>
Recon it and get into extraction site located <marker name = 'extraction'>here</marker>. Do 
not shoot anybody, just collect intel.

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Extract undetected"];
objective3 setSimpleTaskDescription ["Extract undetected", "Extract undetected", "Extract undetected"];
objective2 = player createSimpleTask ["Recon the airbase south"];
objective2 setSimpleTaskDescription ["Recon the airbase south", "Recon the airbase south", "Recon the airbase south"];
objective1 = player createSimpleTask ["Recon the airbase north"];
objective1 setSimpleTaskDescription ["Recon the airbase north", "Recon the airbase north", "Recon the airbase north"];
