//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Attack to Chapoi!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Charlie team <marker name = 'start'>start</marker> from Cancon where they proceed
to <marker name = 'target'>Chapoi</marker> and capture it.
<br/><br/>

Good luck!



<br/><br/>Rolling Promise<br/><br/>

GEN SITREP<br/>
Our time to attack city of Chapoi has arrived. Now we launch combined armor and 
infantry assault to capture this objective. Good luck everyone.
<br/><br/>

INTEL<br/>
Chapoi is defended by lot of infantry and some armored vehicles. Anti Air threat
is present in the city.
<br/><br/>

ORDERS<br/>
You lead Charlie squad and <marker name = 'start'>start</marker> from Cancon. Other
Squads are <marker name = 'inf1'>bravo</marker> and <marker name = 'inf2'>alpha</marker> which
take part of this attack. Armor attack comes from <marker name = 'ustanks1'>tanks #1</marker> 
 and <marker name = 'ustanks2'>tanks #2</marker> positions.
<br/><br/>

TACTICAL<br/>
Be careful on this one, there is going to be heavy resistance. Keep low, take them down.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Chapoi"];
objective1 setSimpleTaskDescription ["Capture Chapoi", "Capture Chapoi", "Capture Chapoi"];
