//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Some mopping up to do today.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Loukov, proceed
into the <marker name = 'target1'>hilltop</marker> and clear it. 



<br/><br/>Vigilant Patrol<br/><br/>

GEN SITREP<br/>
Tomorrow we are launching operation against the valley where lot of enemy armor 
has been holding out. In the mean time we must mop up from area just south east 
of that location.
<br/><br/>

INTEL<br/>
In your are of operation there should be only infantry presence, however stay 
alert for any fast moving BMP's which might jump in from the valley.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Loukov, you are to proceed into
the <marker name = 'target1'>hilltop</marker> and clear it. When you are done, move
into <marker name = 'blata'>Blata</marker> to finish your patrol mission. Good luck.
<br/><br/>

TACTICAL<br/>
Just you and the enemy infantry, but keep alert for light armored vehicles none 
the less. You'll do just fine, tomorrow is a big day so take it easy.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Arrive to Blata"];
objective2 setSimpleTaskDescription ["Arrive to Blata", "Arrive to Blata", "Arrive to Blata"];
objective1 = player createSimpleTask ["Clear hilltop"];
objective1 setSimpleTaskDescription ["Clear hilltop", "Clear hilltop", "Clear hilltop"];
