//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Opatov hit time.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Joudov, capture 
the town of <marker name = 'target1'>Opatov</marker> and 
the <marker name = 'target2'>intersection</marker> in the beach.



<br/><br/>Silent Sparrow<br/><br/>

GEN SITREP<br/>
Our forces are steadily getting closer to the bridge, we fear that the
Russians might blow up the bridge before we get there or do some other
damage to it making it unusable. We must be careful with our actions
regarding this matter. Todays operation calls capturing the town of
Opatov and the intersection near it in the beach.
<br/><br/>

INTEL<br/>
Opatov has strong infantry defenses, armored vehicles have been spotted 
patrolling the area. Intersection is more lightly defended. No helicopters.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Joudov, capture the town 
of <marker name = 'target1'>Opatov</marker> and 
the <marker name = 'target2'>intersection</marker> in the beach. Today you have
AH-1 Cobra gunship support.
<br/><br/>

TACTICAL<br/>
Let the cobra knock out any vehicles thats present there, then move in. Watch
out for the intersection even the intel says its lightly defended.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture intersection"];
objective2 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
objective1 = player createSimpleTask ["Capture Opatov"];
objective1 setSimpleTaskDescription ["Capture Opatov", "Capture Opatov", "Capture Opatov"];
