//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Coordinated op with Bravo, cool.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from the field. Assault
city of <marker name = 'target1'>Modrava</marker> and capture it.



Private Property

GEN SITREP<br/>
City of Modrava is the largest city on north west Nogova, it holds key enemy
personnel as well as materials for their war machine. They are using it as
resupply base also as there is sea port possibilities. 
<br/><br/>

INTEL<br/>
There are heavy defenses in the objective and also tight net of AT teams in
Bludov. Some armored vehicles are present but no enemy helicopter activity.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the field. Bravo squad
will start from the <marker name = 'bravo1'>road</marker> and waits Alphas radio 
call (0-0-1) to assault <marker name = 'target2'>Bludov</marker> and then into Modrava. 
Alpha should assault <marker name = 'target1'>Modrava</marker> or they can join with 
Bravo and use two squad strenght attacking Bludov. Its up to Alpha. Mission is 
accomplished when Bludov and Modrava has been captured. Today you have CAS 
from AH-1 Cobra gunship who will start to engage when you order the assault. 
Good luck forces.
<br/><br/>

TACTICAL<br/>
Its decision time, will you join up with Bravo and assault from the north east
or will you go alone from north west, making the enemy sweat under two direction
attack. Hmm choices... well I know you're taking down this with ease.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture Modrava"];
_objective1 setSimpleTaskDescription ["Capture Modrava", "Capture Modrava", "Capture Modrava"];
_objective0 = player createSimpleTask ["Capture Bludov"];
_objective0 setSimpleTaskDescription ["Capture Bludov", "Capture Bludov", "Capture Bludov"];
