//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Beach preparation, Malden Invasion begins here.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha and Charlie <marker name = 'start'>start</marker> from the beach. Proceed
and clear the <marker name = 'target'>beach</marker> and keep it clear until
Vulcans arrive.
<br/><br/>

Good luck.



Maritime Thunder

GEN SITREP<br/>
Our diversion worked. Lot of enemy armor and presonell are being moved into the
La Passagne area to cover the incoming invasion. Now the southern part of the island
has reduced defenses. Our Malden Invasion commences as of now. We will penetrate the
enemy defenses and set up secure area for our forces to fully deploy into the beach.
<br/><br/>

INTEL<br/>
The bulk of the enemy armor is moved or moving into La Passagne area along with top 
line of the infantry. Southern area in the Cancon and La Riviere region is only 
lightly defended. When our forces strike the southern area, the russians are sure to
deploy infantry and armor into the region again. Expect helicopters and armored vehicles.
Enemy has strong AA defence in the island and any attempt of helicopter insertions would
certainly be extremely dangerous. 
<br/><br/>

ORDERS<br/>
Alpha and Charlie squads <marker name = 'start'>start</marker> from beach where they proceed and
clear the long strech of <marker name = 'target'>beach</marker> of any enemy troops. After the 
beach has been cleared, HQ sends in Vulcans so we can set up air defences on the beach.
When Vulcans have arrived, the mission is complete.
<br/><br/>

TACTICAL<br/>
We must take the beach quickly as time is not on our side, when you start to shoot 
over at the beach and when ruskies finally catch up, they sure will send reinforcements
to repel the invasion. Stay alert until the Vulcans arrive, do not let any russians to 
advance near them. Our final invasion requires that we can defend the beach agains Russian
aircrafts.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Secure it until Vulcans arrive"];
_objective1 setSimpleTaskDescription ["Secure it until Vulcans arrive", "Secure it until Vulcans arrive", "Secure it until Vulcans arrive"];
_objective0 = player createSimpleTask ["Clear the beach"];
_objective0 setSimpleTaskDescription ["Clear the beach", "Clear the beach", "Clear the beach"];
