//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The big seaport in south, Vidlakov. Soon the Russians will not have their
daily shipments of Vodka!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road. Clear out
the <marker name = 'target1'>houses</marker> in the field, then assault
and capture <marker name = 'target2'>Vidlakov</marker> city.
<br/><br/>
Good luck.



<br/><br/>Sharp Force<br/><br/>

GEN SITREP<br/>
NATO is doing great progress recently and we hope it will continue on today.
This operation is important one, we must capture the city of Vidlakov in
south beach of Nogova. Its big sea port so it will be devastating blow to the
Russians to lost that facility.
<br/><br/>

INTEL<br/>
We have now confirmed that most of the Russian helicopters are downed. Unless
they get urgent reinforcements, we should not see any helos anytime soon. The
main objective Vidlakov has strong defenses from infantry and armored vehicles.
The farmhouses has some Russian anti armor teams.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road. Clear out any and
all Anti Armor teams from the <marker name = 'target1'>farmhouses</marker> and then
use radio call (0-0-1) to initate the ground assault 
into <marker name = 'target2'>Vidlakov</marker> city which is our main target. Your 
support is M1A1 Abrams tanks and AH-64 Apache gunship. Good luck.
<br/><br/>

TACTICAL<br/>
Make sure the anti armor teams are knocked out before calling in the tanks as 
they would take severe damage of those pesky RPG's. Let the Apache soften up
Vidlakov before charging in.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Vidlakov"];
objective2 setSimpleTaskDescription ["Capture Vidlakov", "Capture Vidlakov", "Capture Vidlakov"];
objective1 = player createSimpleTask ["Clear out farmhouses"];
objective1 setSimpleTaskDescription ["Clear out farmhouses", "Clear out farmhouses", "Clear out farmhouses"];
