//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Hot damn those ungrateful civilian bastards, how DARE they try to assasinate the
good Colonel of ours!? All the russians we have driven from their lands, soon we 
expect to run last of them into ocean and then Malden is free again. What do we get
for return... makes me think what in the world I would risk my life defending these
low lifes... its so sad, people are so dumb.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from intersection, clear
out <marker name = 'target1'>hill top</marker> and 
then <marker name = 'target2'>capture</marker> buildings.



Garden Clover

GEN SITREP<br/>
Seems like not all the people in this island will appreciate what we are doing.
The assasination attempt to the Colonel was quite surprising, we must concentrate
more effort to the public relations in the future that we do not lose the public
support for our war we are fighting. In the topic of war, seems like Russians have
pretty much gone into defensive mode. We must push even harder now to keep up the
pressure.
<br/><br/>

INTEL<br/>
There are few vehicles patrolling the area ahead, infantry on defensive mode. No enemy
helicopters are in the air.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from intersection, first you must proceed
and clear the house just north east from the starting location. Then off to the first
objective of today, which is <marker name = 'target1'>hill top</marker> and the immediate area
near to it. When you have eliminated all enemy opposition from this area, proceed into
north west where you'll find the <marker name = 'target2'>buildings</marker> in end of the road.
Capture these buildings and your mission is accomplished.
<br/><br/>

TACTICAL<br/>
This should be another easy task for you, or perhaps I should send you back to baby 
sit someone? Hehe sorry just had to throw that joke in, man you did great job with 
protecting the Colonel. I just want to say that I have the upmost respect for you, 
you are one of the most honorable soldiers I've met in my live. Its an priviledge 
to server with you.<br/>
Anyways, like said this should be easy operation for you. Be alert for any surprises
and you'll do fine. Keep your LAW guys alive as there are some BMP's runnign around.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture buildings"];
_objective1 setSimpleTaskDescription ["Capture buildings", "Capture buildings", "Capture buildings"];
_objective0 = player createSimpleTask ["Clear hill top"];
_objective0 setSimpleTaskDescription ["Clear hill top", "Clear hill top", "Clear hill top"];
