//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Damn, counter attack!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> at Houdan. Repel the 
Russian counter <marker name = 'attack'>attack</marker> and defend Houdan at all costs!



<br/><br/>Bright Switch<br/><br/>

GEN SITREP<br/>
Russians are mounting a heavy counter attack to Houdan. We must repel it before we 
can continue our operations in this part of the island.
<br/><br/>

INTEL<br/>
Several infantry squads are spotted approaching, lot of armored contacts are also 
present and some helicopters are active on airbase.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> at Houdan and its tasked to defend it.
Another squad callsign <marker name = 'bravo'>Bravo</marker> is located due west of Houdan
near the buildings. You have support from Abrams tanks, one M113 and Apache Gunship.
Mission is accomplished when Russian counter attack is repelled.
<br/><br/>

TACTICAL<br/>
Stay low, stay alive. Let the Apache pound the upcoming Russians. There is 
also <marker name = 'ammo'>ammo</marker> boxes so use them how you see fit.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Repel counter attack."];
objective1 setSimpleTaskDescription ["Repel counter attack.", "Repel counter attack.", "Repel counter attack."];
