//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Uhm today we could face enemy helos again, those things just make me sick. It
takes too much firepower to bring one down and how much damage can these helos
do to a infantry squad in open area... oh no, I do not even want to imagine that.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from intersection, assault forward
until you reach the <marker name = 'target1'>objective</marker> point.
<br/><br/>
Good luck.



<br/>Red Rock<br/><br/>

GEN SITREP<br/>
We are not ready to take the base in the south, but we must take some ground
on the coastal road so when it is time to attack, its much closer in reach.
Our forces up in the north have experienced some harrasment from Russian during
the night, nothing large scale attack types just mosly poking around. We might
be expecting something in there, intel is working on it.
<br/><br/>

INTEL<br/>
The usual defensive positions along the coastal paved road, mostly ligther armor
and infantry. Enemy helicopters are active, but we just cannot tell if they will
be patrolling the road area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the intersection, attack through
the enemy positions until you reach this <marker name = 'target1'>objective</marker> near
the trees. Do not go further yet even if you would be able to. Intel estimates there
can be helo threat so we have vulcans standing by to back you up. Good luck.
<br/><br/>

TACTICAL<br/>
OK take it easy on this one, you know how deadly the enemy can be on the defensive
positions as seen on previous occations. Vulcans should handle the enemy air threat
if there is one.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Reach assault point"];
objective1 setSimpleTaskDescription ["Reach assault point", "Reach assault point", "Reach assault point"];
