//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Destroying wooden boxes... ok, all part of the war huh?






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from airbase. Search
the enemy <marker name = 'target1'>ammo cache</marker> in the woods.



Ammo Cache

GEN SITREP<br/>
Our war is progressing good and we are preparing to attack the desert in the
north. But another problem as popped up, the russians left some equipment behind
when we ran them out, now civilians are slowly discovering these. We must go and
destroy every piece of Russian hardware in this island, its not safe to leave them
behind.
<br/><br/>

INTEL<br/>
North West of Sainte Marie is friendly territory, no enemy forces expected there.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from airbase, you are tasked to search
and destroy the enemy <marker name = 'target1'>ammo cache</marker> located in the woods 
north west of Sainte Marie. You are <marker name = 'insert'>inserted</marker> in the field.
Do not leave any equipment intact, destroy them all. When done, use radio (0-0-1) to 
call helicopter extraction.
<br/><br/>

TACTICAL<br/>
Seems like you got moment to breathe here and do some demolition work. You have some
satchel charges with you, so use them to destroy the ammo cache.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Return to base"];
_objective1 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
_objective0 = player createSimpleTask ["Search and destroy ammo cache"];
_objective0 setSimpleTaskDescription ["Search and destroy ammo cache", "Search and destroy ammo cache", "Search and destroy ammo cache"];
