//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Russian bastards!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lipany. Get into
office, use radio (0-0-1) to initate assault, eliminate all Russians.



<br/>Protector<br/><br/>

GEN SITREP<br/>
We have hostage situation. Some leftover Russians had regrouped in the eastern
Nogova and put to together a plan to storm the Lipany office building. This was
a success since our forces werent that much protecting the city this far behind
friendly lines, obviously this was a mistake and all NATO occupied cities are
now beefing up their security. The Russians demand safe passage to the Nogova 
airbase and one million dollars or they will kill the hostages. They allowed one
unarmed NATO Officer to enter the building as good will gesture to check out the
hostages and negotiate the details. We must free the hostages and neutralize all
Russians in this building.
<br/><br/>

INTEL<br/>
There is unknown number of Russian leftover soldiers in Lipany office building.
We can see two in the roof, one in the mid floor balkony and one in the office 
at south west corner, all armed with AK-74 assault rifles. We do not know where
they are keeping the civilians.
<br/><br/>

ORDERS<br/>
Alpha squad leader is acting as the unarmed negotiatior. You'll be leaving your
good old COLT M16 Assault rifle behind and bring only Beretta 92FS 9mm hand gun
concealed with you into the building. Climb into the office floor and enter into
negotiations with the Russian leader. You'll have hidden radio transmitter in your
belt which you can activate unnoticed (radio 0-0-1), this is the assault order
to our snipers and special operations forces to storm the building. When you issue
the assault order, bring out your Beretta and take out any Russians your encounter.
Mission is accomplished when you neutralize all Russians from that building and 
hopefully bring out as many hostages alive as possible. Good luck.
<br/><br/>

TACTICAL<br/>
Ok this is a bad one. We were bit careless leaving leftover Russians lurking in the
woods and such (remember those lame wood clearup missions?) and now it bites us back.
Just pray that you get the hostages out alive, do NOT fire at them in the closed spaces
of that office building, take care with your aim! Good luck and be cool out there.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Eliminate hostage takers"];
objective1 setSimpleTaskDescription ["Eliminate hostage takers", "Eliminate hostage takers", "Eliminate hostage takers"];
