//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Desert is unforgiving... but so are we!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Ground forces <marker name = 'start'>start</marker> from fuel station. Assault
the <marker name = 'target1'>desert</marker> and wipe out all Russians.
<br/><br/>
Good luck everyone!



Desert Justice

GEN SITREP<br/>
Soldiers, airmen, sailors and marines. Today we launch the operation
desert justice, the final push to run the remaining Russians out of Malden.
Our objectives are very clear, our morale is high, today is the last day of
fighting in the Malden island, today the Russians will be defeated.
<br/><br/>

INTEL<br/>
Infantry, armored vehicles light and heavy are dug in the desert. Expect 
heavy resistance from the russians.
<br/><br/>

ORDERS<br/>
The ground elements that include Alpha and Bravo infantry squads, one full
platoon of M1A1 Abrams tanks will <marker name = 'start'>start</marker> from the
fuel station. Helicopter gunships and A-10 tank killers are spooling up as we 
speak. The mission launch codeword is VIPER and when you hear it, you
are free to engage enemy targets in the <marker name = 'target1'>desert</marker> wasteland.
Issue additional radio command for ground forces using (0-0-1) when the helos have
struck enough targets.
<br/><br/>

TACTICAL<br/>
Hooyah! today the russians are wasted! Final battle is here, the big desert is going
to be our playground. OK. let the gunships and A-10's do their job first, you stand no
chance against the T-80's alone. Keep your head low and be careful, but not too careful
as you must run the commies into the ocean! Good luck soldiers!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Neutralize enemies in desert"];
_objective0 setSimpleTaskDescription ["Neutralize enemies in desert", "Neutralize enemies in desert", "Neutralize enemies in desert"];
