//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Final assault has come... our move against the last Russians on this island. Last night
I got to think about this war, I've come a long way and it would be bitch to get killed
now. I must focus, I must use all my combat experience to keep alive on this one. no need
to be a hero, but heck if I'm going to be stay back while the other guys fight on this one.
<br/><br/>

My guys are looking confident, but yet quiet. Time to move out, time to move one last time
against the commies... time to take Everon back to the people of Everon.
<br/><br/>

Ok, lets go. 
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha <marker name = 'start'>starts</marker> from Vernon, assaults
<marker name = 'target'>Sait Pierre</marker> and captures it.

<br/><br/>



<br/><br/>Taste of Freedom<br/><br/>

We are in verge of pushing the Russians into ocean, the last stand, Saint Pierre. There are
no other enemy forces in this island, we have cleaned it out completely, these are the 
hard line forces dug in into the city area. They have no additional support, as they are
cut off and they must be low on ammo, they know we're coming, in any case this is the 
last stand one way or another. The native Everonians that were run out of Saint Pierre when
Russians went into rampage have given their so called permission for us to go in with full
force, meaning we are going to use heavy airstrikes to soften up the defenses.
<br/><br/>

Intel has some bad news. We are looking extremely tough armor defenses in the Saint Pierre.
There are several T-72 and T-80 tanks well dug in in the city, the infantry seem to be 
taking cover in the buildings at the moment. There are several squads of them left. There
are no AAA defenses detected like in any stage of this war. The region around the city
(mostly due East) is clear, all enemies are centered on about 200meters of the city.
<br/><br/>

Alpha <marker name = 'start'>starts</marker> from Vernon, 
Bravo starts due <marker name = 'bravo'>east</marker> of target and 
Charlie starts at the castle in <marker name = 'charlie'>west</marker> of the target. Apache
gunships will begin this operation with heavy air strikes and after they have softened up 
the targets, infantry moves in with tanks from <marker name = 'tanks1'>north</marker> 
and <marker name = 'tanks2'>south</marker> mopping up the infantry.
<br/><br/>

This is going to be rough ride. Target area is filled with dug in T72/T80's, lot of 
infantry in the buildings. The operation commences when Apaches unleash the hellfire from
above, you should wait for them to wipe out the heaviest armor (at least T80's), it would
be suicide to storm into the city immediately. When you believe its safe to move in, use
the radio (0-0-1) to commence the ground troops attack. you'll be leading the assault from
North along with Abrams tanks, from East comes bravo squad, charlie attacks from the castle
and another group of Abrams are moving in from South along the coast. This is it guys, our 
last assault on this island, last battle of this War. Fight to win, fight for Everon.
Hooyah Soldier!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Saint Pierre"];
objective1 setSimpleTaskDescription ["Capture Saint Pierre", "Capture Saint Pierre", "Capture Saint Pierre"];
