//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Our assault to La Trinite






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha, Bravo and Foxtrot teams <marker name = 'start'>start</marker> from Dourdan
and assault <marker name = 'target1'>La Trinite</marker> capturing it.
<br/><br/>
Good luck everyone.



Nomad Stick

GEN SITREP<br/>
The day of our assault to La Trinite is here. Today we execute combined arms attack
to town of La Trinite using infantry, tanks and helicopters to run the Russians out
of this objective. When we capture this we are one step closer to the victory.
<br/><br/>

INTEL<br/>
Lot of heavy armor, T72's and T80's are located in the objective. There is shilka AA
protection. Infantry is dug in and waiting for assault.
<br/><br/>

ORDERS<br/>
Alpha, Bravo and Foxtrot teams <marker name = 'start'>start</marker> from Dourdan. You as
Alpha squad leader will need to disable the shilka anti air vehicle before our helos
can move in to soften the town up. When the shilka is down helos come in. When the helos
have bombarded the town enough and you feel its safe to attack it, issue radio (0-0-1) 
command to order Bravo (infantry squad) and Foxtrot (M1A1 Abrams tanks) to 
assault <marker name = 'target1'>La Trinite</marker> town. Your mission is accomplished when 
no more Russians are occupying the objective.
<br/><br/>

TACTICAL<br/>
Uh this is going to be tough... there are at least two platoons of T-80's, T-72's, 
and lot of infantry waiting for us. First you must neutralize the shilka, its somewhere
near the city. Take it out and helos move in. Be absolutely certain that the heavy tanks
are knocked out before you order Bravo and Foxtrot to attack.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture La Trinite"];
_objective0 setSimpleTaskDescription ["Capture La Trinite", "Capture La Trinite", "Capture La Trinite"];
