//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Okay another long run for those mountains. Why don't we just nuke the damn rock!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> west from Houdan. Attack the
high <marker name = 'target1'>mountain</marker> and capture it.



<br/><br/>Mountain Warrior<br/><br/>

GEN SITREP<br/>
Russians had enough of fighting over Houdan, they aren't sending anymore troops.
Today we launch assault against the highest mountain of Malden, its steepness is
not suitable for shilkas but it definitely is Russian anti air site. When we have
captured this objective, the central Malden is ours and we can launch operations
to more north using our helos.
<br/><br/>

INTEL<br/>
Only infantry expected at the target area. The Spez Natz will mostly lurk around 
the mountains so we believe they are present in this mountain too. Enemy helicopters
are actively flying up north, its unknown whether those come down south today.
<br/><br/>

ORDERS<br/>
Alpha Squad <marker name = 'start'>start</marker> west from Houdan. Your orders are to
approach the high <marker name = 'target1'>mountain</marker> and capture it. Along the
way clear out all enemies between Houdan and objective. Do not wander too far to 
the north of south. Mission is accomplished when all Russians are neutralized from
the mountain and backup forces have arrived.
<br/><br/>

TACTICAL<br/>
This should be easy one, only infantry expected. Stay alert for Spez Natz teams as
these evil ones seem to enjoy the mountain life, its most likely that they are in
this mountain too. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Secure until backups arrive"];
objective2 setSimpleTaskDescription ["Secure until backups arrive", "Secure until backups arrive", "Secure until backups arrive"];
objective1 = player createSimpleTask ["Capture mountain"];
objective1 setSimpleTaskDescription ["Capture mountain", "Capture mountain", "Capture mountain"];
