//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Yesterday we scored few scud kills, hopefully we can find more today.

<br/><br/>Its kind of lonesome to be behind enemy lines without much support, 
its the men in my squad that are the lifeline and backbone of my operation, 
its essential to keep them alive so they can keep me alive...
<br/><br/>

I should scavenge some weapons from the dead Russians, its not a recommended 
to run out of ammo here when encountering some unexpected BMP's or infantry
squads. Of course my mission is to avoid any other enemy units except
the pesky Scud launchers.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from forest. Hunt 
down <marker name = 'target1'>scuds</marker> and 
reach <marker name = 'camp'>campign</marker> point.



<br/>Scud Hunt Day 2<br/><br/>

GEN SITREP<br/>
none
<br/><br/>

INTEL<br/>
none
<br/><br/>

ORDERS<br/>
Standing orders from yesterday. Hunt down <marker name = 'target1'>scuds</marker> and
reach <marker name = 'camp'>camping</marker> point.
<br/><br/>

TACTICAL<br/>
none
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Reach campign point"];
objective2 setSimpleTaskDescription ["Reach campign point", "Reach campign point", "Reach campign point"];
objective1 = player createSimpleTask ["Search and destroy scuds"];
objective1 setSimpleTaskDescription ["Search and destroy scuds", "Search and destroy scuds", "Search and destroy scuds"];
