//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Yesterday we scored few scud kills, hopefully we can find more today.

<br/><br/>Its kind of lonesome to be behind enemy lines without much support, 
its the men in my squad that are the lifeline and backbone of my operation, 
its essential to keep them alive so they can keep me alive...
<br/><br/>

I should scavenge some weapons from the dead Russians, its not a recommended 
to run out of ammo here when encountering some unexpected BMP's or infantry
squads. Of course my mission is to avoid any other enemy units except
the pesky Scud launchers.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from forest. Hunt 
down <marker name = 'target1'>scuds</marker> and 
reach <marker name = 'camp'>campign</marker> point.



Scud Hunt Day 2

GEN SITREP<br/>
none
<br/><br/>

INTEL<br/>
none
<br/><br/>

ORDERS<br/>
Standing orders from yesterday. Hunt down <marker name = 'target1'>scuds</marker> and
reach <marker name = 'camp'>camping</marker> point.
<br/><br/>

TACTICAL<br/>
none
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Reach campign point"];
_objective1 setSimpleTaskDescription ["Reach campign point", "Reach campign point", "Reach campign point"];
_objective0 = player createSimpleTask ["Search and destroy scuds"];
_objective0 setSimpleTaskDescription ["Search and destroy scuds", "Search and destroy scuds", "Search and destroy scuds"];
