//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




NATO heavy armor has rolled into the Nogova mainland soil. Yeah baby yeah!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from beach. Proceed and
capture <marker name = 'target1'>St. Sedlo</marker> and 
also <marker name = 'target2'>lighthouse</marker> in the cape
<br/><br/>
Welcome to Nogova, finally.



<br/>Final Invasion<br/><br/>

GEN SITREP<br/>
NATO invasion of Nogova has begun. Really this is the invasion, yes we have been
on the island for some time now but not with the tanks and other armored vehicles
before. Now when we assault something, it will be captured and occupied by frindly
forces for good. This is the first day of the Russian departure of Nogova. Now our
only goal is to run then out any way we can.
<br/><br/>

INTEL<br/>
The St. Sedlo is lightly defended, mostly infantry. Some armored vehicles are 
present in the north of the beach and your objectives. No enemy helicopters.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the beach. Assault and capture
the <marker name = 'start'>St. Sedlo</marker> and 
the <marker name = 'target2'>lighthouse</marker> in the cape. Our forces are landing on
the beach from the supply ships all day long. Your secondary objective is to keep 
and eye on the overall situation in the beach. Your mission is accomplished when
both captures are complete.
<br/><br/>

TACTICAL<br/>
Welcome to Nogova, for good. That sounds nice. Okay the St. Sedlo has some forces,
but we don't expect much resistance from the lighthouse. Be careful.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture lighthouse"];
objective2 setSimpleTaskDescription ["Capture lighthouse", "Capture lighthouse", "Capture lighthouse"];
objective1 = player createSimpleTask ["Capture St. Sedlo"];
objective1 setSimpleTaskDescription ["Capture St. Sedlo", "Capture St. Sedlo", "Capture St. Sedlo"];
