//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Yesterdays Scud hunt came up empty. Wonder if the Russians got alerted from the
first strikes and moved them into more deeper in south, dunno.
<br/><br/>
Well today we will continue more deeper into enemy territory in hunt for scuds, I'll
hope that we find some as even one scud launcher alive here to fire that damn thing 
into NATO forces would be too much to handle. Its up to me to stop these guys, I just
wish we will find rest of them...
<br/><br/>

Time to go, time to go hunting.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from forest, hunt down
the <marker name = 'target1'>scud</marker> launchers. When done proceed into
the <marker name = 'extract'>extraction LZ</marker> for helo extract.



Scud Hunt Day 3

GEN SITREP<br/>
none
<br/><br/>

INTEL<br/>
none
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the forest. Hunt down
enemy <marker name = 'target1'>scud</marker> launchers and destroy them. When you
are done, proceed into <marker name = 'extract'>extraction LZ</marker> and use 
radio call (0-0-1) to call for helicopter extraction.
<br/><br/>

TACTICAL<br/>
none
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Get to extraction LZ"];
_objective1 setSimpleTaskDescription ["Get to extraction LZ", "Get to extraction LZ", "Get to extraction LZ"];
_objective0 = player createSimpleTask ["Search and Destroy scuds"];
_objective0 setSimpleTaskDescription ["Search and Destroy scuds", "Search and Destroy scuds", "Search and Destroy scuds"];
