//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Assault to Saint Louis, enemies are going to RUN!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road, proceed and capture
the <marker name = 'target1'>Fuel Station</marker> and <marker name = 'target2'>Saint Louis</marker> city.



<br/><br/>Sins<br/><br/>

GEN SITREP<br/>
We are closing in on the enemy airbase and they are taking it safely. They have 
moved most of their heavy vehicles into the airbase area and more to the north.
We must get ready for the big fight for the airbase soon.
<br/><br/>

INTEL<br/>
Enemy has withdrawn somewhat to regroup in the airbase. No major armored vehicles are
in the area, small number of infantry. No helicopters are in the air currently.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> the road. Your orders are to capture
the <marker name = 'target1'>Fuel Depot</marker> along with <marker name = 'bravo'>Bravo</marker> squad
who will come from Larche. When fuel depot is captured, use radio (0-0-1) to call on attack to 
the <marker name = 'target2'>Saint Louis</marker> town. Your assault force will be friendly AT team 
whos attacking Saint Louis from the south and Bravo squad whos coming from west. Good luck.
<br/><br/><br/>

TACTICAL<br/>
Yeah seems the Russians are really taking it safe today, most of their T-80's and T-72's
have been moved to defend the airbase. You should expect mostly infantry and maybe
few vehicles. 
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Saint Louis"];
objective2 setSimpleTaskDescription ["Capture Saint Louis", "Capture Saint Louis", "Capture Saint Louis"];
objective1 = player createSimpleTask ["Capture fuel station"];
objective1 setSimpleTaskDescription ["Capture fuel station", "Capture fuel station", "Capture fuel station"];
