//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That was definitely a rush, jumping out of a helo like that. Luckily I still have my
legs and no other limbs are broken either.
<br/><br/>

Okay so we are jumping right into the Gravette, quite fast come to think of it.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Capture city of <marker name = 'gravette'>Gravette</marker>




<br/>The Gravette<br/><br/>

Gravette is the only populated area between the hospital and Montignac. Our near goals are
to take Gravette and the woods leading to the road coming from Montignac.
<br/><br/>

Intel believes there are small number of enemy soldiers remaining in the Gravette.
<br/><br/>

Your orders are to seize <marker name = 'gravette'>Gravette</marker> taking the opportunity as 
the Russian forces are taken by surprise with the hospital attack.

<br/><br/><br/>










"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Seize Gravette"];
objective1 setSimpleTaskDescription ["Seize Gravette", "Seize Gravette", "Seize Gravette"];
