//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




darn those ruskies!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and Bravo <marker name = 'start'>start</marker> from intersection, 
the <marker name = 'attack'>russian attack</marker> comes from north. Orders
are to defend this location at all costs. 
<br/><br/>

Godspeed son.



<br/>Garden Respose<br/><br/>

GEN SITREP<br/>
Our attack to the small island is on hold, Russians are launching a counter attack
on our newly captured positions. We must stop them before proceeding.
<br/><br/>

INTEL<br/>
There seems to be some infantry action and armored vehicles due North of our positions,
also activity from the airbase. Be ready for land and air attack.
<br/><br/>

ORDERS<br/>
Alpha and Bravo <marker name = 'start'>start</marker> from intersection which they must defend
at all costs. The <marker name = 'attack'>russian attack</marker> comes from north. Do not leave 
your positions undefended at any time. Mission is accomplished when all attacking Russians 
have been repelled.
<br/><br/>

TACTICAL<br/>
Okay heavy stuff coming our way. They most definitely spam some helicopters against us and
some heavy armor, not to mention the infantry too. There is ammo boxes brough there and some
small sandbags, use them as you please. Keep your head down, make every shot count, dont panic.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend intersection"];
objective1 setSimpleTaskDescription ["Defend intersection", "Defend intersection", "Defend intersection"];
