//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Heavy enemy defenses in the ruins, are going to be permanent part of the ruins 
when my squad has done with them! Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road, clear area
for <marker name = 'snipas1'>snipers</marker> and commence assault to 
the <marker name = 'target1'>ruins</marker> with radio call (0-0-2).
<br/><br/>
Good luck everyone.



<br/>Fire Fortress<br/><br/>

GEN SITREP<br/>
Today is a big day. Weather is improving a lot, weather team is not expecting
rain anymore today and they estimate that we have clear skies in few days. Today
we move against the last large ruins in Kolgujev occupied by Russians. We are
pretty close of running them out of the whole island.
<br/><br/>

INTEL<br/>
There are armor and heavy infantry defenses in and around the ruins.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road, proceed and clear
the area for <marker name = 'snipas1'>sniper</marker> team. When you have cleared
the area, issue radio command (0-0-1) to call them in. When the snipers are
in position issue radio command (0-0-2) to commence the assault. Assaulting
forces to the <marker name = 'target1'>objective</marker> today are as 
follows: <marker name = 'bravo'>Bravo</marker> squad in the road just south of 
target along with sniper team two. <marker name = 'charlie'>Charlie</marker> squad
is located in the road along with M1A1 Abrams tank platoon who are assigned to 
clearing out the road coming from north east. The mission is accomplished when
NATO is in control of the target ruins. 
<br/><br/>

TACTICAL<br/>
This is going to be tough fight, the Russians are set up good defenses so don't
take any stupid risks today. Keep it low, let the snipers take out most threatening
elements first, use cover... you know the usual stuff. I'll be expecting you in 
full mental and physical health lateron today! Don't let me down buddy.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture ruins"];
objective1 setSimpleTaskDescription ["Capture ruins", "Capture ruins", "Capture ruins"];
