//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Hot damn that was one hair raising rescue ops!
<br/><br/>

Okay so today we are tasked to attack Lamentin in the beach. We have lot of ground to be
covered after insertion, I gotta be careful out there as we penetrate so deep into enemy
territory.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


The teams start at the <marker name = 'start'>Airbase</marker> you'll get inserted into 
the <marker name = 'lz1'>LZ #1</marker>. Swept the <marker name = 'clear1'>area</marker> for 
enemies. Meet the other squad in <marker name = 'rendez'>here</marker><br/>
Radio HQ (0-0-1) to send paratroops and then attack 
Lamentin <marker name = 'attack'>here</marker>.




<br/><br/>Lamentin<br/><br/>

NATO Headquarters is very pleased with the superb performance of the rescue operation
yesterday. We are very happy to get our guys back home. We are moving along the coastline
down to south-west, towards Lamentin. Our objective is to capture the city.
<br/><br/>

Intel community gives warm thoughts for the superb action taken in the rescue ops of our
downed bird. We truly appreciate it. The recon team in the bird that was recorever is 
reporting that Lamentin has two full squads of infantry along with BMP's, but no other 
armor is present in the city. There is also some enemy activity in the beach north-east
from the city.
<br/><br/>

Your squad start on NATO HQ <marker name = 'start'>Airbase</marker> in UH-60 Blackhawk which 
will fly you to your LZ - <marker name = 'lz1'>LZ #1</marker>. Second squad from this assault 
will land at <marker name = 'lz2'>LZ #2</marker>. Your first objective is to clear out any enemy 
forces in the <marker name = 'clear1'>area</marker> between LZ #1 
and <marker name = 'rendez'>rendezvou</marker> point. When you feel the area is secure you are 
to proceed into <marker name = 'rendez'>here</marker> to rendezvou with Bravo squad. When you 
both teams are in place and ready to attack, radio HQ to send the paratroopers with 
Chinook to assault the city. Wait for them, dont make move yourself alone. When the 
paratroops are landing the Chinook will radio you directly to attack the city. Your final 
objective is to attack and secure the <marker name = 'attack'>Lamentin</marker>.

<br/><br/><br/>










"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Secure Lamentin"];
objective2 setSimpleTaskDescription ["Secure Lamentin", "Secure Lamentin", "Secure Lamentin"];
objective1 = player createSimpleTask ["Clear area"];
objective1 setSimpleTaskDescription ["Clear area", "Clear area", "Clear area"];
