//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Happy New Year!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from radar site. Observe
and stand as backup for <marker name = 'target1'>armored fight</marker> in 
lowland north west. Then assault and 
capture <marker name = 'target2'>Mokra Vrata</marker> town.
<br/><br/>
Happy New Year!



Nogova New Year

GEN SITREP<br/>
Happy New Year troops. Tonight we will show the Russians how we celebrate
new year around here. The armored contacts we've had in the north west tip
of the island are going to be attacked from the air in cover of the night
as well as by tanks on the ground with infantry support.
<br/><br/>

INTEL<br/>
Lot of enemy armored contacts in the north west of your position. No enemy helos
present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the mountain top. Observe and
stand as backup support while the gunships from the 
air <marker name = 'target1'>attack</marker> the enemy tanks. When you feel safe enough for
M1A1 Abrams assault, use radio 0-0-1 to call them in from the east. Join the assault and 
capture <marker name = 'target2'>Mokra Vrata</marker> town. Happy New Year!
<br/><br/><br/>

TACTICAL<br/>
Hooyah! let the fireworks begin! Ok you should mostly stand back and enjoy the show,
but be prepared to support the tanks on the ground as the fight progresses. Dont 
assault the objective two before you feel its safe enough. Its not point getting killed
down there. Good luck and happy New Year!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture Mokra Vrata"];
_objective1 setSimpleTaskDescription ["Capture Mokra Vrata", "Capture Mokra Vrata", "Capture Mokra Vrata"];
_objective0 = player createSimpleTask ["Support tanks"];
_objective0 setSimpleTaskDescription ["Support tanks", "Support tanks", "Support tanks"];
