//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Russians attempt to counter attack us again.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, defend
them against Russian counter attack.



<br/>Red Afternoon<br/><br/>

GEN SITREP<br/>
Enemy counter attack is on way towards our positions. Keep them away as
we are not here to give up territory, we are to take it.
<br/><br/>

INTEL<br/>
Special operations forces behind enemy lines are reporting that the heavy armor 
is still in their original positions, expect mostly infantry in this attack.
<br/><br/>

ORDERS<br/>
Alpha <marker name = 'start'>start</marker> from northern ruins while 
the southern ruins is <marker name = 'bravo'>Bravo</marker> squads position. There
is <marker name = 'snipas'>sniper</marker> team supporting in the hilltop. Russian
counter <marker name = 'attack'>attack</marker> is coming from south west. you must
stop them.<br/><br/>

TACTICAL<br/>
There is medic team heading this way from the NATO hq, try to keep the area secure
for their arrival, you'll find some valuable ammo and medical supplies from that
truck. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Stop Russian counter attack."];
objective1 setSimpleTaskDescription ["Stop Russian counter attack.", "Stop Russian counter attack.", "Stop Russian counter attack."];
