//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Boy are we moving fast, yesterday we fight over the Lemantin, with success of course
and today we are moving like crazy into the Le Moule area.
<br/>
"]];
player createDiaryRecord ["Diary", ["Mission", "You start from <marker name = 'start'>here</marker><br/>
Attack and seize <marker name = 'capture'>Le Moule</marker>

<br/><br/>
Operation Muse
<br/><br/>

The operation to capture Lamentin was a success and now we are moving along towards the 
next objective which is Le Moule.
<br/><br/>

Intel has knowledge of two squads of enemy infantry and some vehicles in the city of 
Le Moule, there are also other vehicle (armored and unarmored) operating east from the city.
We are currently in the process of gathering more detailed info, we will let you know when
we have something new.
<br/><br/>

Your Alpha Black squad will start in the <marker name = 'start'>road</marker> west from Le 
Moule. Your mission is to assault and take city of <marker name = 'capture'>Le Moule</marker>. 
There are lot of other squads operating in the closeby, so watch you fire. 
<marker name = 'bravo'>Bravo</marker> squad is assaulting the city from the north. Other squads 
in the area are <marker name = 'charlie'>Charlie</marker> at far north 
and <marker name = 'delta'>Delta</marker> right behind your position. Charlie will sweep the 
hill near its position and the woods south-east from the hill. Delta squad will make sweep 
along the coast. This operation has also heavy air support. When Le Moule is captured, 
hold the city and wait for support truck that will be sent to rearm your troops.
"]];
// tasks need to be in reversed order
// objective2 moved into objective2.sqf file
objective1 = player createSimpleTask ["Capture Le Moule"];
objective1 setSimpleTaskDescription ["Capture Le Moule", "Capture Le Moule", "Capture Le Moule"];
