//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




First advance in Kolgujev, okay. lets go!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from NATO hq. Attack
and capture <marker name = 'target1'>house</marker> and the
small <marker name = 'target2'>base</marker> in the beach.



Essential Elements

GEN SITREP<br/>
Today we start to push down to the south west of Kolgujev. Our forces are
still ferrying into the island and we must make some room for them.
<br/><br/>

INTEL<br/>
We have some vehicles in the west of NATO hq, nothing heavy at the moment.
No enemy helicopters are detected yet.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from new NATO hq. You are to 
proceed into <marker name = 'target1'>house</marker> and capture it. From there
neutralize all enemies from <marker name = 'target2'>base</marker> at the beach.
<br/><br/>

TACTICAL<br/>
You have small room to breathe, the russian onslaught counter attack made some
cap in their strenghts so we have rather easy advance. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture base"];
_objective1 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
_objective0 = player createSimpleTask ["Capture buildings"];
_objective0 setSimpleTaskDescription ["Capture buildings", "Capture buildings", "Capture buildings"];
