//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



I like ambushing ivan, its good fun.
<br/><br/>

We are pushing very hard now. I must keep my focus, if not for me... for my men.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Clear out enemy positions in this sector, major areas are:<br/>
<marker name = 'clear1'>Clear area #1</marker><br/>
<marker name = 'clear2'>Clear area #2</marker><br/>
<marker name = 'clear3'>Clear area #3</marker><br/>
Sweep areas clear of enemy forces. Do not enter into the Saint Pierre surroundings.
<br/><br/>

Good luck commander.
<br/>



Killing Grounds

Our reinforcements to the airbase have been arrived finally, now we have good use of 
aircrafts again and our assaults continue. We did advance to the south side of Saint Pierre
and if we now move into north-east side too, the Russians are put on tight pressure and 
have only one escape point, into the ocean...
<br/><br/>

Intel have received the new birds finally, yet we didn't get them set up properly and this
operation is without any aerial reconnaisance. However we have been looking at the tangos 
in the frontlines and there is lot of activity. Lot of infantry dug in there and they got
machine gun positions build in just yesterday. There have been some indication of enemy 
armor but the types and numbers are unknown. Armor defences are to be expected. No sign of
enemy aircrafts in the region still keep the intel wondering why such strategy...
<br/><br/>

Alpha and Bravo squads <marker name = 'start'>start</marker> from the field base. They push 
through the Russians defences in the front line and sweep the area clear of enemy forces.
First objective is for Alpha to neutralize 
enemy <marker name = 'mgun'>Machine Gun</marker> position while Bravo waits in the front line.
<br/>
Clear <marker name = 'clear1'>area #1</marker><br/>
Clear <marker name = 'clear2'>area #2</marker><br/>
Clear <marker name = 'clear3'>area #3</marker><br/>
Use all means possible to wipe them out. Mission is accomplished when all Russians are 
either dead or fleeing from the frontline to the beach in south-east tip of the island.
When the enemies are wiped out, call the backup guys (radio 0-0-1) to set up camp in the 
beach around the <marker name = 'lz'>LZ</marker> point. Air support is available in this 
operation. Do not enter into enemy territory beyond the red dotted line 
near <marker name = 'noentry'>Saint Pierre</marker> at any situation.
<br/><br/>

You are command of full squad of Alpha Black in <marker name = 'start'>field hq</marker> and
Bravo squad is equipped the same way. Your orders are to clear out the area (three actually)
behind the front lines, after you have neutralized 
the <marker name = 'mgun'>Machine Gun</marker> position. The areas are marked on the map, they 
are not so specific but general points in the map, so you better to sweep the surrondings 
of those marks too. Its easy to say that you need to run out every Russian from the front 
line to the southern tip of the island. Borders in your area of operation is the front 
lines and the red dot marked area in south-west, its marked clearly where you cannot 
enter. We dont want you to go near Saint Pierre yet as when we go, we go with massive 
force. After your sweep and clear op is completed, use the radio (0-0-1) to call backup 
guys to setup camp in the just captured area, they will be inserted with Chinook to 
the <marker name = 'lz'>LZ</marker> so make sure its safe and secure for their arrival. 
Today we finally got the reinforcements to our air vehicles and we got Apache and Cobra 
gunships to support your assault.<br/>
Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Call backup forces"];
_objective1 setSimpleTaskDescription ["Call backup forces", "Call backup forces", "Call backup forces"];
_objective0 = player createSimpleTask ["Clear areas"];
_objective0 setSimpleTaskDescription ["Clear areas", "Clear areas", "Clear areas"];
