//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Special Operations forces, the cowboys of military. Things get serious when these guys
are on the scene. Things get really really bad when one of them gets wounded. Now its 
time to extract these guys from the hills in southern part of the island.<br/>
I kind of miss the real action and its only been few days for the cease fire to be in order.
Wonder if this war comes to a end... or do we have still some fighting to do.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Tonights operation is calling for med-evac extraction of spec ops. You are conducting
this totally covert mission with one medic. Remain undetected at all times. You are not 
cleared to engage enemies other than selfdefence.
<br/><br/>
You fly in with Blackhawk, land, find the spec ops, medical treat them, get back to LZ
and call the chopper (radio 0-0-1). Good luck.<br/><br/>

Spec Ops hideout <marker name = 'specops'>camp</marker> posit.<br/>
Helicopter <marker name = 'lz'>Landing Zone</marker> is safe.




<br/>Cease Fire in order<br/><br/>

The cease fire limits our ability to attack the Russians. We cannot conduct any offensive 
operations until the leaders decide how to proceed with this War. At this time we have no 
real intel for Russian intentions and the cease fire negotiations didn't give much info
on that matter either.<br/><br/>

Tactical sitrep:<br/>
There are some Special Forces operatives deep inside the enemy territory, we have kept them
there for intelligence gathering purposes only so far. Now we have new developments from
their status, seems that one of the operatives has gotten serious injuries. The wounded 
spec op has been stabilized by the other two operatives with him but they have radioed in 
that he cannot be moved without decent medic treatment. We do not know at this moment 
wheter this injury is caused by enemy fire or just plain accident, due the fact that it is
not wise to discuss matters on wide spectrum over the radio comms.
<br/><br/>

We do have precise location for the hideout that the guys are using. Its on the hillside
south-west from Saint Pierre, well hidden under a tree cover. Spec Ops hideout 
<marker name = 'specops'>camp</marker> position.
<br/><br/>

They have reported enemy activity all over the southern Everon, infantry, armor and other
lighter vehicles. They have not detected any enemy air activity or air equipment located 
anywhere in their area of operations. There are no enemy activity nearby the spec ops 
hideout present time and the helicopter <marker name = 'lz'>Landing Zone</marker> is declared 
safe to operate (intel note: report is 15 mins old).

<br/><br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Extract Spec Ops team"];
objective2 setSimpleTaskDescription ["Extract Spec Ops team", "Extract Spec Ops team", "Extract Spec Ops team"];
objective1 = player createSimpleTask ["Get medical team to Spec Ops"];
objective1 setSimpleTaskDescription ["Get medical team to Spec Ops", "Get medical team to Spec Ops", "Get medical team to Spec Ops"];
