//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Hooyah time to kick the russians into the sea! Yeeaah!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins. Assault the
Russian <marker name = 'target1'>stronghold</marker> and neutralize them all.
<br/><br/>
Good luck.



<br/>Weasels<br/><br/>

GEN SITREP<br/>
Weather is clear. Our objectives are clear. Ladies and Gentlemen, today NATO will
run out the Russians from Kolgujev. The day has come, we have been victorious and
today is no different. I want all of you, soldiers airmen and marines to put one
hundred percent effort for this last operation. Lets finish this with minimal 
casualties and lets finish this good. Tonight we celebrate the Kolgujev independency.
<br/><br/>

INTEL<br/>
The remaining enemy armor is trying to get ferry out of the island, but we do not have
anything on the NAVY's radar systems. Seems like they are stuck for here at least so
long that we can deal with them. There are number of enemy tanks and lighter vehicles
along with the heavy and desperate infantry holding up. Last enemy helicopters were 
destroyed in the ruins.
<br/><br/>

ORDERS<br/>
Alpha and bravo squads <marker name = 'start'>start</marker> in ruins along with Charlie 
M1A1 Abrams tank platoon. Infantry first clears the enemy gate at the fuel station and 
then tanks move in. Its infantrys job to clear out any anti armor teams that might be 
waiting for our tanks, so alpha and bravo, stay sharp. When the fuel depot is cleared 
you are to proceed into the center of enemy <marker name = 'target1'>stronghold</marker> and 
neutralize all found Russians there. Mission is accomplished when no Russians are 
standing in the western tip of Kolgujev.
<br/><br/>

TACTICAL<br/>
Final battle, huh... this is it boys and girls. Time to put our best effort into the
play. Be very careful with the ridge passing into the main stronghold, most of them
will get immediate ling of sight for you at once. Thats lot of fire...
<br/>












"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Neutralize all Russians"];
objective1 setSimpleTaskDescription ["Neutralize all Russians", "Neutralize all Russians", "Neutralize all Russians"];
