//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Push along the road, advancement as you will... and I do.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, assault through
the enemy <marker name = 'target1'>positions</marker> and seize 
the <marker name = 'target2'>intersection</marker> which they are holding.



Bronze Breakfast

GEN SITREP<br/>
This morning we start to push towards west on the paved road near the highest
mountain in Kolgujev, our main objective is the next intersection. If this
succeeds, its another great advancement in our war effort. Soon we will have
the mountain surrounded and we can clear it out from any enemies.
<br/><br/>

INTEL<br/>
The road is heavily defended especially in the volcano flow point, infantry and
armor is dug in along the path. Enemy helos are active far more north west areas.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road at the intersection.
Assault along the road until you reach the 
enemy <marker name = 'target1'>positions</marker> which you must clear out. Then assault
the main objective which is <marker name = 'target2'>intersection</marker> that enemy
has set up a basic check point.
<br/><br/>

TACTICAL<br/>
There are lot of wooden areas surrounding this road, along with short engagement 
distances on some places. Be careful, don't let the enemy flank you. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Seize intersection"];
_objective1 setSimpleTaskDescription ["Seize intersection", "Seize intersection", "Seize intersection"];
_objective0 = player createSimpleTask ["Clear positions"];
_objective0 setSimpleTaskDescription ["Clear positions", "Clear positions", "Clear positions"];
