//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



We finally got Montignac! It feels good now that we have captured something really large
from the enemy, the troops seem to appreciate this fact and yes, its truly a good morale
boost.
<br/><br/>

So now we are into another boring area clearup. We need to comb the region north-east from 
Entre Deux woods and hills for any leftover Russians, sigh... I want to be in the front 
lines pushing the commies away from this island!
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Clear out <marker name = 'clear'>area</marker> and <marker name = 'chapel'>Chapel</marker>




<br/><br/>Cleanups<br/><br/>

After we seized Montignac, we want to make sure there are no leftover Russian 
forces hiding in the North-East from Montignac. We are building up the defensive positions
to Montignac for repel any and all possible counter attacks by Russians.
<br/><br/>

Intel has been too busy gathering intelligence behind enemy lines that we have no 
additional information about the region north-east of Entre Deux. However its clear that
there are no vehicles - we would have picked up those from the air already.
<br/><br/>

Your orders are to search and destroy all remaining russians in 
this <marker name = 'clear'>area</marker> Also make sure there are nobody in 
the <marker name = 'chapel'>Chapel</marker> or nearby.

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear the designated area"];
objective1 setSimpleTaskDescription ["Clear the designated area", "Clear the designated area", "Clear the designated area"];
