//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I must sneak closer to the fuel depot and when to call the assault strike the
target along with the snipers, Bravo will assault soon after along with the tanks. Yeah!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and bravo teams <marker name = 'start'>start</marker> from base, attack
enemy <marker name = 'target1'>fuel depot</marker> and <marker name = 'target2'>ruins #1</marker>
 and <marker name = 'target3'>ruins #2</marker> capturing them.
<br/><br/>
Good luck.



<br/><br/>Ghost Hope<br/><br/>

GEN SITREP<br/>
Today we launch operation against the enemy fuel depot and two ruins just south 
west of our last captured objective (the base). If we are successful we have the
control over the whole south and east coast of Kolgujev. The enemies are then ran
into tight spot as they run out of bases very quickly. We are expecting their 
resistance to get stronger as they run into more desperate times.
<br/><br/>

INTEL<br/>
There are no helicopters active in the south, the three targets consist of normal
infantry defenses backed up with light and heavy armored vehicles.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from the base. Charlie tank
platoon is positioned in the <marker name = 'ustanks'>road</marker> south east of the base.
Sniper team is positioned in the <marker name = 'snipas'>hill</marker> overlooking SW area.
Our operation objectives are three folded, first is 
the <marker name = 'target1'>fuel depot</marker> directly west of our base. Next is the
small <marker name = 'target2'>ruins #1</marker> west of fuel depot. Last objective is 
the larger <marker name = 'target3'>ruins #2</marker> in the beach. Alpha squad gives the
assault command by radio (0-0-1) and then bravo and charlie move against the fuel depot,
Charlie stays there but bravo proceeds into ruins #1 before engaging the last ruins #2
objective.
<br/><br/>

TACTICAL<br/>
This is three target operation. You should have pretty good coverage by the snipers
who will commence fire when you radio the assault, but don't make them fight the fight
alone.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture ruins #2"];
objective3 setSimpleTaskDescription ["Capture ruins #2", "Capture ruins #2", "Capture ruins #2"];
objective2 = player createSimpleTask ["Capture ruins #1"];
objective2 setSimpleTaskDescription ["Capture ruins #1", "Capture ruins #1", "Capture ruins #1"];
objective1 = player createSimpleTask ["Capture fuel depot"];
objective1 setSimpleTaskDescription ["Capture fuel depot", "Capture fuel depot", "Capture fuel depot"];
