//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Vampires, yeah we were vampires allright. sucking the blood out of Russian positions!
<br/><br/>

Another night watch for me. these really takes a bite. but hey someone's gotta do it.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha starts at <marker name = 'start'>Vernon</marker> guarding it for possible 
Russian counterattack.




<br/><br/>Open Arms<br/><br/>

Tonight we are assmbling the forces for full scale attack to the last stronghold of the
enemy, Saint Pierre. We have additional infantry and special forces coming in from other
parts of the island. There will be hard decisions made tonight about air support for the
assault, Saint Pierre is beautiful old city where people live and it definitely won't be
that way if we send in Gunships and Warthogs.
<br/><br/>

Intels best estimate is that the Russians cannot affort to launch counterattack at this
point of time. You should be aware that there are some small squads ready to commence 
some sort of counter attacks, but its highly unlikely. Russian armor is very well dug in
and you will definitely not see them tonight at Vernon area. But tomorrow when our large
final assault comes, we are looking for very very tough fight.
<br/><br/>

Alpha starts from <marker name = 'start'>Vernon</marker> and the orders are to remain in the
village limits and keep it under NATO control. We do not expect any Russian visitors 
tonight, but stay alert. Mines are cleared out and <marker name = 'tanks'>tanks</marker> are 
rolling in tonight. Do not in any circumstances enter into enemy 
territory <marker name = 'noentry1'>south</marker> of Vernon.
<br/><br/>

We have interesting night in ahead of us, Russians have driven out of Vernon but intel guys
are saying they aren't capable of any significant counter attack. However when was the intel
100% correct, so stay sharp. We have Abrams tanks coming in from Durras as the engineers 
finally cleared the mines north of Vernon.
<br/><br/>

<br/>











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Guard Vernon"];
objective1 setSimpleTaskDescription ["Guard Vernon", "Guard Vernon", "Guard Vernon"];
