//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The terrain of Kolgujev, is going to be cleaned out from any Reds.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, sweep 
the <marker name = 'target1'>area</marker> south west of ruins, 
meet <marker name = 'bravo'>Bravo</marker> squad in the base.



<br/>Distant Promise<br/><br/>

GEN SITREP<br/>
Weather keeps improving as the predictions are clear skies by tonight. We captured
and ran out of the Russians in the ruins with success like it was expected. War
is progressing fine, it should not take many days to run the remaining Russians from
western corner into the ocean.
<br/><br/>

INTEL<br/>
There is little or no information about the area south west of the ruins. We have
concentrated our intel ops into the last piece of Russian real estate in Kolgujev,
the western tip. We should have new intel by tomorrow morning at the latest.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the ruins, proceed through the
terrain in south west and <marker name = 'target1'>sweep</marker> all enemies you 
encounter in that area. Do not proceed into the western tip which is the enemy
stronghold. Meet <marker name = 'bravo'>Bravo</marker> squad in the base to accomplish
your sweep mission.
<br/><br/>

TACTICAL<br/>
Heya, now its sweep time again. You should be familiar this already, make sure
there are no surprises in the area between our two positions, the ruins and the
base where Bravo is waiting for you to arrive. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Sweep the area, meet Bravo"];
objective1 setSimpleTaskDescription ["Sweep the area, meet Bravo", "Sweep the area, meet Bravo", "Sweep the area, meet Bravo"];
