//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to take on with the Russian infantry again. But hey, thats what I do best. 
Time to go.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Larche, mission
objectives are:<br/>
clear <marker name = 'target1'>intersection</marker><br/>
clear <marker name = 'target2'>mountain</marker><br/>
capture possible <marker name = 'target3'>landing zone</marker><
<br/><br/>
Good luck.



<br/>Silent Walker<br/><br/>

GEN SITREP<br/>
Larche defenses are setting up, but no time to sit around. We move forward deeper 
into the enemy territory today. Objectives are key places north, north west from Larche.
If we manage to get that LZ operational it will give us excellent drop off point for
our troops near the front line.
<br/><br/>

INTEL<br/>
Infantry and vehicles are moving in the north west side of Larche. No signs of enemy 
helicopter activity this morning.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Larche, you are to clear out the 
first <marker name = 'target1'>intersection</marker> in the west between the hills. Secondly
you are to take the <marker name = 'target2'>mountain</marker> which we can use as site for
vulcans. Last objective is <marker name = 'target3'>landing zone</marker> or whats to become
landing zone after we seize that large open area. Mission is accomplished when all these
objectives are under NATO control. Good luck.
<br/><br/>

TACTICAL<br/>
I suggest using caution when going up that first road, smells like good place to set up 
ambush or at least throw couple of snipers in the hillside. Make sure the area selected
for landing zone is cleared completely, we do not want to have our choppers flying 
directly into enemy lap.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture and prep LZ"];
objective3 setSimpleTaskDescription ["Capture and prep LZ", "Capture and prep LZ", "Capture and prep LZ"];
objective2 = player createSimpleTask ["Clear mountain"];
objective2 setSimpleTaskDescription ["Clear mountain", "Clear mountain", "Clear mountain"];
objective1 = player createSimpleTask ["Clear intersection"];
objective1 setSimpleTaskDescription ["Clear intersection", "Clear intersection", "Clear intersection"];
