//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




my notes!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from the intersection. Assault
and capture the enemy <marker name = 'target1'>base</marker> in the mountain ridge.
<br/><br/>
Good luck.



Infinite Response

GEN SITREP<br/>
The feared weather front is just one day away from the Kolgujev coast now, we will
be expecting heavy rain and thunderstorms all across this island. It will severe 
our operations as the visibility will drop and it makes harder to spot enemies.
<br/><br/>

INTEL<br/>
Basic infantry defense and some vehicles are in the enemy base. No air activity detected.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base with the M2A2 sherman,
you will clear path to the tank along the blue dots. Your backup 
is <marker name = 'bravo'>bravo</marker> squad who will attack from the NW and takes position
on the <marker name = 'bravo2'>intersection</marker> just west of the base. When you reach
the base gates, M2A2 will knock them down and then you must neutralize all enemy forces
in the <marker name = 'target1'>base</marker> itself.
<br/><br/>

TACTICAL<br/>
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture enemy base"];
_objective0 setSimpleTaskDescription ["Capture enemy base", "Capture enemy base", "Capture enemy base"];
