//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Another fast assault to the enemy held villages. At least last time we did not
encounter too much armor defenses which made it rather easy. Hope the same luck
is with us this time too.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airstrip, assault
the <marker name = 'target1'>Blata</marker> village in the hill.



<br/><br/>Safari Heat<br/><br/>

GEN SITREP<br/>
More Russian armor have been reported to be deployed in the Nogova island, they are
putting heavy defenses at the nearby area of the airbase. The troops all over the 
island are getting more and more alert of our presence and setting up their own
local defense positions. Today we conduct another fast assault into the Russian held
villages, this is called Blata and its located center of the eastern landpiece of Nogova.
<br/><br/>

INTEL<br/>
We are estimating that there is light infantry and perhaps one or two softer vehicles
present in Blata. The troops are getting more alert, but we do not believe they are
expecting an attack to be imminent. No helicopters contacts on radar.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the airstrip, you will get normal
Black Hawk <marker name = 'insert'>insertion</marker> north west of your objective which
is the <marker name = 'target1'>Blata</marker> village in the hill top. Strike it fast
and when you have done enough damage, escape 
into <marker name = 'extract'>extract LZ</marker> where Black Hawk will come to pick you up
after you've issued radio call (0-0-1) to him. Good luck.
<br/><br/>

TACTICAL<br/>
This time be more careful, the intel don't think the Russians are expecting us to 
attack Blata, but they are more alert. This is enough for concern. Keep your LAW
soldiers ready for any vehicles like BMP's.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Assault Blata"];
objective1 setSimpleTaskDescription ["Assault Blata", "Assault Blata", "Assault Blata"];
