//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Those wood cleanup ops are pain in the ass. I hate to be running around in the woods.
Ah well, no woods today. We got ourselves a Gas station raid, looks harmless... I just
got to be careful and not to blow up the whole station by stray fire.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Your squad starts from the <marker name = 'start'>base</marker> backed up with 
a <marker name = 'sniper'>sniper</marker> team. Proceeds to 
the <marker name = 'gas'>Gas Station</marker> and secure it.
<br/><br/>

Good luck.



<br/><br/>Gasoline<br/><br/>

The gas station due south from the base is next strategic location in our campaign 
against the Russians. If we capture it, we can give some high value fuel to our 
vehicles in the area, it will speed up the attacks seriously.
<br/><br/>

Our Recon squad has noticed that there are Fuel truck and some smaller vehicle parked
in the gas station, also infantry movement has been detected. Still no armor or air 
activity anywhere in the front line.
<br/><br/>

Our objectives in this operation is to secure the gas station.<br/>
Charlie squad (your team) and Sniper team starts from the <marker name = 'start'>base</marker><br/>
Sniper team will position themselfs <marker name = 'sniper'>here</marker> while Charlie 
continues to the <marker name = 'gas'>Gas Station</marker> clearing out any enemy troops located
there.

<br/><br/><br/>










< ---THE FOLLOWING IS THE TEXT FOR THE SECOND SECTION ON THE OBJECTIVE LIST>
"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Secure the Gas Station"];
objective1 setSimpleTaskDescription ["Secure the Gas Station", "Secure the Gas Station", "Secure the Gas Station"];
