//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Once again we visit the old friend, Russian prison camp/arty site. Its the third time 
I'm visiting this site. Its getting cosy around here hehe.
<br/><br/>

Its cool to have some support forces for this one, but I need to position my anti armor
guys very carefully to inflict maximum damage to the enemy at once. I have satchel charges
and mines to use for the road to get the first kill. All in all this looks pretty good.
<br/><br/>

After we have nuked the convoy, its time to head back into the extraction site and get back
home. I should be careful as there is no way of telling what loose infantry the Russians 
have in the area, we got to remember that even if our forces are very close we are still
going to operate behind enemy lines...
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Reinforcement ambush
<br/><br/>

Alpha, Bravo and Charlie starts <marker name = 'LZ'>LZ/Extract</marker> location.<br/>
<marker name = 'bravo'>Bravo</marker> team takes support position<br/>
<marker name = 'charlie'>Charlie</marker> team takes support position
<br/><br/>

Clear out village and set up <marker name = 'ambush'>ambush</marker> to stop enemy 
<marker name = 'convoy'>convoy</marker> approaching from south.

Get back to camp for extraction (use radio).
<br/><br/>





Ambush at Durras

We continue to push to the south aggressively. Russians are on defensive.
<br/><br/>

Intel have intercepted enemy radio traffic which indicates that they are sending few 
armored vehicles and infantry on trucks to the front lines with intentions to fortify
the defences. The convoy of reinforcements contains one heavy tank, bmp and trucks.
The convoy starts from Saint Pierre and runs the road up north into the front lines.
Durras is most certainly occupied by enemy forces.
<br/><br/>

This mission calls for quick insertion and clearing of enemy village, setting up an ambush
to kill enemy convoy. Your teams get inserted into the prison camp/arty <marker name = 'LZ'>site</marker> 
 from where you are to proceed into Durras where you set up the <marker name = 'ambush'>ambush</marker> 
 for the convoy. Bravo and Charlie teams will be positioned for fire support while Alpha 
clears the <marker name = 'ambush'>village</marker> and sets up the ambush. 
Bravo <marker name = 'bravo'>posit</marker> and Charlie <marker name = 'charlie'>posit</marker> are
east from the village.
<br/><br/>

There are mines and satchels in the ammo boxes at the LZ/Extract site, enemy has not get 
them out of there, so we are going to use them. Be sharp with the enemy forces in the 
Durras when you enter the vicinity, they most likely dont know you're coming from the east 
so you have the advantage. Take them out quickly and make sure there are nobody left 
hiding. Place mines or satches in the road so you can kill the enemy armor. Then pull back 
to safe distance with your anti armor guys. Wait until the convoy gets into the Durras and 
let them have it. Your mission objectives are met when the convoy is destroyed. Then head 
back to the camp for extraction, use radio 0-0-1 to order the support teams to return there also.
To call the Blackhawk for extraction use radio 0-0-2 call when at the camp.

<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Extract back home"];
_objective1 setSimpleTaskDescription ["Extract back home", "Extract back home", "Extract back home"];
_objective0 = player createSimpleTask ["Kill the convoy"];
_objective0 setSimpleTaskDescription ["Kill the convoy", "Kill the convoy", "Kill the convoy"];
