//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Hmm I must get close to that hill undetected, so I better keep my mens fingers off the 
triggers until we are in striking distance...

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Cancon and proceeds to
neutralize enemy <marker name = 'aasite'>AA Site</marker> just south east from La Riviere.




Noble Force

GEN SITREP<br/>
Overnight we took the first populated objective, Cancon. Next we must neutralize some 
of the nearest anti aircraft sites in this region if we ever want to have our 
helicopters operating in Malden. 
<br/><br/>

INTEL<br/>
There is AA Site in the hill south east from La Riviere. There is at least one Shilka 
present and some infantry movement has been detected. La Riviere is heavily defended
but its unlikely that they can spare any large reinforcements for the AA site.
<br/><br/>

ORDERS<br/>
Alpha Black <marker name = 'start'>start</marker> from Cancon and proceeds west towards the
enemy<br/><marker name = 'aasite'>AA Site</marker> in the hill. After the site is neutralized 
Alpha will secure the hill and keep any russian reinforcements away from it.
<br/><br/>

TACTICAL<br/>
Neutralize the shilka, be alert for any infantry AA soldiers present as they must also be
taken out to eliminate the AA threat that site poses to our choppers. Take good defensive
positions after you've taken the hill as Russians may launch some counter attacks from 
La Riviere. We don't believe there is much they can spare, but prepare for anything.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Defend the hill"];
_objective1 setSimpleTaskDescription ["Defend the hill", "Defend the hill", "Defend the hill"];
_objective0 = player createSimpleTask ["Neutralize AA Site"];
_objective0 setSimpleTaskDescription ["Neutralize AA Site", "Neutralize AA Site", "Neutralize AA Site"];
