//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That tank busting was a close call I tell you. Its nice to get some more relax
work after that. Time to put this boat house, dock, whatever, out of business.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, assault
and capture <marker name = 'target1'>boat house</marker> the enemy is
using to resupply.



Boat House

GEN SITREP<br/>
We are moving armor and personel to the tank base in the process to speed up
our war efforts. Intel seems to believe that there will be large scale Russian
counter attack soon, we will keep close eye on the enemy.
<br/><br/>

INTEL<br/>
The depot resupplying the enemy boats is overall lightly defended, only 
infantry and light vehicles in the area at the moment. No enemy helicopters 
are present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at the road near the old AA site,
you are to proceed and capture <marker name = 'target1'>boat house</marker> in the 
beach. Good luck.
<br/><br/>

TACTICAL<br/>
This should be pretty easy as there is no armor and air vehicles to bother you.
Stay alert, as usual.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture boat house"];
_objective0 setSimpleTaskDescription ["Capture boat house", "Capture boat house", "Capture boat house"];
