//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Some sneaking around to place satchel charges!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the cliff. Proceed to 
the <marker name = 'target'>Fuel Truck</marker> place some satchels under it
and detonate when you're far away. Return to the boat for extraction.




<br/>Smoke and Mirrors<br/><br/>

GEN SITREP<br/>
We are preparing for Malden Invasion. This operation begins with fooling the Russians 
to think we are attacking from the West coast near La Passagne by setting demolition
charges in the beach area. When they explode hopefully the russians think we are 
bombarding the beach as we prepare to invade it. We have other plans for invasion...
<br/><br/>

INTEL<br/>
There should not be much guard activity on the La Passagne area since the Russians aren't 
expecting us to pay a visit. Some guards have been detected though.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from below the cliffs in the ocean, the 
insertion is with a boat which waits there until Alpha is done with the mission. Alpha
proceeds into the <marker name = 'target'>Fuel Truck</marker> and places satchel charges nearby.
Then the team departs the area and detonates the explosives when some distance has been taken.
Alpha boards the boat and leaves the area.
<br/><br/>

TACTICAL<br/>
Be careful with the guards over there, try to avoid engaging them if possible.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Destroy Fuel Truck"];
objective1 setSimpleTaskDescription ["Destroy Fuel Truck", "Destroy Fuel Truck", "Destroy Fuel Truck"];
