//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Le Port must go!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha and Bravo teams <marker name = 'start'>start</marker> from intersection near
front lines. They proceed and seize <marker name = 'target1'>intersection</marker> and
also <marker name = 'target2'>sea port</marker> from where they finally assault
the <marker name = 'target3'>Le Port</marker> town.
<br/><br/>
Good luck!



Eternal Phoenix

GEN SITREP<br/>
One more push and we control south part of Malden. Today we move on the South East
side which has one of the most important ports of this island. When we have control
over this region, we can assault the small island East of Le Port. But first Le Port
must go.
<br/><br/>

INTEL<br/>
There are infantry and armor present. The airspace is clear at the moment, but there
are several helos standing by on Malden airport. Its unknown how fast they can get them
to the area when hostilities commence. Stay alert.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from intersection, the first
objective is the road <marker name = 'target1'>intersection</marker> which is our cut off
point for any enemy reinforcements. When road is cut off, we will send you M1A1 Abrams 
support to hold the intersection, wait for them. Second objective is 
the <marker name = 'target2'>sea port</marker> what enemy is using to resupply their Southern
forces. Third and final objective is <marker name = 'target3'>Le Port</marker> town which is key
location in enemy operations in southern sector. When all these three objectives are under
NATO control, your mission is accomplished. Be adviced we have two Vulcans standing by in case
of any enemy air activity.
<br/><br/>

TACTICAL<br/>
You and bravo squads take on foot, watch out for enemy armor as they move awfully fast. Make
sure there is no enemies left wandering around who might struck you in the back when you're
not expecting it. Unknown status on enemy air operations, keep and eye on the sky. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective2 = player createSimpleTask ["Capture Le Port"];
_objective2 setSimpleTaskDescription ["Capture Le Port", "Capture Le Port", "Capture Le Port"];
_objective1 = player createSimpleTask ["Capture sea port"];
_objective1 setSimpleTaskDescription ["Capture sea port", "Capture sea port", "Capture sea port"];
_objective0 = player createSimpleTask ["Cut off the road"];
_objective0 setSimpleTaskDescription ["Cut off the road", "Cut off the road", "Cut off the road"];
