//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Russians are really trying to kick our boys around with he helos.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from tank base, you must
defend against Russian attack.
<br/><br/>
Good luck.



<br/><br/>Long Sword<br/><br/>

GEN SITREP<br/>
Russians have got their air operations fully active, they are launching fighter 
bombers from some of the islands in the region. At the moment we do not know which
island is it, we must try to find the next Russian base. Today our advance is at
halt until we regroup our forces for next assault. The anti air squads are scheduled
to arrive tonight which most likely will put a stop to the enemy air operations.
<br/><br/>

INTEL<br/>
Russian airborne operations are to be expected in our area today. Special Ops recon
teams have been reporting enemy armor movement towards the front lines. 
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at tank base. Keep ready for enemy
air and land attack anytime now. You must hold the base.
<br/><br/>

TACTICAL<br/>
Now if the commies get some bombers in the tank base, it will make some terrible 
destruction. Those vulcans are still too far away from Kolgujev coast so we must
hold it with just stingers. There is plenty of them in the ammo boxes, use 'em!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend off the Russians."];
objective1 setSimpleTaskDescription ["Defend off the Russians.", "Defend off the Russians.", "Defend off the Russians."];
