//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Assault to La Passagne fuel depot. Hmm I need to watch what I fire in there,
one wrong shot and BOOM it goes...






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from field. Assault 
targets:<br/> 
<marker name = 'target1'>Secure hilltop</marker><br/>
<marker name = 'target2'>Capture hilltop</marker><br/>
<marker name = 'target3'>Capture La Passagne</marker><br/>
<marker name = 'target4'>Capture Vigny</marker><br/>
<br/><br/>
Good luck!



<br/><br/>Golden Canyon<br/><br/>

GEN SITREP<br/>
Today we move against the heavily defended La Passagne fuel depot and
installations surrounding it. This is strategic objective in Malden and
Russians know that too, it will be heavily defended. Due our recent strikes
against enemy air defenses we can operate helos in this canyon. It should
give us the final edge to neutralize all Russians in La Passagne area.
<br/><br/>

INTEL<br/>
Our estimate is that in this canyon alike terrain we can safely operate helos
below the enemy anti air (shilkas) coverage. There is still threat from shoulder
launched missiles though. First objective has only infantry defenses at the moment
as the earlier shilka was knocked out. Second objective contains heavy AA defenses,
expect at least one shilka and AA soldiers. No heavy armor should be present. 
Objective three the fuel depot has intense defenses from dug in infantry and heavy
armor. Objective four has mostly infantry presence.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from field near the front lines, from
there you should proceed and take control of 
the <marker name = 'target1'>hilltop</marker> which contains the enemys old AA site. When its
secured, wait until vulcans arrive from starting location. When you're cleared to proceed,
assault the <marker name = 'target2'>AA Site</marker> in the hill. Wait for another vulcan and
M1A1 Abrams tanks to arrive. When they are on location, AH-64 Apache gunship callsign 
Foxtrot Black will be dispatched (codeword Golden Canyon) to strike the heavy 
armor in<br/><marker name = 'target3'>La Passagne</marker> area. You should wait until the target 
is more safe for you to attack it. When you think its time, issue attack order for the
second infatry squad and the Abrams tanks. Mission is accomplished when all Russians are 
wiped out from La Passagne fuel depot and <marker name = 'target4'>Vigny</marker> area.
<br/><br/>

TACTICAL<br/>
This is big one, we need all your skills now. Skip the jokes and get serious. After you
have secured the old AA site, wait for radio clearance from HQ to proceed. Same with
the active AA site. When the Foxtrot has neutralized most of the enemy armor and you feel
its safe to attack the fuel depot from the ground, issue radio (0-0-1) call for the tanks
and infantry that are supporting you. Also there are few ammo boxes where you start, so
plan what you need with this one. Good luck, you're gonna need it.
<br/><br/>













"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Capture Vigny"];
objective4 setSimpleTaskDescription ["Capture Vigny", "Capture Vigny", "Capture Vigny"];
objective3 = player createSimpleTask ["Capture La Passagne"];
objective3 setSimpleTaskDescription ["Capture La Passagne", "Capture La Passagne", "Capture La Passagne"];
objective2 = player createSimpleTask ["Capture hilltop"];
objective2 setSimpleTaskDescription ["Capture hilltop", "Capture hilltop", "Capture hilltop"];
objective1 = player createSimpleTask ["Secure hilltop until for AA"];
objective1 setSimpleTaskDescription ["Secure hilltop until for AA", "Secure hilltop until for AA", "Secure hilltop until for AA"];
