//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to rescue some civilians, ok this should be interesting.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airstrip, evacuate some
civilians from <marker name = 'target1'>trosky</marker> town.



<br/><br/>Blue Relief<br/><br/>

GEN SITREP<br/>
The enemy defenses and force compositions are indeed light in the northern Nogova,
they seem to have limited troops in place. Until they fully realize NATO is moving
against them and getting reinforcements, we must strike fast and hard. There are
some civilian population that has requested refugee status and want to get out of
the island before the fighting breaks out. We will try to get out as much of them
as possible.
<br/><br/>

INTEL<br/>
The mountains north east from the Trosky seem almost undefended, no vehicles are
detected in that area and no air defenses at all. Enemy helicopters are inactive.
Trosky itself has Russian infantry squad at minimum, we cannot really rely on
the civilian reports but they report that there are more forces in the castle 
ruins at the mountain top.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the airstrip, you will get inserted
with Black Hawk into the <marker name = 'insert'>insertion LZ</marker> north of the target
area. The civilian town is <marker name = 'target1'>Trosky</marker> and you must evacuate
all civilians in there. When you get to the civilians and establish contact, move them
to more safer <marker name = 'extract'>extraction LZ</marker> and call the helicopter with
radio call (0-0-1). Mission is accomplished when you return to base.
<br/><br/>

TACTICAL<br/>
Russians with light defenses, hey its nice for a change. When you get into the Trosky,
do NOT kill any civilians! it would not look good to return with civilian kills.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Evacuate civilians"];
objective1 setSimpleTaskDescription ["Evacuate civilians", "Evacuate civilians", "Evacuate civilians"];
