//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That was one firce fight let me tell you, I'm lucky to be alive. Lot of my buddies died
on this freaking city, I just hope everything is worth it...
<br/><br/>

Seems that today we have some less activity, intel is reporting no enemy movements detected
and so on. 
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Your team is holding city of Meaux <marker name = 'start'>here</marker>.



In the Meaux

We successfully defended Meaux for the second time now. Russians really had some serious
forces attacking this city, they must think its important. We have not found any special
reason, we have searched the houses and its an ordinary civilian city, nothing special.
<br/><br/>

Our intel has nothing on the front lines at the moment, no enemy movements to be concerned
about. Looks like the Russians are rethinking their tactics for a while at least.
<br/><br/>

You are to sit <marker name = 'start'>Meaux</marker> and be alert. Nothing on scope, but who 
knows what might happen in the next hour. Be alert. 

<br/><br/><br/>











"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Hold Meaux"];
_objective0 setSimpleTaskDescription ["Hold Meaux", "Hold Meaux", "Hold Meaux"];
