//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh my, now the commies got helos again.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from beach docks, wait for
resupply truck and shoot down enemy helos.



Airspace Denial

GEN SITREP<br/>
Enemy has gotten its air forces to active status, there is indication that
we get some aerial assaults today.
<br/><br/>

INTEL<br/>
Special Operations forces are reporting that enemy hinds are active in southern
Kolgujev. We estimate that they are heading our way at any minute.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at beach docks, wait for resupply
truck and get some stinger missiles from there. Shoot down any enemy helicopters
that fly into our air space. Good luck.
<br/><br/>

TACTICAL<br/>
They are sending you resupply truck so stay put, take stinger missiles from there
and bring down any helo (Russian!) you see in the area. You are free to engage.
Good hunting!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Get stingers "];
_objective1 setSimpleTaskDescription ["Get stingers ", "Get stingers ", "Get stingers "];
_objective0 = player createSimpleTask ["Shoot down enemy helos"];
_objective0 setSimpleTaskDescription ["Shoot down enemy helos", "Shoot down enemy helos", "Shoot down enemy helos"];
