//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Heavily defended intersection in enemy territory. Sounds cool.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the road. Assault
enemy held <marker name = 'target1'>intersection</marker> and capture it.



<br/><br/>Big Horizon<br/><br/>

GEN SITREP<br/>
Moving forward to the west in northern Nogova, next objective is the enemy
held intersection north east from Bludov. This intersection connects the
forest dirt road that goes down the south with the paved road in north.
The Russians have been using this to move the supplies into the front lines.
<br/><br/>

INTEL<br/>
The intersection itself is middle of three forest areas, its heavily defended
and most likely the Russians have troops in the forests too. Enemy helos are
flying much closer to the front line now, its unknown if they join the fight.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road, assault the enemy
held <marker name = 'target1'>intersection</marker> and wipe out all Russians there.
Your mission is accomplished when you control the area. Good luck.
<br/><br/>

TACTICAL<br/>
This is getting exciting, do the Russians throw some helos at us or not? Well if
they do you have your hands full as the Vulcans are far more eastern area from
there. Lets hope the birds stay away.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture intersection"];
objective1 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
