//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That Morton op was certainly a fast paced action again, I just wonder what kind of situation
we would got if the Russians had helicopters at their disposal... hmm
<br/><br/>

Anyways, seems that we have the job cut out for ourselfs again today. Three cities to be
captured, lot of enemies to be killed. Oh well, thats my specialty.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Capture <marker name = 'alpha'>Provins</marker> and <marker name = 'charlie'>Figari</marker>




<br/>Three Targets<br/><br/>

Todays objectives are three cities: Provins, Figari and Chotain. Capturing these locations
will provide us with more stable fighting grounds.
<br/><br/>

Intel have been getting signals of enemy armor movement and presence of other enemy forces
in all of the targets: Provins, Figari and Chotain.
<br/><br/>

You are the leader of Echo Black (start at <marker name = 'start'>here</marker>) and are 
tasked to assault and capture the city of <marker name = 'alpha'>Provins</marker> - Bravo team 
will strike <marker name = 'bravo'>Chotain</marker> from the north. Charlie team is coming from 
the Morton in south and will assault <marker name = 'charlie'>Figari</marker> - Your secondary 
objective is to backup Charlie team as Figari is close enough. So when Provins have been 
captured, you are to proceed into Figari to help Charlie squad. If you successfully 
eliminate Provins and Figari without heavy casualties, then engage any enemies you find 
from the general <marker name = 'clear'>area</marker> between these three cities, where we 
believe lot of enemies are patrolling. Good luck.

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Clear out area between"];
objective4 setSimpleTaskDescription ["Clear out area between", "Clear out area between", "Clear out area between"];
objective3 = player createSimpleTask ["Capture Chotain"];
objective3 setSimpleTaskDescription ["Capture Chotain", "Capture Chotain", "Capture Chotain"];
objective2 = player createSimpleTask ["Capture Figari"];
objective2 setSimpleTaskDescription ["Capture Figari", "Capture Figari", "Capture Figari"];
objective1 = player createSimpleTask ["Capture Provins"];
objective1 setSimpleTaskDescription ["Capture Provins", "Capture Provins", "Capture Provins"];
