//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I'm bit concerned what kind of battle we have with the mountain terrain here. Its one
thing to engage enemies on somewhat flat terrain, but this area is like one big
wall we must climb. I must focus...






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, proceed and
capture <marker name = 'target1'>base</marker> in the mountain.



Little Prince

GEN SITREP<br/>
Today we launch assault against the first of the enemy bases high up in the
mountain ridge which goes all the way up to the big mountain in the center of 
Kolgujev. When we get foothold on the mountain, the helicopters can ferry more
personel in there. It is extremely difficult if not impossible to get a tanks
up there.
<br/><br/>

INTEL<br/>
Enemy has withdrawn its helicopters from the front line currently. The base has
heavy defenses and probably some vehicles are present with infantry backbone.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road, you are to climb into
the high mountain ridge and capture <marker name = 'target1'>base</marker> which is the
first base in the long mountain. We will send helicopters to ferry more squads to
back you up when the area is secured.
<br/><br/>

TACTICAL<br/>
This is difficult one as the terrain is exrtemely rough when you approach the target.
Be very very careful with this one, enemy defenses and that mountain ridge is not the
safest place one could imagine. Keep the base secure until backups arrive by helo.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture the base"];
_objective0 setSimpleTaskDescription ["Capture the base", "Capture the base", "Capture the base"];
