//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Another day, another AA Site, Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from base. Helicopter
will <marker name = 'insert'>insert</marker> them south of 
the <marker name = 'target'>AA Site</marker> which is tasked to elimination.
<br/><br/>
After the AA site is down, Alpha will move 
to <marker name = 'extract'>extraction</marker> location and use radio (0-0-1)
to call helicopter.



Silver Obelisk

GEN SITREP<br/>
After our forces captured the small island on east, we can now have very good
helicopter operating base in very safe place. Its protected with Vulcans for
air assault, and Abrams tanks are guarding the beaches for assaults by boat/bmps.
We're safe there. Now we proceed to clear Malden island, todays operation
is for another piece of enemy integrated air defense system. South West of the 
island is a AA site on hilltop which we will neutralize.
<br/><br/>

INTEL<br/>
AA Site. One shilka present with some infantry. The area is near the front lines
so it should be crawling with enemies. Nothing major on armor front, some vehicles
are far to the north, but those should not pose a threat this time. No enemy 
helicopters are active at the moment.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the newly captured base. Blackhawk
helicopter will <marker name = 'insert'>insert</marker> you just south of your target
which is <marker name = 'target'>AA Site</marker> in the hilltop near the woods. After
the AA site is neutralized, proceed into <marker name = 'extract'>extraction</marker> point
and call Blackhawk to extract you. Mission is accomplished when you have neutralized 
the aa site and returned to <marker name = 'start'>home</marker> base.
<br/><br/>

TACTICAL<br/>
Finally some choppers! this is what we've been waiting for! The AA site is usual shilka 
plus infantry, take it out and get out. Intel don't expect there to be any heavy armor 
and helos around, but stay alert always. At the instant you can reclaim the extraction 
site safe, use radio (0-0-1) to call extraction. Keep the extraction site safe until 
the Blackhawk arrives and you're done with this one.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Return to base"];
_objective1 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
_objective0 = player createSimpleTask ["Neutralize AA Site"];
_objective0 setSimpleTaskDescription ["Neutralize AA Site", "Neutralize AA Site", "Neutralize AA Site"];
