//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Mental note:<br/>
Who's bright idea was it to take a flying trip with these lunatics, eh?
<br/><br/>

Never get aboard of helicopter (with crazy pilot) if you do not really need to get 
someplace. 
<br/><br/>

Okay so now we get some action again, we are being tasked to assault this enemy base close
to the airbase we're located. I hope nothing goes wrong with this one, we don't really have
much intel about the base, except that there is no armor present.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Your team starts <marker name = 'start'>here</marker> on the airbase, then 
<marker name = 'join'>joins</marker> up with the additional troops and assault the enemy 
base <marker name = 'ebase'>here</marker>.
<br/><br/>

Good luck.



Assault

We have gathered first squad ready for offensive action against the Russians. Our goal 
is to seize the nearest base due south from the airbase.
<br/><br/>

Intel is limited at this point, but we are certain that there is no enemy armor present
in the enemy base. There are unknown amount of enemy infantry stationed in the base. No 
serious guard activity, you should get very close without being detected.
<br/><br/>

You start from <marker name = 'start'>here</marker> in the airbase, the team boards 5t 
truck and drives to the hospital, where some supplemental infantry for the squad will 
be <marker name = 'join'>joining</marker> up. Then you are driven into nearby the enemy base. 
Your orders are to attack and take that enemy <marker name = 'ebase'>base</marker>. Make this 
one fast and clean. Don't let any Russians escape.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture enemy base"];
_objective1 setSimpleTaskDescription ["Capture enemy base", "Capture enemy base", "Capture enemy base"];
_objective0 = player createSimpleTask ["Join squad"];
_objective0 setSimpleTaskDescription ["Join squad", "Join squad", "Join squad"];
