//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Boy that was fast to drive around the jeeps .50Cal machineguns blazing. Never thought to get
to do something like that when I enlisted. sweet.
<br/><br/>

Right. So now we have this coordinated attack with bravo, charlie with big tanks and helo 
supporting us. This should be easy as the Russians so far have not put out very tough 
resistance, this plan looks good, I just gotta execute it good. Our forces will initiate
attack on my command (big boys giving me all this responsibility, woot) so it might be a 
good idea to sneak a bit close before I start this thing. Never hurt to get some up-to-date
recon of the area, I might even find some sneaky dug in ruskies around the place.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Today we conduct a coordinated attack.
<br/><br/>

Alpha team starts <marker name = 'start'>here</marker> in 
road. <br/>
Bravo team starts from <marker name = 'bravo'>hilltop</marker><br/>
Charlie team starts edge of the <marker name = 'charlie'>edge</marker> forest.
Delta team (M1A1 tanks) are bit behind in the <marker name = 'delta'>road</marker>
<br/><br/>

Objective is to <marker name = 'road'>seize</marker> enemy positions around this road. 
<br/><br/>

Initiate the coordinated attack by radio (0-0-1) command.
<br/><br/>

There is AH-1 Cobra helicopter gunship support available.




<br/><br/>Spike<br/><br/>

We continue wiping out the Russian positions on Everon.
<br/><br/>

There are enemy positions dug in around the intersection between the forests. Intel 
believes there are some armor present as well as reasonable sized infantry force. 
<br/><br/>

Objective is to seize the <marker name = 'road'>seize</marker> nearby the intersection. Our 
forces in this operation includes three squads of infantry <marker name = 'start'>Alpha</marker>, 
<marker name = 'bravo'>Bravo</marker>, <marker name = 'charlie'>Charlie</marker> and 
<marker name = 'delta'>Delta</marker> tanks.<br/>
Helicopter gunship support includes one AH-1 Cobra.
<br/><br/>

Everything begins when Alpha team leader initiates the attack command by using (0-0-1)
radio. Infantry and helo support then moves to attack enemy positions directly and the
tanks will move as far as <marker name = 'dposit'>here</marker><br/>
You receive report from Charlie when the teams move through cover waypoint. From that point
on the battle is more direct.
<br/><br/>

Do not proceed further to the enemy territory as the red coverage indicates in your briefing
map. We don't want to get greedy and our forces killed here. Our mission objectives are met
when all enemies are ran out of their positions in the region around the intersection.

<br/><br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Seize the area"];
objective1 setSimpleTaskDescription ["Seize the area", "Seize the area", "Seize the area"];
