//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Goddamn I got promoted! Whohuu! this is great! I'm now Sergeant!
<br/><br/>

Guess the commanders believe my ability to lead other men in battle. This is awesome, now
I need to really sharpen up for the command. Its my decisions that effect 8 men under my 
command. No mistakes are allowed here.
<br/><br/>

Sergeant... YEAH!
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Meet your newly arriving squad at the <marker name = 'meet'>airbase</marker>.
Take command and board the men into truck. Show them around the areas,
move into the Saint Phillippe <marker name = 'show1'>city</marker> and then to the
<marker name = 'show2'>base</marker> in south-east.




<br/><br/>Congratulations Sargent!<br/><br/>

NATO is holding Meaux, no enemy advances are happened since the battle of Meaux.
<br/><br/>

The intel guys are gathering information on enemy troop movements, no special to report
at this stage.
<br/><br/>

Congratulations Sergeant!<br/>
Meet your new squad at the <marker name = 'meet'>airbase</marker> and join up with them. Then 
move the men into the truck and drive them to 
the <marker name = 'show1'>Saint Phillippe</marker> city. From there proceed to 
the <marker name = 'show2'>base</marker> located south-east. Consider yourself as a tour 
guide, Sergeant!

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Tour the base"];
objective3 setSimpleTaskDescription ["Tour the base", "Tour the base", "Tour the base"];
objective2 = player createSimpleTask ["Tour Saint Phillippe"];
objective2 setSimpleTaskDescription ["Tour Saint Phillippe", "Tour Saint Phillippe", "Tour Saint Phillippe"];
objective1 = player createSimpleTask ["Join to your squad"];
objective1 setSimpleTaskDescription ["Join to your squad", "Join to your squad", "Join to your squad"];
