//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Damned Russians, I knew they would launch a counter attack again.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins #1, defend
the area at all costs.
<br/><br/>
Good luck.



<br/><br/>Enduring Haven<br/><br/>

GEN SITREP<br/>
Russians launched counter attack, we had expected something like this but not
so fast, we are still behind schedule to reinforce the defensive positions at
the area. Our forces are in tight spot right now before reinforcements arrive.
<br/><br/>

INTEL<br/>
We have some tanks coming in from north west and infantry from the nearby areas, 
meaning they will come from more or less from north, north west. No enemy 
helicopters are expected to join the fight.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at the ruins #1 along with Charlie
Abrams tank platoon. Bravo squad is 
on <marker name = 'bravo'>fuel depot</marker> alone. Delta squad is stationed as
backup in the ruins at the beach. Hold the Russians back until we get reinforcements.
<br/><br/>

TACTICAL<br/>
Damned those reinforcements took so long to arrive, you have to work this on your own 
now. Stay low and take accurate shots. If you run out of ammo, don't leave your post
undefended when going to pickup more ammo from the truck at fuel depot. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend the objective"];
objective1 setSimpleTaskDescription ["Defend the objective", "Defend the objective", "Defend the objective"];
