//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



My goodness, that was one mission I did not expect. Yet we managed it quite well in so 
short notice. I just hope we dont run into many of these missions in the future, its bitch
to go to a battle with little or no knowledge of what to expect.
<br/><br/>

Okay we have additional troops coming, thats always reassuring. Our squad has gone into
really some stealthy recon mode. Only two guys left... oh hell, under other circumstances
this might even be FUNNY! <br/>
I hope to survive this...
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Your orders are to hold city of <marker name = 'start'>Meaux</marker>
<br/><br/>

Good luck



<br/>Defence of Meaux<br/><br/>

The Russians reinforcements are just arriving to Meaux. We have slim forces on the ground 
at the moment as we had to move some of our forces to other tasks, but reinforcements are 
on the way.
<br/><br/>

Intel estimates that the reinforcement consists of two armored vehicles, most likely BMP's
which have infantry attachement. No signs on further enemy movement at this moment.
<br/><br/>

It is essential that you do not lose this city. We know the situation is tight as your 
squad has gotten so small. There is M1A1's standing by and additional infantry squad
(callsign BRAVO BLACK) on their way with BlackHawk into the Meaux to defend the city. 
Wait there and backup BRAVO.
<br/><br/>

<br/><br/><br/>











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Hold city of Meaux"];
objective1 setSimpleTaskDescription ["Hold city of Meaux", "Hold city of Meaux", "Hold city of Meaux"];
