//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Lets get those hiding Russians!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from La Trinite, clear out
any Russians at <marker name = 'target1'>area</marker> between city and beaches.



Shiny Beaches

GEN SITREP<br/>
Today we must clear out some of the area near La Trinite, east specificly. After
this operation we are set to go against saint Louis.
<br/><br/>

INTEL<br/>
Only light infantry is located east of La Trinite at the moment, these must be some of 
the forces that were scattered from the city when we took it. No enemy helicopters
are operating. No armor is present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from La Trinite with orders to clear out
all Russians in the <marker name = 'target1'>area</marker> east of the city. Clear the hills
all the way to the beach but do not proceed further north than the red dots indicate. When
all Russians are neutralized from this area, your mission is accomplished.
<br/><br/>

TACTICAL<br/>
Mop up ops, nothing special here. Stay sharp near the woods and don't let anyone flank you.
Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Clear area"];
_objective0 setSimpleTaskDescription ["Clear area", "Clear area", "Clear area"];
