//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Larche must fall!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from mountain, assault
and capture <marker name = 'target1'>Larche</marker> city.
<br/><br/>
Good luck!



Decisive Eagle

GEN SITREP<br/>
Today we assault city of Larche. Its one of those biggest cities in this island and 
it will be heavily defended. It would be a major morale boost if we could get our troops 
into this important city.
<br/><br/>

INTEL<br/>
Larche has lot of armor and infantry stationed in defensive positions. No enemy 
helicopters are present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the mountain, where you are to wait 
until <marker name = 'snipers'>snipers</marker> and <marker name = 'bravo'>Bravo</marker> squad
are ready to attack. In this time AH-64 Gunship and A-10 tank killer will soften up the 
target first. When you are ready, issue radio (0-0-1) command for the assault. Your 
objectives are met when no more Russians are left in 
the <marker name = 'target1'>Larche</marker> city area.
<br/><br/>

TACTICAL<br/>
Be careful with this one, the armor is too dammned heavy near the city that you must
wait until the air assets have taken out most of them. Move cautiously as the enemy is
so well dug in there that they will not give up easily.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture Larche"];
_objective0 setSimpleTaskDescription ["Capture Larche", "Capture Larche", "Capture Larche"];
