//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to seize another intersection, taking more room to run our vehicles
in this island. Always good stuff.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, seize 
the enemy <marker name = 'target1'>intersection</marker> and then
meet <marker name = 'bravo'>Bravo</marker> squad.



Blue Sword

GEN SITREP<br/>
Our assault to the front lines and enemy base was successful in all parts.
We have now crippled their air operations in Kolgujev, there cannot be much
more helicopters left for them to fly. Weather team reports that tomorrow the
weather starts to clear up, thats always a good news for all our forces.
<br/><br/>

INTEL<br/>
The road contains some fleed armored vehicles from yesterdays tank battle,
and infantry is in defensive positions. Russian helicopter operations have
had severe reduction in numbers now, we do not expect them to have many if
any flights in Kolgujev as most of their helos are destroyed. They can have
some hidden helos somewhere for emergencies, but we are keeping an eye on
the remaining enemy concentrations. The intersection which is todays main
objective will be heavily defended by infantry and armor. 
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> in the road with Charlie M1A1 
platoon working as the armor hammer. Proceed and clear the road leading into
the enemy <marker name = 'target1'>intersection</marker> up north. Seize it and
neutralize any remaining Russians in the nearby area. Then proceed into
meet <marker name = 'bravo'>Bravo</marker> squad in the friendly positions. Charlie
will remain to secure the seized intersection. Good luck.
<br/><br/>

TACTICAL<br/>
Now you have pretty much the same situation as yesterday, except today you
are roaming over the enemy fleeing cowards. Well maybe not cowards but most
of their armor in the road up to the intersection is what fled from yestrdays
battle. Stay alert.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Meet Bravo squad"];
_objective1 setSimpleTaskDescription ["Meet Bravo squad", "Meet Bravo squad", "Meet Bravo squad"];
_objective0 = player createSimpleTask ["Seize intersection"];
_objective0 setSimpleTaskDescription ["Seize intersection", "Seize intersection", "Seize intersection"];
