//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Our large assault to the russian base in coastline is finally here. I must focus, this
is the real thing, the big time.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and Charlie teams <marker name = 'start'>start</marker> from the road. 
Attack and capture the enemy <marker name = 'target1'>base</marker> in the beach.
<br/><br/>
Good luck.



<br/><br/>Grey Thunder<br/><br/>

GEN SITREP<br/>
Full effect of the thunderstorm has hit the Kolgujev, it pouring rains. Weather
however will not stop our advance, today we will assault and capture the large
Russian base in the east coast of Kolgujev. It is heavily defended so this is
join operation from air and land, infantry and armor. We must seize the intersection
south west of the base which will cut off enemy completely from this base and gives
us the possibility to drive our vehicles up to the central Kolgujev.
<br/><br/>

INTEL<br/>
Lot of infantry, lot of armored vehicles are defending the enemy base. No helicopters
have been detected in the area.
<br/><br/>

ORDERS<br/>
Alpha and Charlie squads <marker name = 'start'>start</marker> at the road along with
Foxtrot Black abrams tank platoon. The northern backup 
is <marker name = 'bravo'>Bravo</marker> squad who will cut off the road leading to 
the <marker name = 'target1'>base</marker> which is our main objective. Alpha Black One 
will issue radio command (0-0-1) to assault the base when everybody is ready and
the two helicopter gunships have softened up the target. When the target base 
have been captured you are to seize 
the <marker name = 'target2'>intersection</marker> south west of the main objective.
<br/><br/>

TACTICAL<br/>
There are AH-1 Cobra and AH-64 Apache gunships enroute to whip some russians as we 
speak, I suggest you let the soften up the target first before assaulting it. 
Keep it together people, this is important one.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Seize the intersection"];
objective2 setSimpleTaskDescription ["Seize the intersection", "Seize the intersection", "Seize the intersection"];
objective1 = player createSimpleTask ["Capture enemy base"];
objective1 setSimpleTaskDescription ["Capture enemy base", "Capture enemy base", "Capture enemy base"];
