//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This should be piece of cake, small town with light defenses. No biggie.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from beach, assault and
capture <marker name = 'target1'>Okrouhlo</marker> town.



Rough Way

GEN SITREP<br/>
Okrouhlo town is our todays objective which is located north east from the invasion
beach position. We have set up good defenses on the St. Sedlo so now its time to 
advance few hundred meters.
<br/><br/>

INTEL<br/>
We have alert from the Nogova airbase, SU-25 ground attack planes have been spotted
landing in the airbase, we do not know which point they are flying sorties. Okrouhlo
town has light defenses, most likely the heavy weaponry has been moved into Lipony.
Some helicopter activity on the west, not confirmed if they are heading this way.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from the beach, assault and
capture the <marker name = 'target1'>Okrouhlo</marker> town. Do not proceed further to the
north than the town limits. When you are in control of the town, your mission is 
accomplished.
<br/><br/>

TACTICAL<br/>
There aren't that many enemies in the Okrouhlo, but they sure are expecting you...
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Capture Okrouhlo"];
_objective0 setSimpleTaskDescription ["Capture Okrouhlo", "Capture Okrouhlo", "Capture Okrouhlo"];
