//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Yeah we had luck when we captured this base. But now we need to mop things up a bit in the
nearby area.<br/>
Goddamn if there are some Speznatz troops making ambush in the woods...
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


We have wood clearing for you.
<br/><br/>

Clear <marker name = 'Woods2'>woods #1</marker> located due north.<br/>
Clear <marker name = 'Woods1'>woods #2</marker> right here on east of the base. When you are 
cleared the woods, return to <marker name = 'start'>base</marker><br/>

Good luck and be careful out there.



<br/>Noises from Woods<br/><br/>

Our forces captured the enemy base near the airbase, we have now pretty security in the
south part of this island.
<br/><br/>

We have heard some noises from the woods that quite not fit to any animals, there might 
be some Russian troops lurking around. We cannot see too much into the woods and there is
nothing that really gives any indication of what we are up against. Could be one man or 
several, we just don't know.
<br/><br/>

Your job is to search and clear our any lurkers in these woods, Russian or otherwise.
Objective number one is the <marker name = 'Woods2'>woods #1</marker> in the north from the base, 
second objective is <marker name = 'Woods1'>woods #2</marker> in the east. These woods aren't
that large in size, so be careful and move slowly there, don't take too many risks in this
one. When the woods are swept from any enemy forces, you are to return back 
to <marker name = 'start'>base</marker> for debriefing.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Return to base"];
objective3 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective2 = player createSimpleTask ["Clear woods #2"];
objective2 setSimpleTaskDescription ["Clear woods #2", "Clear woods #2", "Clear woods #2"];
objective1 = player createSimpleTask ["Clear woods #1"];
objective1 setSimpleTaskDescription ["Clear woods #1", "Clear woods #1", "Clear woods #1"];
