//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Thank you Lord!
<br/><br/>

I'm still alive, it is unbelievable I survived my first combat experience!
<br/><br/>

Its true what they say, when that first bullet goes past your head - the politics goes 
right out from the window... It was me, my team and the enemy. Fight for our lives. It was 
amazing how the training kicked in when I first saw the first muzzle flashes from AK-74's,
those tracers trying to reach me... I never ever would have believed the feeling. I went 
like into this weird mode and just kept on going. If its not for me, its for my buddies, I
 gotta fight to save my buddies.
<br/><br/>

I'm at War now...
<br/><br/>

Good to see these reinforcements arriving, now I feel safer.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Reinforcements are arriving to the newly captured Russian airbase
 <marker name = 'start'>here</marker>. Enjoy the show.



Foundations

We have just successfully captured the Everon airbase in the early morning attack. 
There is limited troops on the ground at the moment and we hurry up for reinforcements
to lay down foundations for our new base.<br/><br/>

There is no sign of enemy forces in the immediate area of the airbase, we swept the 
nearest woods west and east of the airbase northern end near the buildings, also the 
southern buildings are cleared.<br/><br/>

Your mission is pretty much wait for reinforcements to arrive with ship. After these
guys are on the ground we can start to build the base.

<br/><br/><br/>











"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Reinforcements"];
_objective0 setSimpleTaskDescription ["Reinforcements", "Reinforcements", "Reinforcements"];
