//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh man this rain... it started to pour in last night. Man I hardly got any sleep with
the raindrops just dapping around the tent. Hrr. Man do I hate the rain or what...
<br/><br/>

If that wasn't the good news enough, its time to push forward on the east coast, that 
is one damned heavily defended beach... great, just great.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, black hawk helo take
you to the coastal <marker name = 'insert'>insertion</marker> point. From there 
push forward into the marked <marker name = 'target1'>point</marker> in the road.



<br/><br/>Rainman<br/><br/>

GEN SITREP<br/>
The weather front has arrived to Kolgujev, we can expect this rain continue for days. 
For our continued war effort we will push forward in the east coast towards the enemy
base. We are not attacking the base itself today, last pieces of intel will be gathered
and most likely the assault starts in 24-48hrs.
<br/><br/>

INTEL<br/>
The east coast around the road is heavily defended, armor and infantry. Enemy is 
definitely waiting for us. No enemy helos are currently present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the ruins, black hawk helicopter
will <marker name = 'insert'>insert</marker> your team to the beach. From there meet up
with <marker name = 'bravo'>bravo</marker> squad. From the front line assault the enemy
position until you reach <marker name = 'target1'>target</marker> area or you cannot
get through anymore. Good luck.
<br/><br/>

TACTICAL<br/>
This is ugly weather I tell you... but still we got a island to free. Time to go to 
work. Take it slow on the front line, the enemy is well dug in and they will not give
up the positions so easily. Keep your team alive.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Assault the enemy positions"];
objective1 setSimpleTaskDescription ["Assault the enemy positions", "Assault the enemy positions", "Assault the enemy positions"];
