//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I hope everything goes by the numbers today, that terrain is pretty deceptive.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Blata, assault 
the <marker name = 'target1'>intersection</marker> clearing out all
Russian defenses, then capture <marker name = 'target2'>Loukov</marker> town.



Shining Brass

GEN SITREP<br/>
Eastern Nogova has two main roads, today we are going after the one on the east coast.
We must seize the intersection coming from Blata and after that by the end of the
road there is Loukov town held by Russian forces. Anything further north is pretty
much rural areas where vehicles are difficult to operate. 
<br/><br/>

INTEL<br/>
Some vehicles are spotted in the Loukov area along the road, rest of the opposing
Russians are infantry on defensive positions. Also stay alert for any possible
helicopters as there have been some activity reports from the airbase.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Blata. You are to assault and
clear the <marker name = 'target1'>intersection</marker> leading to the main road. From
there proceed to <marker name = 'target2'>Loukov</marker> assaulting and capturing it.
Good luck.
<br/><br/>

TACTICAL<br/>
Ok you need to make a decision whether to bring along AA launchers as the intel 
peeps have been reported some helicopter activity.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Capture Loukov"];
_objective1 setSimpleTaskDescription ["Capture Loukov", "Capture Loukov", "Capture Loukov"];
_objective0 = player createSimpleTask ["Clear intersection"];
_objective0 setSimpleTaskDescription ["Clear intersection", "Clear intersection", "Clear intersection"];
