//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "
This is going to big one, I'm cool. Bring it on, yeah!"]];
player createDiaryRecord ["Diary", ["Mission", "
Alpha team <marker name = 'start'>start</marker> from road. Sweep through
the <marker name = 'target1'>area</marker> and capture <marker name = 'target2'>woods</marker> and
the <marker name = 'target3'>mountain</marker> top.
<br/><br/>

Good luck.

<br/><br/>Square Matrix<br/><br/>

GEN SITREP<br/>
Todays operation is big push to the open areas in central Nogova. The enemy has strong
defensive forces set up there and we need combined air and land troops to remove all
enemy poisitions. With the successfull completion of this operation, we are in striking
distance of Mirov.
<br/><br/>

INTEL<br/>
The open area consists lot of enemy armored contacts, mostly BMP's an T-72's. There
are strong infantry presence also, but no enemy helos are flying there.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road, your support is M1A1 Abrams
platoon callsign <marker name = 'ustanks1'>Bravo</marker> just west of your position. In the
air we have AH-64 Apache gunship callsign Charli Black. When you issue radio call 
(0-0-1) to assault, bravo and charlie will move into 
the <marker name = 'target1'>sweep</marker> area to engage targets. Mission objectives include
the specific targets of <marker name = 'target2'>woods</marker> and 
the <marker name = 'target3'>mountain</marker> top that must be captured. Bravo platoon will
move slowly through the area and stops just north west of the mountain objective. Good 
luck all of you.
<br/><br/>

TACTICAL<br/>
Okay this is a big one. The ruskies have tons of steel in that field. Be extra careful 
as its going to be murder down there. The bright HQ has decided to send gunships and
tanks at the same time, so if you decide to go alone first keep that pretty head of
yours down! It escapes me why we couldn't just bombard them into stoneage first, now
we all go in at the same time and thats going to be one big mess. Oh well, thats our
orders so get moving solider. Good luck!
<br/><br/>

"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture woods"];
objective2 setSimpleTaskDescription ["Capture woods", "Capture woods", "Capture woods"];
objective1 = player createSimpleTask ["Sweep area"];
objective1 setSimpleTaskDescription ["Sweep area", "Sweep area", "Sweep area"];
