//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That intersection op was a blast, so much happening.
<br/><br/>

So what today... Oh boy do I hate these wood cleanups... sigh
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Clear out the :<br/>
<marker name = 'woods1'>Woods #1</marker><br/> 
<marker name = 'woods2'>Woods #2</marker><br/>
<marker name = 'woods3'>Woods #3</marker>



Leftover troops

Our task is to clear up the central NATO occupied area that there aren't any 
leftover Russian infantry hiding in there. We have some communications from the Russians
that they want to discuss with the NATO commanders. We will see what they want.
<br/><br/>

We had some reports on the Russian infantry hiding in the woods at NATO occupied grounds. 
There definitely are some leftover troops trying to re-group, but they are very 
unorganized and most likely dont have radio support as they are so far behind enemy lines.
<br/><br/>

We are tasked to comb through the woods to seach Russian infantry left behind, who are 
hiding in the woods. Alpha will be inserted with helicopter, the LZ 
is <marker name = 'lz'>here</marker>. You are tasked to sweep the woods in this sector, there 
are three separate woods: <br/>
<marker name = 'woods1'>Woods #1</marker><br/> 
<marker name = 'woods2'>Woods #2</marker><br/>
<marker name = 'woods3'>Woods #3</marker><br/><br/>

There will be air support, armor support and supply truck available to back you up. The 
supply truck will be driven near the Landing Zone (<marker name = 'lz'>LZ</marker>). Be careful 
out there, good luck.

<br/><br/><br/>











"]];
// tasks need to be in reversed order
_objective2 = player createSimpleTask ["Clear woods #3"];
_objective2 setSimpleTaskDescription ["Clear woods #3", "Clear woods #3", "Clear woods #3"];
_objective1 = player createSimpleTask ["Clear woods #2"];
_objective1 setSimpleTaskDescription ["Clear woods #2", "Clear woods #2", "Clear woods #2"];
_objective0 = player createSimpleTask ["Clear woods #1"];
_objective0 setSimpleTaskDescription ["Clear woods #1", "Clear woods #1", "Clear woods #1"];
