//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Oh Uh another fast roping down. Geesh!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, board black hawk
which will insert you to <marker name = 'target1'>target</marker> island
where you neutralize all Russians.
<br/><br/>
Have fun.



<br/><br/>Fast Escape<br/><br/>

GEN SITREP<br/>
Its been one celebration since we freed Kolgujev from Russian control. We have been
trying to find any remaining enemies in the island but its rather difficult so far.
Work is in progress as we speak. Luckily our inteligence sources found out that
the small island north of the Kolgujev is indeed rendezvous point of Russian 
soldiers who are escaping, we must make every effort to stop them.
<br/><br/>

INTEL<br/>
We have optained information that there are several Russian soldiers in the small 
island north from Kolgujev. They are believed to be the part of the remaining
soldiers who are hiding and obviously escaping from Kolgujev.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base. Board the waiting Black
Hawk helicopter which will fly you to the 
small <marker name = 'target1'>target</marker> island where the Russians are gathering.
Fast Rope down from the helo and neutralize all Russian soldiers present. When you
are ready, radio the helo and it will pick you up and bring back to the base.
<br/><br/>

TACTICAL<br/>
Okay after the late night parties in the camp, we get to go do some damage again. 
Remember the fast roping, fun and games... fun ang games, hehe. This mission should
be just a walk in the park. Have fun!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear the island"];
objective1 setSimpleTaskDescription ["Clear the island", "Clear the island", "Clear the island"];
