//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




It takes some time to climb that mountain I tell you...






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road and proceeds to 
capture <marker name = 'target1'>mountain</marker> top. 



<br/>Intense Zone<br/><br/>

GEN SITREP<br/>
The central mountains of Malden are hideouts for russian infantry and also
some anti air sites. Today we move against one of the mountain sites in our
effort to reduce enemys ability to keep our helos from operating.
<br/><br/>

INTEL<br/>
There is another Anti Air Site in the mountain somewhere, infantry but not other
enemy armored vehicles. Enemy vehicles are operating more in north, north west.
Enemy helicopters are actively patrolling the central island.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from road north of Chapoi. From there
you are to proceed into the <marker name = 'target1'>mountain</marker> and capture it.
When its under your control, Bravo squad will be dispatched to back you up so 
keep the site secure until they arrive. Mission is accomplished when Bravo has reached
the mountain top.
<br/><br/>

TACTICAL<br/>
This mountain climbing is going to be tough, even tougher to fight there. Be careful
with the shilka as the engagement ranges are knife fight style, when the shilka and
infantry is taken out bravo will join you, wait for them. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Secure it until backup arrives."];
objective2 setSimpleTaskDescription ["Secure it until backup arrives.", "Secure it until backup arrives.", "Secure it until backup arrives."];
objective1 = player createSimpleTask ["Capture mountain"];
objective1 setSimpleTaskDescription ["Capture mountain", "Capture mountain", "Capture mountain"];
