//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This should be small and neat operation.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Neveklov, assault
and capture <marker name = 'target1'>houses #1</marker> and 
also <marker name = 'target2'>houses #2</marker> in the beach.



<br/>Silver Anvil<br/><br/>

GEN SITREP<br/>
Our forces were successful taking the Neveklov, we are getting much closer now
to the airbase which is the main headquarters of Russian forces on Nogova. Today
we advance and capture two farm houses in south central Nogova.
<br/><br/>

INTEL<br/>
There is no sign of Russian helicopters and we estimate that they are keeping the
last ones emergency situations. The objectives today are defended by infantry
and some vehicles.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Neveklov, assault the two
small farmhouses <marker name = 'target1'>houses #1</marker> and 
also <marker name = 'target2'>houses #2</marker> in the beach. Today you have AH-1 
Cobra gunship as air cover. Your mission is accomplished when these objectives 
are under NATO control.
<br/><br/>

TACTICAL<br/>
Keep it simple, dont get killed. Watch for the Cobra to give you indication for
enemy vehicles.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture house"];
objective2 setSimpleTaskDescription ["Capture house", "Capture house", "Capture house"];
objective1 = player createSimpleTask ["Capture Farmhouses"];
objective1 setSimpleTaskDescription ["Capture Farmhouses", "Capture Farmhouses", "Capture Farmhouses"];
