//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



To the hills, to the valley... from top to the bottom. What do I care as long
as there are enemies to waste, Hooayh!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha starts from <marker name = 'alpha'>here</marker> Bravo starts east from target 
area <marker name = 'bravo'>here</marker> and Charlie starts west 
in <marker name = 'charlie'>here</marker><br/>Mission <marker name = 'durras'>target</marker> is
city of Durras. Clear out any enemy opposition.





Sweet Sweep

Our forces keep on pushing towards the southern tip of this island.
<br/><br/>

Intel reports two tanks in the Durras along with infantry presence. We have reason to 
believe that there are anti-armor team hiding behind the city and we are unsure of the
roads situation with mines. Intel do not recommend sending in armored vehicles.
<br/><br/>

Alpha starts <marker name = 'alpha'>here</marker> north of the Durras in the 
valley, <marker name = 'bravo'>Bravo</marker> squad is directly east in the hillside 
and <marker name = 'charlie'>Charlie</marker> is at opposing side of the hills. HQ decided 
not to send any armored vehicles as we have reason to believe they would met heavy 
anti-armor and possible mines at the target. Your mission is to assault and clear out any
enemy forces from <marker name = 'durras'>target</marker> are which is city of Durras, objectives
are met when there are no Russians left.
<br/><br/>

We have another piece of Russian realestate to seize. 
Our <marker name = 'durras'>target</marker> today is Durras. The operation forces are three 
squads <marker name = 'alpha'>Alpha</marker> in the 
north, <marker name = 'bravo'>Bravo</marker> in east 
and <marker name = 'charlie'>Charlie</marker> in the west. Plan is to assault the city from 
these three directions using just infantry. We have threat from enemy anti-armor team and
possible mines so no armored support guys, sorry about that.
<br/><br/>














"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Assault Durras"];
_objective0 setSimpleTaskDescription ["Assault Durras", "Assault Durras", "Assault Durras"];
