//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



My goodness, those prisoners who escaped are now taking innocent civilians as hostages.
Shit what a meatheads.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Proceed into the <marker name = 'asspos'>building</marker> and wait for go code. When you 
do receive<br/>
the GREEN LIGHT go code, assault and clear 
the <marker name = 'target'>target</marker> house.
<br/><br/>





<br/><br/>Hostage Hero<br/><br/>

The POW's who has turned themselves to hostage takers are demanding safe truck transport
to the Russian controlled area where they promised to release the hostages. If any NATO 
personell is detected in the Provins area they will execute the hostages. If their demans
aren't met, they will execute the hostages. The situation is under our control, but we are
not prepared to storm the building yet, we will try everything to get them to surrender
peacefully.
<br/><br/>

The escaped POW's are found. Unfortunately they have found some old AK rifles from the
leftovers and are now holding up four civilias as hostages in the house at Provins.
Total number of tangos in the target location is six, two are guarding the hostages and
two (possibly leadership) are remaining in the center of the building. We have reason
to believe that these men are desperate and will execute the hostages if they feel that
they are being threatened.
<br/><br/>

Your team <marker name = 'start'>starts</marker> at Figari. Your orders are to get on board
the humvwee which will take you to the forest 
edge where you <marker name = 'disembark'>disembark</marker> and proceed on foot into the other
edge <marker name = 'waypoint'>here</marker> - then you move 
into <marker name = 'asspos'>position</marker> behind a building north-west from 
the <marker name = 'target'>target</marker> house 
where the tangos are located. If you are ordered to do so, you will storm the building and
clear out any elements that threaten the hostages.
<br/><br/>

This is a bad scenario. Bad for the hostages and bad for the tangos. We have the place 
surrounded since earlier today, there is no way out for these guys and they must know it.
Our 
snipers (<marker name = 'sniper1'>sniper #1</marker> and <marker name = 'sniper2'>sniper #2</marker>) 
have been on the location for quite some time and we have got good intel from them. Your
team will position behind the next building from where the tangos are, from that position 
you can quickly move in if we get to go. HQ does not want us to rush into this, they have
kept the snipers under strict hold fire mode for the whole time. If the situation develops
further they might change their minds and thats when you guys come to play. Go code for
the assault is simply GREEN LIGHT - make a note that you cannot be seen or cannot
fire on the tangos before you receive the code word, its going to be hell to pay if you do.
All right, good luck and shoot sharp if it comes to that.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Eliminate Tangos (if ordered)"];
objective2 setSimpleTaskDescription ["Eliminate Tangos (if ordered)", "Eliminate Tangos (if ordered)", "Eliminate Tangos (if ordered)"];
objective1 = player createSimpleTask ["Proceed into assault point"];
objective1 setSimpleTaskDescription ["Proceed into assault point", "Proceed into assault point", "Proceed into assault point"];
