//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




La Riviere, the beach town to be captured.

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha and Bravo <marker name = 'start'>start</marker> from the hill, they proceed
and capture <marker name = 'target'>La Riviere</marker> objective.



<br/><br/>Silver Sabre<br/><br/>

GEN SITREP<br/>
Massive Russian attack is repelled and we move forward. La Riviere is one of the 
largest Ports in this island and Russians get lot of supplies through this town.
We can signifigantly reduce their supplies if we capture this port.
<br/><br/>

INTEL<br/>
We have been looking La Riviere and the estimates are that there are two mechanized 
and two normal infantry squads present. Some smaller infantry patrols are also in the 
area guarding the town. Russian air activity is to be expected, so keep your heads down.
<br/><br/>

ORDERS<br/>
Alpha and Bravo is tasked to capture <marker name = 'target'>La Riviere</marker> town. Bravo
proceeds from the Eastern route (<marker name = 'bravo1'>#1</marker> <marker name = 'bravo2'>#2</marker>)
where alpha should take the western near the coastline route. Mission is accomplished when
no Russian troops are present in the town area.
<br/><br/>

TACTICAL<br/>
Be careful with the meachanized infantry out there, keep your LAW guys ready. Also the enemy
helos most likely will show up so keep your head down and wish that the Vulcans will take
them out before they hurt you. There is AT team to go along with you, so try to keep these guys
alive will you.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture La Riviere"];
objective1 setSimpleTaskDescription ["Capture La Riviere", "Capture La Riviere", "Capture La Riviere"];
