//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This is going to be one big fight. I just hope to survive this... we are getting 
actually pretty close to capturing this island, there is no time for dying now.
I'll just keep my head down, take accurate shots and trying not to do anything
stupid like being a hero. Yeah, thats what I'll do allright. Time to toas some
Russians, lets hit the road!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, assault
and capture enemy <marker name = 'target1'>base</marker> in the west
coast.



<br/><br/>Urgent Fox<br/><br/>

GEN SITREP<br/>
Today we initiate operation to capture enemys only base in the west coast of 
Kolgujev. They have massive tank depot located in that area and we expect the
open areas to drag us a big tank battle. Good news are that the weather team
is now predicting that the weather starts to clear up soon.
<br/><br/>

INTEL<br/>
We are looking for last enemy helicopter base in the area so expect them to have
some helos in the air defending it. There will be heavy tanks and lot of infantry
present near the base, along the coast line.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from the ruins, with M1A1 
Abrams tank platoon. You'll advance right into the 
enemy <marker name = 'fl'>front lines</marker> and push through it neutralizing all Russians.
Push all the way until you capture the <marker name = 'target1'>base</marker> in the coast.
Today You got two AH-64 Apache gunships and A-10 overhead supporting the assault. 
Good luck everybody.
<br/><br/>

TACTICAL<br/>
The defenses are dense, make no mistake gentlemen... you are walking into the heavies
Russian defenses in a long time. The open areas in the beach are just littered with
tanks. Do not get yourself killed over there.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture base"];
objective1 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
