//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



The ops for capturing Le Moule really got interesting, I love the intel peeps who keep
feeding us this urgent new detail we need to run after it.
<br/><br/>

Night time flash raid to Morton, speed and surprise. Yehaa here we come!
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Capture <marker name = 'morton'>Morton</marker>



<br/>Morton<br/><br/>

We keep on pushing deeper into the enemy territory, next city to fall is Morton on the
coast. 
<br/><br/>

Intel reports no enemy armor present in the city of Morton, there is heavy infantry 
presence however.
<br/><br/>

Tonight we are going to capture city of Morton. This is major landmark on the battlefield 
so, be decisive, be aggressive. We have thee squads conducting the assault. Insertion 
points are :<br/>
<marker name = 'lz1'>LZ #1</marker><br/>
<marker name = 'lz2'>LZ #2</marker><br/>
<marker name = 'lz3'>LZ #3</marker><br/><br/>

When you get into the ground, move fast, use cover and ran those Russians out of the town.
This mission dont reguire night vision goggles as the city is all lit up, try to use the 
lights to your advantage.

<br/><br/><br/>










"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Morton"];
objective1 setSimpleTaskDescription ["Capture Morton", "Capture Morton", "Capture Morton"];
