//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Sniper hunt. quick and deadly. 






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from fuel depot and
boards helo, search and destroy 
enemy <marker name = 'target1'>sniper</marker> team behind friendly lines.



Red Sniper

GEN SITREP<br/>
Weather keeps improving slowly, it should not take long now to have the rain stop
completely and skys getting clearer. We have had few insidents near the large base
at east coast where sniper or snipers have assasinated some of our personnel. This
cannot continue and we are tasking operation to hunt down the sniper teams.
<br/><br/>

INTEL<br/>
You will be operating at friendly lines hunting down one or perhaps two enemy 
sniper teams who are in hiding. They believed to be operating somewhere nort west
of the base.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> at the fuel depot, board the incoming
Black Hawk helicopter which will <marker name = 'insert'>insert</marker> you to the ruins.
Find the <marker name = 'target1'>sniper</marker> team or teams that have been operating
somewhere north west from our base in the coast. Your backup is Delta squad who starts
from the base in the coast and AH-1 Cobra gunship callsign Charlie Black. Good luck.
<br/><br/>

TACTICAL<br/>
This could be tricky, its easy to fight massive troop concentrations, but to seek out
and eliminate one or two men in large area, this could be tricky... Happy hunting!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Find and kill Sniper team"];
_objective0 setSimpleTaskDescription ["Find and kill Sniper team", "Find and kill Sniper team", "Find and kill Sniper team"];
