//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Damn only few minutes time to write before we are inserted. ok many russians
attacking the base, thats all I need to know. Better to keep my head low and
take accurate shots. Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from road, board helo
and join base <marker name = 'target1'>defenses</marker> in the east coast.
<br/><br/>
Good luck.



Intense Ivan

GEN SITREP<br/>
We have emergency situation, massive russian attack is under way to our
east coast base. They have already started to attack there, we need to 
redirect our forces in the defense.
<br/><br/>

INTEL<br/>
Not much intel available, we are sorry our assets were committed to other part
of the island at the moment.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> in the 
road, <marker name = 'pickup'>board</marker> the black hawk which 
will <marker name = 'insert'>insert</marker> you north of the base. Join 
its <marker name = 'target1'>defenses</marker> and repell Russian attack.
Bravo squad and tanks are already defending the <marker name = 'bravo'>outer</marker> perimeter.
<br/><br/>

TACTICAL<br/>
How did this happen, how did they manage to put together counter attack without
our intel knowing about it. The first wave already knocked out few of our tanks
and people in the front line and now second wave is inbound. get there QUICK!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Defend the base"];
_objective0 setSimpleTaskDescription ["Defend the base", "Defend the base", "Defend the base"];
