//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



NATO and Russian commanders are negotiating for cease fire, so what the fuck are the
Russians preparing for attack then!?
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Defend your <marker name = 'start'>positions</marker>




Positions

We intend to hold these positions until we move forward with out objectives or permanent 
cease fire has been established. By tomorrow we should have more information on the 
negotiations.
<br/><br/>

Intel has reliable information that while the negotiations continue overnight, the Russians 
are in fact rolling into our defensive positions. Attack is imminent. The enemy forces have
combined infantry and armor. The Russian T-80 tanks have been detected moving towards the
front line.
<br/><br/>

Your mission is to hold the postions westside of the barricades, you are not to cross the 
east side, to commence anykind of offensive manuevre. Enemy force is coming 
from <marker name = 'attack'>this</marker> direction. Our defensive positions are nearby your 
starting location, <marker name = 'start'>here</marker> - do not let any Russians pass this 
line. Stop and waste all of them trying. You have artillery support (automatic) and 
optional Battlefield Illumination with arty flares (radio code 0-0-1). The artillery 
support fires only once, the flares are available as many times you radio them in. Just 
behind your positions are two other squads and one platoon of M1A1 tanks. These consists 
the NATO forces present in the sector at the moment.

<br/><br/><br/>










"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Repel enemy attack"];
_objective0 setSimpleTaskDescription ["Repel enemy attack", "Repel enemy attack", "Repel enemy attack"];
