//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This is the first mission behind enemy lines at Nogova, makes you wonder what 
might be there waiting for us.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airstrip, destroy
the <marker name = 'target1'>radar site</marker> in the hill.



<br/><br/>Anatolis Eyes<br/><br/>

GEN SITREP<br/>
There is no enemy anti air units present in the northern Nogova so we are pretty
free to fly our helicopters and planes in the area. There is however radar site
in north west part of the island which must be knocked out before we can fully
operate in the Nogova region. We just cannot eliminate it with laser guided bombs
because there can be vital information about the other defenses, our troops must go
in and do search in the site. The plan is to have fast attack insert - extract 
operations against the enemy to disrupt their daily routine. The enemy defenses
seem bit light, which we must use our advantage as they most likely will bring in
reinforcements soon.
<br/><br/>

INTEL<br/>
There is high signal radar emitter in the hill, defenses are mostly light infatry 
with perhaps few vehicles. No air defenses are present and the enemy helicopters
are grounded after the last nights attacks.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the airstrip, you are inserted
into the <marker name = 'insert'>beach</marker> just north east from your main target
which is to destroy a <marker name = 'target1'>radar site</marker> in the hill. When
the objective has been accomplished, proceed 
into <marker name = 'extract'>extract LZ</marker> for helicopter extraction. 
<br/><br/>

TACTICAL<br/>
Use caution, this is the first operation behind enemy lines and even the intel peeps
suggest the defenses and troop concentrations are light in nature, no plan survives
the first contact. Your squad will be the first one to find out if the intel is correct.
Good luck and be careful!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Return to base"];
objective2 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective1 = player createSimpleTask ["Destroy radar site"];
objective1 setSimpleTaskDescription ["Destroy radar site", "Destroy radar site", "Destroy radar site"];
