//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to escort some special forces back to base as their radio is busted.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Okrouhlo. Board helo
which will take you to a special forces extraction point. Find them 
at this generic location and get everyone extracted.



Black Cover

GEN SITREP<br/>
The Bitov was successful operation, but the fight was more intense than expected,
Russians are massing move troops to Nogova daily. We must keep the pressure on
them before they can put too heavy defenses in the eastern sector of this island.
Unfortunately they do seem to have heavy defenses set up in the western part of
Nogova.
<br/><br/>

INTEL<br/>
One of our best special operation forces teams has been on the enemy territory for
long period now, they are running out of food and ammo, they need to be extracted.
Problem is that their radio must be broken because we cannot reach them. We must
send someone to the pre planned extraction point to make contact with them.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Okrouhlo, you first board the
incoming Black Hawk which will fly you behind enemy lines 
and <marker name = 'insert'>insert</marker> you into the pre planned extraction location 
of Delta Black spec ops team. When you get into the ground, call them on radio
using (0-0-1). When you have met them, proceed 
into <marker name = 'extract'>extraction</marker> point in the coast line. It should be 
safe. When you are at the extract LZ, use radio call (0-0-2) to call the black hawk
to pick you up. Your mission is accomplished when you arrive back to base.
<br/><br/>

TACTICAL<br/>
Okay special forces guys radio battery must have been run out of someting as lame as
that. So you'll need to find them. When you jump out of the helo, stay put and try
to call them on radio. These guys are smart and professional, they most likely see
you coming a mile away. Stay put, use the radio and all should work out just fine.
<br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Return everyone to base."];
_objective1 setSimpleTaskDescription ["Return everyone to base.", "Return everyone to base.", "Return everyone to base."];
_objective0 = player createSimpleTask ["Meet Special Forces."];
_objective0 setSimpleTaskDescription ["Meet Special Forces.", "Meet Special Forces.", "Meet Special Forces."];
