//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Last big mountain in North West of Nogova, soon to be NATO's mountain.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Mokra Vrata. Clear out
the <marker name = 'target1'>mountain</marker> in north west.



Northern Wind

GEN SITREP<br/>
The last mountain in north west Nogova is the objective of todays operation.
After this operation we control the whole northern region of the island and we
area ready to start move towards south.
<br/><br/>

INTEL<br/>
Most of the enemy armor has been wiped out, but few softer vehicles might be lurking
in the nearby area. The mountain has only infantry defenses.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Mokra Vrata, assault and clear out
the <marker name = 'target1'>mountain</marker> west from your location. Leave no Russians
wandering around in the area. Good luck.
<br/><br/>

TACTICAL<br/>
The ruskies are cornered and they know that. Be careful on this one.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Clear out mountain"];
_objective0 setSimpleTaskDescription ["Clear out mountain", "Clear out mountain", "Clear out mountain"];
