//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That was one hellowa ambush, the Russians didn't much expect such a warm welcome.
<br/><br/>

Its getting dark, we have to move fast to the road block. I dont want to fight in the
darkness near these woods.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Seize the <marker name = 'road'>road</marker> between woods.




<br/><br/>Road Block<br/><br/>

We are preparing our troops to assault for city of Montignac. So we must clear out the 
narrow road passage through the woods as it is very deadly ambush point and will be used 
to reinforce Montignac in any possible attack situations.
<br/><br/>

We dont have any additional intel for the woods or road area. But its assumed the enemy 
sees this position as we do and its occupied.
<br/><br/>

You begin from <marker name = 'start'>Gravette</marker>, you are then to proceed in 
the <marker name = 'road'>road</marker> between woods. Its vital that we take control of this 
piece of road so we can cut it off and plan future ambushes. After you have cleared it, stay
alert for possible reinforcements.

<br/><br/><br/>










"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Repel reinforcements"];
objective2 setSimpleTaskDescription ["Repel reinforcements", "Repel reinforcements", "Repel reinforcements"];
objective1 = player createSimpleTask ["Clear the road block"];
objective1 setSimpleTaskDescription ["Clear the road block", "Clear the road block", "Clear the road block"];
