//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I'm so scared. I just vomited before we boarded the chopper... I'm sure I'm going to 
die in next couple of hours. Please God, forgive me for every bad thing I've done in 
my life.
<br/><br/>

I'm so sorry...

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Today we start our war with the Russians.
<br/><br/>

Alpha and Bravo teams will be <marker name = 'LZ'>inserted</marker> in the runway.

Clear out all the enemy forces from this airbase.
<br/><br/>

There is AH-1 Cobra and AH-64 Apache helicopter support available.




<br/>War Starts<br/><br/>

Our War starts from this point. First move of the war is to assault the Everon's
only airbase located in the north. When we get control over this strategic location
and our forces in the ground, we can conduct air operations for the rest of the island.
<br/><br/>

Our Special Forces conducted reconnaissance last night and gathered some good intel about
the enemy positions. Here is what we know.<br/>

There is <marker name = 'sniper'>sniper</marker> located between the houses in the south end
of the runway, make sure you don't get caught in he's fire before the threat is eliminated.
Enemy has placed guards <marker name = 'guard1'>here</marker> and 
<marker name = 'guard2'>here</marker> be alert for these guys. Main enemy troops are positioned 
in the central part of the airbase right <marker name = 'inf'>here</marker><br/>
Stay alert for the enemy MI-17 Helicopter the intel reported being operating in the area.
<br/><br/>

Alpha and Bravo teams are inserted with Chinook from <marker name = 'coming'>this</marker> 
 direction. When you hit the ground, move fast! don't get caught in the enemy crossfire.
Our objective is to capture the airbase. You can do this either by killing all enemy forces
or making them flee from the airbase area.

<br/><br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture enemy airbase"];
objective1 setSimpleTaskDescription ["Capture enemy airbase", "Capture enemy airbase", "Capture enemy airbase"];
