//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Assault to the enemy base, okay, I'm up for it. 






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the road. Assault
and clear the <marker name = 'target1'>intersection</marker> leading to the
enemy <marker name = 'target2'>base</marker> which is your main objective.



<br/><br/>Safe Nighthawk<br/><br/>

GEN SITREP<br/>
Today we will take the next enemy base in southern part of Kolgujev. There are
actually three separate objectives in that area, but first objective is this
eastern base of the three.
<br/><br/>

INTEL<br/>
Enemy is stationing tanks and other armored vehicles in that base, it seems to be
repair station of some kind with heavy equipment. Most likely high value facility
for the Russians. Helicopters are active in this part but most likely they keep out
from the battle and support forces in their own territory.
<br/><br/>

ORDERS<br/>
Alpha and Bravo squads <marker name = 'start'>start</marker> from the road, abrams tanks
are keeping good distance in the north east. First you must attack and seize 
the <marker name = 'target1'>intersection</marker> where you wait for the Abrams tanks
to arrive. Then you are to attack the enemy <marker name = 'target2'>base</marker> which 
is your main objective today. Tanks will keep any enemy armor reinforcements off from
the base. 
<br/><br/>

TACTICAL<br/>
The defenses intensify here, take it slow and take out those enemies from distance if
possible. keep your men alive and don't try anything foolish. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture base"];
objective2 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
objective1 = player createSimpleTask ["Clear intersection"];
objective1 setSimpleTaskDescription ["Clear intersection", "Clear intersection", "Clear intersection"];
