//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Velka Ves, will be the next target.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lany, 
capture <marker name = 'target1'>Mala Ves</marker> buildings, 
and <marker name = 'target2'>Velka Ves</marker> town.



<br/>Pink Bag<br/><br/>

GEN SITREP<br/>
This morning the operation Pink Bag is started to capture two enemy positions,
Velka Ves being the main objective. We do not want to move against the bridge 
as of right now because we are not sure if the Russians would blow it up rather
than to give it up to us. We must use caution with the bridge area not to
alarm the enemy.
<br/><br/>

INTEL<br/>
There are some armored vehicles present along with infantry defenses. No enemy 
helicopters are expected to be operating there today.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Lany along with Bravo Abrams
platoon. Mission objectives are <marker name = 'target1'>Mala Ves</marker> and
also <marker name = 'target2'>Velka Ves</marker> being the main objective. Alpha shoud
proceed first to clear out the road for any possible anti armor teams while M1A1's
follow in behind giving cover fire and holding of enemy vehicles. Mission is 
accomplished when both objectives are under NATO control.
<br/><br/>

TACTICAL<br/>
Stay clear of the bridge, keep low when enemy armor in sight and let the Abrams 
blew them away. Other than that... good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Velka Ves"];
objective2 setSimpleTaskDescription ["Capture Velka Ves", "Capture Velka Ves", "Capture Velka Ves"];
objective1 = player createSimpleTask ["Capture Mala Ves"];
objective1 setSimpleTaskDescription ["Capture Mala Ves", "Capture Mala Ves", "Capture Mala Ves"];
