//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Arudy attack, whoah






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Goisse and proceeds
through intersections <marker name = 'target1'>road #1</marker> 
and <marker name = 'target2'>road #2</marker> all the way up 
to <marker name = 'target3'>Arudy</marker> which is to be captured.



Quick Horizon

GEN SITREP<br/>
Arudy area still contains considerable enemy positions which must be taken out. Todays
operation is for three objectives around this important area, two intersections and
the town of Arudy itself. 
<br/><br/>

INTEL<br/>
No enemy air activity is detected, mostly infantry and some vehicles in the operational 
area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Goisse. You must proceed into the 
east towards intersection <marker name = 'target1'>road #1</marker> and clear out all Russians
occupying the area. From there assault intersection <marker name = 'target2'>road #2</marker> in
coordination with <marker name = 'charlie'>Charlie</marker> squad who waits your radio (0-0-1) call
to attack. When both intersections are cleared, assault the town 
of <marker name = 'target3'>Arudy</marker> in the east. When town is secured, support forces
are sent to back you up. Wait for them to arrive. 
<br/><br/>

TACTICAL<br/>
No enemy helos, small number of enemy vehicles... seems like good infantry fight today.
Charlie squad should ease your attack to the second intersection and Arudy. Charlie will
push through intersection into Arudy directly, so just don't sit back when they move.
Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective2 = player createSimpleTask ["Capture Arudy"];
_objective2 setSimpleTaskDescription ["Capture Arudy", "Capture Arudy", "Capture Arudy"];
_objective1 = player createSimpleTask ["Clear our intersection #2"];
_objective1 setSimpleTaskDescription ["Clear our intersection #2", "Clear our intersection #2", "Clear our intersection #2"];
_objective0 = player createSimpleTask ["Clear our intersection #1"];
_objective0 setSimpleTaskDescription ["Clear our intersection #1", "Clear our intersection #1", "Clear our intersection #1"];
