//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I'm getting sick of these AA Sites, but hey we must get helos in the air, 
even more sickening is walking around this island...






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Fuel Depot and proceeds
into <marker name = 'target1'>intersection</marker> seizing it, clearing the road leading 
there. After backups have arrived, attack the <marker name = 'target2'>AA Site</marker> in hill 
top.
<br/><br/>
Good luck.



<br/>Angry Bear<br/><br/>

GEN SITREP<br/>
We must clear a path to our tanks into the upper areas of central malden in
north east of La Pessagne fuel depot. Enemy has heavy defenses here and our
tanks would take a beating if they would try to get through.
<br/><br/>

INTEL<br/>
There is infantry and some armored vehicles North East of La Pessagne fuel 
depot. The AA site is located on the hill top and has at least one shilka 
present. Enemy helicopters are known to be operating in the area.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from Fuel Depot in the 
road, <marker name = 'bravo'>Bravo</marker> team starts due north of your
location. You must clear the road for our tanks (callsign Charlie Black) 
all the way up to the <marker name = 'target1'>intersection</marker> where 
you wait for them. At this time Bravo has taken positions bit south 
west from our main objective, the <marker name = 'target2'>AA Site</marker> in 
the hill top. When bravo and charlier are in positions, assault the
main AA site and neutralize all enemies there. Hold the area secure until
more support forces arrive.
<br/><br/>

TACTICAL<br/>
Ok this is going to be tough fight, make sure you cover all the arcs when approaching
the enemy positions, these bastards can lurk anywhere. Clear out all of them so our
tanks dont get hit by those pesky RPG's today.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Secure until support arrive."];
objective3 setSimpleTaskDescription ["Secure until support arrive.", "Secure until support arrive.", "Secure until support arrive."];
objective2 = player createSimpleTask ["Neutralize AA site"];
objective2 setSimpleTaskDescription ["Neutralize AA site", "Neutralize AA site", "Neutralize AA site"];
objective1 = player createSimpleTask ["Seize intersection"];
objective1 setSimpleTaskDescription ["Seize intersection", "Seize intersection", "Seize intersection"];
