//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This starts to look bad... do I ever see any of my friends again? My God... will
this be beginning of rest of my life.






"]];
player createDiaryRecord ["Diary", ["Mission", "











"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Follow orders, or die."];
objective1 setSimpleTaskDescription ["Follow orders, or die.", "Follow orders, or die.", "Follow orders, or die."];
