//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Ah this time we are descenting, not climbing. Much much better.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from intersection, descent
through the mountain terrain and <marker name = 'target1'>sweep</marker> all
enemies you encounter until you reach <marker name = 'bravo'>Bravo</marker> squad.



Big Sweep

GEN SITREP<br/>
Next large objective is to capture the largest mountain top in Kolgujev, we are
still gathering intel of what the Russians have store for us there. The assault
should be prepared in day or two. In these weather conditions its very difficult
task to complete.
<br/><br/>

INTEL<br/>
The muddy and slippery terrain ahead is not accessible by vehicles so you only
expect to encounter infantry. No enemy helicopters are active today.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the intersection, proceed 
through the mountain terrain and <marker name = 'target1'>sweep</marker> any enemy
forces you encounter. When you reach <marker name = 'bravo'>Bravo</marker> squad in
friendly territory the mission is accomplished.
<br/><br/>

TACTICAL<br/>
Today as you're coming down we have set you up with normal gear, but be careful
even though no vehicles are present. The Russians are still giving us good fight.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep area and meet Bravo"];
_objective0 setSimpleTaskDescription ["Sweep area and meet Bravo", "Sweep area and meet Bravo", "Sweep area and meet Bravo"];
