//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



This is kind of eary... what kind of reaction the Russians will have
for us capturing the airbase. Will they just leave it there, or are they
building a massive counterattack... we are on night watch... its quiet,
almost too quiet out here... and dark...
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

You're on the night watch on the just captured Russian Airbase
<marker name = 'start'>here</marker>. Stay alert, we dont know if Ruskies
decide to make counterattack. 




Night

Our reinforcements have arrived to the Everon airbase. We have our HQ setup now.
<br/><br/>

At this time we have no intel available as we have only sit in the runway and build the
base. No enemy sounds, no patrols, nothing. There must be some sort of enemy counter 
attack on the plan, the Russians can't give up this airbase so easy.
<br/><br/>

You are tasked for first watch for this night. We must keep everything under control
in our newly captured airbase <marker name = 'start'>here</marker>. Stay alert and do not let
any Russians into near the vehicles. There are other troops in the southern part of the
airbase who will maintain the first line of defence.

<br/><br/><br/>












"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Guard the airbase"];
_objective0 setSimpleTaskDescription ["Guard the airbase", "Guard the airbase", "Guard the airbase"];
