//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




One wrong bullet hit and that fuel station goes BOOM.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase, assault
and capture <marker name = 'target1'>Fuel Station</marker> in north west.



<br/>Fuel Fumes<br/><br/>

GEN SITREP<br/>
We are setting up defenses for the airbase, move vulcans to defend it, assigning
guards and patrols. In the mean while there are still Russians holding up on
the Fuel Station which is too near this airbase to safely operate and we always
need the fuel. 
<br/><br/>

INTEL<br/>
Russian air vehicles are pretty much wiped out so your safe from aerial attacks 
on Malden from now on. The armored vehicles have moved into further west from the
airbase. In the fuel station you should not get more than light infantry and perhaps
few light vehicles.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from airbase gates. Assault and capture
the <marker name = 'target1'>Fuel Station</marker> just few click away in the north west
from your location. Try not to waste the whole station.
<br/><br/>

TACTICAL<br/>
Finally the damned hinds are wiped out from this island! Hooyah! Well the fuel station,
nothing much here. be careful not to get too hyped up with our latest victory capturing
the airbase, this war is NOT over yet. Watch your fire near the station itself, don't
let LAW soldiers roam free.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture fuel station"];
objective1 setSimpleTaskDescription ["Capture fuel station", "Capture fuel station", "Capture fuel station"];
