//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Ivan got pissed, they rarely launch counter attacks anymore.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from intersection, defend
it against Russian counter <marker name = 'attack1'>attack</marker> coming from
south west direction.
<br/><br/>
Good luck.



<br/><br/>Bear Lash<br/><br/>

GEN SITREP<br/>
Russian counter attack on way, we must defend the intersection. Do not fall back.
<br/><br/>

INTEL<br/>
Armored contacts and lot of infantry moving your way as we speak. Helos are flying
also in the south west.
<br/><br/>

ORDERS<br/>
Alpha squad with some additional support <marker name = 'start'>start</marker> from the
intersection which you are tasked to defend against Russian 
counter <marker name = 'attack1'>attack</marker> coming from south south west direction. 
Do not let any Russians get through. Good luck.
<br/><br/>

TACTICAL<br/>
Okay they are indeed coming now with full force. Get ready, take accurate shots
and keep your men alive. Stay healthy.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend intersection."];
objective1 setSimpleTaskDescription ["Defend intersection.", "Defend intersection.", "Defend intersection."];
