//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to make the flyboys happy. Thats all that matters in this OP.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from east of Cancon, proceeds to 
the <marker name = 'aasite'>AA Site</marker> and takes it out.



<br/>Fiery Sword<br/><br/>

GEN SITREP<br/>
The Russians are putting together a tough counter attack force which seems to be just
about ready to strike us but not in few hours at least. We must use this advantage and
really hit hard the nearest enemy posts.
<br/><br/>

INTEL<br/>
The enemy AA site due East from Cancon has equipped with one Shilka and some infantry,
there seem to be couple of other vehicles as well defending the site. Malden airbase is
again showing some activity, be adviced for any enemy helos if they get them tasked.
<br/><br/>

ORDERS<br/>
Alpha Black <marker name = 'start'>start</marker> from Buildings east of Cancon, they will 
proceed and neutralize the <marker name = 'aasite'>AA Site</marker> in the hill containing
Shilka and some additional support forces. When the site has been neutralized Alpha will
be look out for any enemy presence in the area.
<br/><br/>

TACTICAL<br/>
Another AA site to take out, all for our fly boys. The other vehicles in the hill have not 
been identified so keep your LAW soldiers alert if they indeed happen to be heavier stuff.
Intel is not sure about the enemy air activity so be ready for them. 
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Neutralize AA site"];
objective1 setSimpleTaskDescription ["Neutralize AA site", "Neutralize AA site", "Neutralize AA site"];
