//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Up in the north west we go.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from Mokropsy. Assault
three enemy positions:<br/>
<marker name = 'target1'>House</marker><br/>
<marker name = 'target2'>Houses</marker><br/>
<marker name = 'target3'>Mountain</marker><br/>



Ghost Guard

GEN SITREP<br/>
Today our operation includes three enemy positions which we are going to
clear out. In the next few days we are pushing into the north west tip of
Nogova, from there we start to move towards south then.
<br/><br/>

INTEL<br/>
Some armored vehicles are in the vicinity, enemy helicopters are operating
far more southern areas. Infantry in defensive positions.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Mokropsy. Assault and
capture the <marker name = 'target1'>House</marker> just west from your starting
location. From there proceed to assault the <marker name = 'target2'>Houses</marker> in
north. When these two objectives are completed, get into 
the <marker name = 'target3'>mountain</marker> and neutralize all Russian forces there.
<br/><br/>

TACTICAL<br/>
There is some ground to cover, keep your men healthy, watch for ambushes and stuff
like that. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective2 = player createSimpleTask ["Clear mountain"];
_objective2 setSimpleTaskDescription ["Clear mountain", "Clear mountain", "Clear mountain"];
_objective1 = player createSimpleTask ["Capture houses"];
_objective1 setSimpleTaskDescription ["Capture houses", "Capture houses", "Capture houses"];
_objective0 = player createSimpleTask ["Capture house"];
_objective0 setSimpleTaskDescription ["Capture house", "Capture house", "Capture house"];
