//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Going for Goisse, Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> near Vigny, 
attack <marker name = 'target'>Goisse</marker> and defend it for any 
counter attacks



Big Spoon

GEN SITREP<br/>
Next objective in our war against the Russians is the town of Goisse located in 
west coast. This should not bee too heavily defended as its rather remote area in
Malden island, but its another important landmark for us to seize.
<br/><br/>

INTEL<br/>
There are some armor present in this sector but not much. Infantry is noticeable.
There seems not to be any enemy helicopter activity however.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> near Vigny, your orders are to proceed
along the coastal road into <marker name = 'target'>Goisse</marker> and capture it. While 
you do so, clear out any possible enemies that you come across. When you have neutralized
all enemies there, set up defensive pasture so that you can repel the most likely
enemy counter attack. 
<br/><br/>

TACTICAL<br/>
No enemy helos, not much armor... hey this should be a piece of cake. Anyways be careful
as we are talking about the enemy front lines here. Expect anything and you'll do fine.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Defend Goisse"];
_objective1 setSimpleTaskDescription ["Defend Goisse", "Defend Goisse", "Defend Goisse"];
_objective0 = player createSimpleTask ["Capture Goisse"];
_objective0 setSimpleTaskDescription ["Capture Goisse", "Capture Goisse", "Capture Goisse"];
