//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This is the big one, Petrovice. street fighting. brr.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Vidlakov. Clear the
three locations:<br/>
<marker name = 'target1'>Fuel Station</marker><br/>
<marker name = 'target2'>South East houses</marker><br/>
<marker name = 'target3'>North East houses</marker>
<br/><br/>
And finally <marker name = 'target4'>Petrovice</marker> must be captured.



<br/><br/>Cosmopolitan Order<br/><br/>

GEN SITREP<br/>
Our big assault has come, the large capital city of Petrovice is coming 
under NATO attack today. We must first clear the nearby areas from enemy
soldiers so that our vehicles can safely engage the main target. When the
areas are cleared, the assault is initiated and all forces strike the
city.
<br/><br/>

INTEL<br/>
The nearby areas are mostly defended by infantry which are waiting for our
attack, some anti armor teams have been detected near the houses around main
target. There are some BMP patrols in the area but no heavy tanks. The Petrovice
itself is extremely heavily defended, there is T-80 tanks in the city as well
as other heavy armor, anti armor teams on the ground and snipers in the rooftops.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Vidlakov. You must clear the 
surrounding areas near Petrovice. These are 
the <marker name = 'target1'>fuel station</marker> by the road, 
the <marker name = 'target2'>south east houses</marker> in the field and then
the <marker name = 'target3'>north east houses</marker> also. When these are cleared
from enemy infantry, use radio call (0-0-1) to initiate the assault when all
forces start the attack. The forces are; <marker name = 'bravo1'>Bravo</marker> inf 
squad, <marker name = 'charlie1'>Charlie</marker> M1A1 Abrams platoon and AH-64 Apache
gunship. Mission is accomplished when all Russians are run off from Petrovice. 
Good luck.
<br/><br/>

TACTICAL<br/>
This is the big one. Do not engage the city before the infantry is eliminated from
the objectives around it. You are outgunned by far if you go there alone. Also when
you have cleared the infantry, you do not need to call the assault immediately, you
can do some recon first. Be careful with this one, good luck.
<br/>












"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Capture Petrovice"];
objective4 setSimpleTaskDescription ["Capture Petrovice", "Capture Petrovice", "Capture Petrovice"];
objective3 = player createSimpleTask ["Clear north east houses"];
objective3 setSimpleTaskDescription ["Clear north east houses", "Clear north east houses", "Clear north east houses"];
objective2 = player createSimpleTask ["Clear south east houses"];
objective2 setSimpleTaskDescription ["Clear south east houses", "Clear south east houses", "Clear south east houses"];
objective1 = player createSimpleTask ["Clear fuel station"];
objective1 setSimpleTaskDescription ["Clear fuel station", "Clear fuel station", "Clear fuel station"];
