//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Mirov is falling today, no doubt about that.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road. First clear out
the <marker name = 'target1'>Fuel Station</marker> then proceed and capture
the <marker name = 'target2'>intersection</marker> and wait for backup. When
they arrive enter into <marker name = 'target3'>Mirov</marker> and capture it.
<br/><br/>
Good luck.



<br/><br/>Steel Uniform<br/><br/>

GEN SITREP<br/>
Our grattitude goes out to the professional soldiers who handled the hostage
situation in Lipany, the hostages got freed and Nogova people are very happy
for the outcome. In the mean time our base securitys are on elevated level to
prevent any such scenarios in the future. Today we have large operation in hand
as we assault the city of Mirov and the few positions near it, we must try not
to destroy too much of the buildings in the city.
<br/><br/>

INTEL<br/>
The fuel station has minimal infantry defenses and few vehicles have been spotted
to refuel there. The intersection is more heavily defended as its the choke point
to enter into Mirov. The city itself has strong defenses from both infantry and
armored vehicles.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the road. Clear out all Russians
from the <marker name = 'target1'>Fuel Station</marker> area and the church. Next you 
must capture the <marker name = 'target2'>intersection</marker> to cut off any 
reinforcements the enemy might send to the city. Lastly you are to capture 
city of <marker name = 'target3'>Mirov</marker> and the additional buildings around it.
<br/><br/>

TACTICAL<br/>
Be alert on this mission, if you enter the Mirov directly from the intersection then
you run over the ridge and pop out only few meters away from the city buildings. I'd
suggest you take alternate route to give more range to fire.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Mirov"];
objective3 setSimpleTaskDescription ["Capture Mirov", "Capture Mirov", "Capture Mirov"];
objective2 = player createSimpleTask ["Capture intersection"];
objective2 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
objective1 = player createSimpleTask ["Clear fuel station"];
objective1 setSimpleTaskDescription ["Clear fuel station", "Clear fuel station", "Clear fuel station"];
