//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Intel peeps found me some more lurking Russians, time to go take them
out.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, sweep the
coast <marker name = 'target1'>area</marker> for lurking Russians. Return to base 
with helo.



<br/>Coast Shield<br/><br/>

GEN SITREP<br/>
There is still few remaining Russians popping up here and there, they must have
been hiding in the forests trying to regroup into the coast line to get boats 
any kind of boats out of Kolgujev. We have spotted another group which we want
to be taken out before they can leave the island.
<br/><br/>

INTEL<br/>
There are few Russians spotted in the north west coast, they are unorganized and
poorly equipped, trying to hide. They obviously are trying to get boat ride out
of the island.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base in east coast on board
Black Hawk which will fly you into the <marker name = 'insert'>insertion</marker> point
in the road near the northern coast. Proceed into 
the <marker name = 'target1'>beach</marker> and search hiding enemy soldiers there and 
neutralize them. When you are done, use radio call (0-0-1) to call the black hawk 
to fly you back to base.
<br/><br/>

TACTICAL<br/>
This should be another cake walk for you, but don't get cocky out there. Do the job
like the professional you are. 
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear coast"];
objective1 setSimpleTaskDescription ["Clear coast", "Clear coast", "Clear coast"];
