//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Still rains like there is no tomorrow... that dirt road is going to be difficult 
to sweep as there are such harsh terrain around it. Caution, caution...






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from intersection, proceed
into NATO <marker name = 'target1'>base</marker> along the road.



Rainy Hope

GEN SITREP<br/>
We had good results on the northern coastal road today, it has now been captured 
and friendly forces soon can travel through it to the central island. But first we
must clear out the southern or upper part of the dirt road also. Its still considered
as enemy territory and today we send a squad to sweep that road.
<br/><br/>

INTEL<br/>
There should be only infantry in the dirt road from the intersection up to the 
NATO base. No enemy helicopters are present in the area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the intersection, you are to 
slowly advance along the road (more or less, your choise) all the way up to the
friendly NATO <marker name = 'target1'>base</marker> where you meet Bravo squad. Mission
is accomplished when you reach the base.
<br/><br/>

TACTICAL<br/>
The road is cleared, except the northern dirt road part. Sweep it through, do not
leave any russians lurking in there. Use caution, good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep road to the base"];
_objective0 setSimpleTaskDescription ["Sweep road to the base", "Sweep road to the base", "Sweep road to the base"];
