//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Ok we left the heavy weapons behind as this terrain is too demanding to be
dragging all that gear behind us, since we aren't expecting any vehicles
in the rough terrain. As always that makes me feel quite naked, not to have
some heavies around. Oh well, all in days work, time to go. Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> near the fuel depot. Sweep
the <marker name = 'target1'>terrain</marker> until you 
reach <marker name = 'bravo'>bravos</marker> position.



Sharp Sweep

GEN SITREP<br/>
Russians have been kept back from the newly captured fuel depot with great
success thanks to experienced troops. There is no imminent attack on the
scope at the moment. The weather still does not have any changes in near future,
it keeps raining and having thunder storms all over the Kolgujev. It makes 
difficult to move our armor around anywhere else expect paved roads.
<br/><br/>

INTEL<br/>
As the weather conditions are this bad and the terrain is very rough, there is
no vehicles present in the area north north-east of the fuel depot. You'll be
looking for just infantry. Also enemy helicoptes seem to keep a good distance
to this area.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> near the fuel depot. You are to
sweep the <marker name = 'target1'>terrain</marker> in general area of north east
from the starting position. Basically you push towards 
the <marker name = 'bravo'>Bravos</marker> positions neutralizing all encountered 
enemies in the path. Mission is accomplished when you reach Bravo squad.
<br/><br/>

TACTICAL<br/>
This is bad weather in bad terrain. God loves the infantry! OK just be careful
out there, should be quite easy as you are only expecting infantry, there are
no damned vehicles that can drive in that crazy and muddy mountain this time.
Oh yeah and you should leave all the heavy weapons behind, they just slow you
down up there.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Sweep terrain and reach Bravo."];
_objective0 setSimpleTaskDescription ["Sweep terrain and reach Bravo.", "Sweep terrain and reach Bravo.", "Sweep terrain and reach Bravo."];
