//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Russian counter attack on our way!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha squad <marker name = 'start'>start</marker> from the beach. Secure the beach
for <marker name = 'invasion'>invasion</marker> and stay alive!




<br/>Vigilant Anvil<br/><br/>

GEN SITREP<br/>
Russians are sending their first wave of counter attack to the beachhead invaded 
by NATO. We are still deploying our vehicles to the beach and we must hold it at
all costs.
<br/><br/>

INTEL<br/>
There is lot of activity on the Malden Airbase and we surely can expect some helicopters
on our way shortly. Also first armored vehicles have been spotted North West of Cancon.
<br/><br/>

ORDERS<br/>
Alpha squad is on the <marker name = 'start'>beach</marker> securing it as vehicles 
and troops are <marker name = 'invasion'>deployed</marker> You must hold the Russians 
back at all costs.
<br/><br/>

TACTICAL<br/>
There is some vehicles coming and the bad news is that helicopters are on the way too.
We have ammo truck deploying to the starting location so get some ammo from it, mainly
Stinger missiles so you can shoot down any incoming enemy helos.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Secure the beach"];
objective1 setSimpleTaskDescription ["Secure the beach", "Secure the beach", "Secure the beach"];
