//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




First the mountain top, then some coastal areas. I just need to keep
my steps sharp out there in the edge of the coastal mountain range.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from houses. Assault the
<marker name = 'target1'>mountains</marker> north from your position and the coast
in <marker name = 'target2'>east</marker> and <marker name = 'target3'>west</marker> area.
<br/><br/>
Good luck.



<br/><br/>Nogova Star<br/><br/>

GEN SITREP<br/>
The northern area of our positions is still under Russian control and today we
move against that area as we want to have our backs clear. There is high mountains 
and deep drops in the coastal region so our forces must use caution when operating 
in this difficult terrain.
<br/><br/>

INTEL<br/>
Infantry mostly, might be one or two BMP's hiding somewhere but nothing major
on the armored vehicles. Enemy helos are operating but much more southern areas.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from houses. Proceed into the
objectives and clear out <marker name = 'target1'>mountains</marker> first, then
the <marker name = 'target2'>east</marker> coast and 
the <marker name = 'target3'>west</marker> coast. You have AH-1 Cobra patrolling the 
area so he can provide you some CAS.
<br/><br/>

TACTICAL<br/>
Ok this should be easy one, infantry fight mostly. The Cobra is nice protection
against any possible vehicles out there. He might actually find some soldiers
patrolling there too.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Clear west coast"];
objective3 setSimpleTaskDescription ["Clear west coast", "Clear west coast", "Clear west coast"];
objective2 = player createSimpleTask ["Clear east coast"];
objective2 setSimpleTaskDescription ["Clear east coast", "Clear east coast", "Clear east coast"];
objective1 = player createSimpleTask ["Clear mountain"];
objective1 setSimpleTaskDescription ["Clear mountain", "Clear mountain", "Clear mountain"];
