//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




These darn scuds! They are nasty things which must be taken out.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from base, hunt down
and destroy two enemy <marker name = 'target1'>scud</marker> launchers.
Meet with <marker name = 'charlie1'>Charlie</marker> squad to end mission.



Black Phoenix

GEN SITREP<br/>
Enemy has launched few Scuds to NATO targets, we must now hunt them down and
destroy them at all costs. All operations are halt until the scuds are taken out.
<br/><br/>

INTEL<br/>
We had a jackpot, one of our intel birds detected the Scud launches and we have
been tracking them ever since. They got resupply missiles earlier today and are
no refitting them to make another launch.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base, UH-60 Black Hawk will
then <marker name = 'insert'>insert</marker> your team just SE of 
the expected <marker name = 'target1'>Scud</marker> launch area. Seek the Scuds out and 
destroy both of them. When they are destroyed, return to friendly positions and 
meet <marker name = 'charlie1'>Charlie</marker> squad there. Good hunting.
<br/><br/>

TACTICAL<br/>
Okay those damned missiles must be taken out, you are our best soldier for the job.
Don't play a hero out there, if you can evade enemy patrols, DO IT. You'll have plenty
of stuff to blow up when you find the Scuds. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
_objective1 = player createSimpleTask ["Meet Charlie squad"];
_objective1 setSimpleTaskDescription ["Meet Charlie squad", "Meet Charlie squad", "Meet Charlie squad"];
_objective0 = player createSimpleTask ["Destroy Scuds"];
_objective0 setSimpleTaskDescription ["Destroy Scuds", "Destroy Scuds", "Destroy Scuds"];
