//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




The last remaining pipeline. yeah, shutting it down is going to be fun.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Valley, board black hawk
which will insert you to Velka Ves. Proceed to 
the <marker name = 'target1'>road</marker> and set up a ambush there.



<br/><br/>Hard Rock<br/><br/>

GEN SITREP<br/>
Our forces performed very well yesterday assaulting the enemy infested valley
in the north, we totally control the area at this moment. Todays objective is
to shut down the road along the river that leads into the Trosky area from Velka Ves.
This is the only passable area for vehicles connecting eastern and western Nogova in
the north. The enemy would use this road to run some more infantry trucks and armored
vehicles to near our positions.
<br/><br/>

INTEL<br/>
No helicopters are active in the air now, we estimate there is no air threat today. 
The road has only minimal infantry skeleton as defense, there has been some activity 
up north and its very likely that we encounter some vehicles today in the road. Be 
careful with the west shore of the river as its so close some enemies might be able
to fire at you. The west side of the river has heavy enemy concentrations.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the valley. Board the Black Hawk thats
coming to pick you up and ride into <marker name = 'insert'>Velka Ves</marker> which is your
insertion point. From the village proceed into the <marker name = 'target1'>road</marker> by
the river and our front line positions up the mountain. Along this path clear out any and
all enemy forces you encounter, the road must be cleared completely. When you are near the
ambush point, use radio call (0-0-1) to call <marker name = 'bravo'>Bravo</marker> squad to 
join you. Set up ambush in the rocks and wait for any possible enemy troops travelling 
towards Velka Ves.
<br/><br/>

TACTICAL<br/>
This is going to be ambush time... only if you encounter any enemy forces in that road.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Ambush possible enemies"];
objective2 setSimpleTaskDescription ["Ambush possible enemies", "Ambush possible enemies", "Ambush possible enemies"];
objective1 = player createSimpleTask ["Clear road"];
objective1 setSimpleTaskDescription ["Clear road", "Clear road", "Clear road"];
