//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



This is indeed weird, I'm training at warzone. The front lines aren't even 10 clicks away
and I'm training. Heheh cool.
<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
Welcome to some special training.<br/><br/>

We have had some sortage of capable men rescuing some high value personel behind enemy lines,
since your record shows a successful rescue mission in war time, you get to be amongst the
first to be trained into these situations.<br/><br/>

There is simulated enemy <marker name = 'camp'>camp</marker> set up, it has some soft and hard
targets for you to takedown, in one of the tents you'll find civilian element which you 
must rescue with fastest possible way. Do not let him get out of the tent before all
targets are neutralized.<br/><br/>

Uhm for this one I cannot really wish you a good luck, so ...<br/><br/>

Have fun!










"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Rescue high value personel"];
_objective0 setSimpleTaskDescription ["Rescue high value personel", "Rescue high value personel", "Rescue high value personel"];
