//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Today is the star of a Scud hunt, I like it. Okay this is going to take few
days and nights behind enemy lines so I must be very very careful.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airstrip, you are 
to <marker name = 'target1'>search and destroy</marker> enemy scud launchers. Then
reach <marker name = 'camp'>camping</marker> point.
<br/><br/>
Good luck and be careful!



<br/><br/>Scud Hunt Day 1<br/><br/>

GEN SITREP<br/>
Our base in the airstrip was attacked by Scud missiles yesterday causing several
casualties, the missiles were launched from somewhere in eastern Nogova. Today we
are sending infantry troops to seek out those missiles and destroy them. These
troops have only one goal, scuds, scuds and nothing but scuds.
<br/><br/>

INTEL<br/>
We haven't optained the exact location of the scuds and most likely they are 
moving them around so we could not track them. The enemy has been moving more
troops into the eastern Novoga during the night, we also believe there can be
anti air threat present.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the airstrip, helicopter 
will <marker name = 'insert'>insert</marker> you to the mountain. From that position
you are to conduct <marker name = 'target1'>search and destroy</marker> operation 
against enemy Scud launchers. Your rules of engagement are: Scuds, scuds and 
nothing but scuds. Consider all other targets as secondary. When you reach 
the <marker name = 'camp'>camping</marker> location, set up there for some rest overnight. 
Your mission is accomplished when you have reached the forest camping location and possibly
taken out the hidden scud launchers.
<br/><br/>

TACTICAL<br/>
This is a Scud hunt. Those darn scuds! I hate them! When you are in behind enemy
lines, try to avoid enemy contact if there is no Scuds present. Its waste of ammo
to fight other targets as your mission specificly is against scud launchers. Also
when you attack, do it fast and escape as the enemies are sure to launch search
parties after you. Also since you are camping behind enemy lines for few days, keep
your men alive and healthy with plenty of ammo. Reserve your ammunition, especially LAW's. 
Good luck... and bag me some Scud missiles! Good hunting!
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Reach campign location"];
objective2 setSimpleTaskDescription ["Reach campign location", "Reach campign location", "Reach campign location"];
objective1 = player createSimpleTask ["Search and destroy Scuds"];
objective1 setSimpleTaskDescription ["Search and destroy Scuds", "Search and destroy Scuds", "Search and destroy Scuds"];
