//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Another batch of civilians to free. Seems like no biggie.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from airstrip. Clear out
the <marker name = 'target1'>buildings</marker> and evacuate civilians.



Op Liberty

GEN SITREP<br/>
There are some civilians that have requested evacuation and we are going
to provide them just that. They live in the farm area near Bitov and Lany 
and are waiting for our troops there. Its been reported that there are light
Russian infantry presence in the farms, so we must first clear out the area
before civilians can be airlifted out of there.
<br/><br/>

INTEL<br/>
There should be very light infantry patrols in the area, no enemy helicopters
or vehicles are reported.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the airstrip, you will be 
helicopter <marker name = 'insert'>inserted</marker> into south west of the 
target <marker name = 'target1'>buildings</marker> which you must clear. When the 
area is cleared, meet with the civilian group and evacuate them into the
helicopter using radio (0-0-1) when area is safe. Be careful what you shoot
out there, the target buildings contains innocent civilians. Do not, I repeat
do NOT fire at them. Make this one quick, clear the area, call the chopper to
pick you up and get home.
<br/><br/>

TACTICAL<br/>
This should be easy one. Watch what you shoot at and when all the Russians are
neutralized, meet with the civis and get them aboard the black hawk which will
bring all of you back to NATO base. Just make this quick, we do not know what
the Ivan might send to that area when you start to make noise. Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective4 = player createSimpleTask ["Board chinook and return home"];
_objective4 setSimpleTaskDescription ["Board chinook and return home", "Board chinook and return home", "Board chinook and return home"];
_objective3 = player createSimpleTask ["Secure Crash Site until the"];
_objective3 setSimpleTaskDescription ["Secure Crash Site until the", "Secure Crash Site until the", "Secure Crash Site until the"];
_objective2 = player createSimpleTask ["Locate pilots"];
_objective2 setSimpleTaskDescription ["Locate pilots", "Locate pilots", "Locate pilots"];
_objective1 = player createSimpleTask ["Locate Downed Blackhawk"];
_objective1 setSimpleTaskDescription ["Locate Downed Blackhawk", "Locate Downed Blackhawk", "Locate Downed Blackhawk"];
_objective0 = player createSimpleTask ["Clear houses, meet civilians"];
_objective0 setSimpleTaskDescription ["Clear houses, meet civilians", "Clear houses, meet civilians", "Clear houses, meet civilians"];
