//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That was big fight yesterday, it almost got exciting out there. Oh well today we
move forward to the Lany, lets see how it goes.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lipany. Assault
and capture <marker name = 'target1'>Lany</marker> town.



<br/>Fiery Warrior<br/><br/>

GEN SITREP<br/>
Our war continues on Nogova, today we will take another piece of Russian occupied
real estate, the town called Lany. There is some unconfirmed reports on Russians
setting up heavier defenses more to the north and west Nogova, the bridge is 
reported to be heavily defended already.
<br/><br/>

INTEL<br/>
You'll be facing mostly infantry, some armored vehicles. No enemy helicopters are
to be expected.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from Lipany. You are to assault the
town of <marker name = 'target1'>Lany</marker> with the road intersection. The mission
is accomplished when you have the town under control. Good luck.
<br/><br/>

TACTICAL<br/>
Good work on Lipany operation, nicely done. Todays mission with the Lany assault 
should be pretty good if all things go well.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Lany"];
objective1 setSimpleTaskDescription ["Capture Lany", "Capture Lany", "Capture Lany"];
