//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




I feel like traffic cop with these intersections.






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'start'>start</marker> from base, seize the
enemy <marker name = 'target1'>intersection</marker> checkpoint south west
of your base.



Determined Tree

GEN SITREP<br/>
Our weather team has now confirmed that the storm front is indeed now moving towards
Kolgujev, so in near future we can expect some poor weather. Today the final 
preparations are being put together for our next large assault where objective is the 
enemy base in the mountain ridge. These include seizure of the intersection that could
be used by armored vehicles to travel to the base.
<br/><br/>

INTEL<br/>
There is some armored vehicles ahead along with the normal heavy infantry defenses. No
helicopters are present at the moment. There are more vehicles stationed in the ruins
west of the intersection, but they seem to be in defesive positions and not to be expected
to join the fight.
<br/><br/>

ORDERS<br/>
Alpha squad <marker name = 'start'>start</marker> from the base, you are to attack and seize
the enemy road <marker name = 'target1'>intersection</marker> just south west from our base.
Neutralize all enemy forces in the intersection so you have full control over it, we must
make it blocked for enemy vehicles. When you have control over it, we will send you bravo
squad to back you up, they are specialized in anti armor and heavy weapons.
<br/><br/>

TACTICAL<br/>
This should be quite straight forward, go there and wipe them out. They have dug in positions
so move carefully, try to take them out from distance.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Seize intersection"];
_objective0 setSimpleTaskDescription ["Seize intersection", "Seize intersection", "Seize intersection"];
