//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




My God... Russians are attacking with full speed...

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "
See War Situation for details.<br/><br/>

Alpha team <marker name = 'alpha'>start</marker> from the field, 
and <marker name = 'bravo'>Bravo</marker> starts SW from Cancon. Defend the positions
at all costs.
<br/><br/>

Good luck soldiers!



Steel Warrior

GEN SITREP<br/>
Russian attack is on its way. Infantry, Armor and Air assets are bearing upon us
as we speak. We must hold the grounds at all costs and defend the invaded beach.
<br/><br/>

INTEL<br/>
We have reports on multiple enemy armored vehicle contacts, high numbers of infantry 
as well as helicopters that are heading in the general Cancon area. Expect attack in
any minute from land and from air.
<br/><br/>

ORDERS<br/>
Alpha squad is located <marker name = 'alpha'>here</marker> just South East of the hill 
with M1A1 Abrams tanks. <marker name = 'bravo'>Bravo</marker> squad is South West from 
Cancon.
<br/><br/>

TACTICAL<br/>
Stay low try to let the armor first blow the enemy tanks away before engaging the infantry.
Also watch for the enemy choppers and hope that Vulcans can knock them out of the sky.
<br/><br/>













"]];
// tasks need to be in reversed order
_objective0 = player createSimpleTask ["Defend positions"];
_objective0 setSimpleTaskDescription ["Defend positions", "Defend positions", "Defend positions"];
