//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Man do I love defending these ruins. But this is the front line, I'm tasked to it
and that is it... no more questions. Lets fight.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, defend them against
all possible enemy attacks.



<br/><br/>Tall Coyote<br/><br/>

GEN SITREP<br/>
Weather front keeps closing in, its no confirmed to be as bad as predicted. Tomorrow
morning we have a full storm over at Kolgujev. The enemy seems to grown fond of the
ruins as they are launching second counter attack against it. We will defend it. 
There is alpha black and some additional troops tasked to the defenses. We would like
to have armored support but its still not possible.
<br/><br/>

INTEL<br/>
There is armored movement in the north west, its possible they heading this way. 
Infantry seem to be gearing up for assault. No helicopters are active. Get ready. 
<br/><br/>

ORDERS<br/>
Alpha squad is tasked to <marker name = 'start'>defend</marker> the ruins. Your backup
will be Bravo squad who will be flown in with helicopter as soon as possible. Also
the ammunition resupply is coming with a five ton truck from the NATO base at 
north east. Keep the ruins area secure so the truck and bravo can arrive safely.
<br/><br/>

TACTICAL<br/>
First objective is to keep the area clear, you do not want to get our backup team 
blown to bits no do you? No helos so all you need to keep an eye is the ground. Good luck!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend ruins"];
objective1 setSimpleTaskDescription ["Defend ruins", "Defend ruins", "Defend ruins"];
